package models

func (a *A_ATTRIBUTE_DEFINITION_XHTML_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_XHTML_REF
}

func (a *A_ATTRIBUTE_DEFINITION_STRING_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_STRING_REF
}

func (a *A_ATTRIBUTE_DEFINITION_BOOLEAN_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_BOOLEAN_REF
}

func (a *A_ATTRIBUTE_DEFINITION_INTEGER_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_INTEGER_REF
}

func (a *A_ATTRIBUTE_DEFINITION_DATE_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_DATE_REF
}

func (a *A_ATTRIBUTE_DEFINITION_REAL_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_REAL_REF
}

func (a *A_ATTRIBUTE_DEFINITION_ENUMERATION_REF) GetRef() string {
	return a.ATTRIBUTE_DEFINITION_ENUMERATION_REF
}
