// generated from ng_file_enum.ts.go
export enum GongFilePerStructSubTemplateId {
	// insertion point	
	GongFileFieldSubTmplAssociationNameCompositePointerField = 21,
	GongFileFieldSubTmplAssociationNameCompositeSliceOfPointersField = 22,
	GongFileFieldSubTmplAssociationNamePointerField = 19,
	GongFileFieldSubTmplAssociationNameSliceOfPointersField = 20,
	GongFileFieldSubTmplPointerFieldAssociationMapFunction = 23,
	GongFileFieldSubTmplPointerFieldPointerAssociationMapFunction = 25,
	GongFileFieldSubTmplPointerFieldSliceOfPointersAssociationMapFunction = 26,
	GongFileFieldSubTmplSetBasicFieldBool = 0,
	GongFileFieldSubTmplSetBasicFieldEnumInt = 3,
	GongFileFieldSubTmplSetBasicFieldEnumString = 2,
	GongFileFieldSubTmplSetBasicFieldFloat64 = 4,
	GongFileFieldSubTmplSetBasicFieldInt = 1,
	GongFileFieldSubTmplSetBasicFieldString = 5,
	GongFileFieldSubTmplSetPointerField = 7,
	GongFileFieldSubTmplSetSliceOfPointersField = 8,
	GongFileFieldSubTmplSetTimeField = 6,
	GongFileFieldSubTmplSliceOfPointersFieldAssociationMapFunction = 24,
	GongFileFieldSubTmplStringFieldName = 9,
	GongFileFieldSubTmplStringValueBasicFieldBool = 10,
	GongFileFieldSubTmplStringValueBasicFieldEnumInt = 13,
	GongFileFieldSubTmplStringValueBasicFieldEnumString = 12,
	GongFileFieldSubTmplStringValueBasicFieldFloat64 = 14,
	GongFileFieldSubTmplStringValueBasicFieldInt = 11,
	GongFileFieldSubTmplStringValueBasicFieldString = 15,
	GongFileFieldSubTmplStringValuePointerField = 17,
	GongFileFieldSubTmplStringValueSliceOfPointersField = 18,
	GongFileFieldSubTmplStringValueTimeField = 16,
}

export interface GongFilePerStructSubTemplateIdSelect {
	value: number;
	viewValue: string;
}

export const GongFilePerStructSubTemplateIdList: GongFilePerStructSubTemplateIdSelect[] = [ // insertion point	
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplAssociationNameCompositePointerField, viewValue: "GongFileFieldSubTmplAssociationNameCompositePointerField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplAssociationNameCompositeSliceOfPointersField, viewValue: "GongFileFieldSubTmplAssociationNameCompositeSliceOfPointersField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplAssociationNamePointerField, viewValue: "GongFileFieldSubTmplAssociationNamePointerField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplAssociationNameSliceOfPointersField, viewValue: "GongFileFieldSubTmplAssociationNameSliceOfPointersField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplPointerFieldAssociationMapFunction, viewValue: "GongFileFieldSubTmplPointerFieldAssociationMapFunction" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplPointerFieldPointerAssociationMapFunction, viewValue: "GongFileFieldSubTmplPointerFieldPointerAssociationMapFunction" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplPointerFieldSliceOfPointersAssociationMapFunction, viewValue: "GongFileFieldSubTmplPointerFieldSliceOfPointersAssociationMapFunction" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetBasicFieldBool, viewValue: "GongFileFieldSubTmplSetBasicFieldBool" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetBasicFieldEnumInt, viewValue: "GongFileFieldSubTmplSetBasicFieldEnumInt" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetBasicFieldEnumString, viewValue: "GongFileFieldSubTmplSetBasicFieldEnumString" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetBasicFieldFloat64, viewValue: "GongFileFieldSubTmplSetBasicFieldFloat64" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetBasicFieldInt, viewValue: "GongFileFieldSubTmplSetBasicFieldInt" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetBasicFieldString, viewValue: "GongFileFieldSubTmplSetBasicFieldString" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetPointerField, viewValue: "GongFileFieldSubTmplSetPointerField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetSliceOfPointersField, viewValue: "GongFileFieldSubTmplSetSliceOfPointersField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSetTimeField, viewValue: "GongFileFieldSubTmplSetTimeField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplSliceOfPointersFieldAssociationMapFunction, viewValue: "GongFileFieldSubTmplSliceOfPointersFieldAssociationMapFunction" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringFieldName, viewValue: "GongFileFieldSubTmplStringFieldName" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueBasicFieldBool, viewValue: "GongFileFieldSubTmplStringValueBasicFieldBool" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueBasicFieldEnumInt, viewValue: "GongFileFieldSubTmplStringValueBasicFieldEnumInt" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueBasicFieldEnumString, viewValue: "GongFileFieldSubTmplStringValueBasicFieldEnumString" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueBasicFieldFloat64, viewValue: "GongFileFieldSubTmplStringValueBasicFieldFloat64" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueBasicFieldInt, viewValue: "GongFileFieldSubTmplStringValueBasicFieldInt" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueBasicFieldString, viewValue: "GongFileFieldSubTmplStringValueBasicFieldString" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValuePointerField, viewValue: "GongFileFieldSubTmplStringValuePointerField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueSliceOfPointersField, viewValue: "GongFileFieldSubTmplStringValueSliceOfPointersField" },
	{ value: GongFilePerStructSubTemplateId.GongFileFieldSubTmplStringValueTimeField, viewValue: "GongFileFieldSubTmplStringValueTimeField" },
];
