// file generated by gong
// go module version: v0.0.0-20260713025214-28bcb487d015+dirty
/* to edit this file with the default probe, use the command
go run github.com/fullstack-lang/gong/dsm/phylla/go/probe/cmd/probe@v0.0.0-20260713025214-28bcb487d015 stage.go
*/
package main

import (
	"slices"
	"time"

	"github.com/fullstack-lang/gong/dsm/phylla/go/models"
	// injection point for ident package import declaration{{ImportPackageDeclaration}}
)

// generated in order to avoid error in the package import
// if there are no elements in the stage to marshall
var (
	_ time.Time
	_ = slices.Index[[]int, int]
)

// function will stage objects
func _(stage *models.Stage) {

	// insertion point for declaration of instances to stage

	__ArcNormalVectorShape__00000966_ := (&models.ArcNormalVectorShape{Name: `Plant 1-ArcNormalVectorShapeGrid-0`}).Stage(stage)
	__ArcNormalVectorShape__00000967_ := (&models.ArcNormalVectorShape{Name: `Plant 1-ArcNormalVectorShapeGrid-1`}).Stage(stage)
	__ArcNormalVectorShape__00000968_ := (&models.ArcNormalVectorShape{Name: `Plant 1-ArcNormalVectorShapeGrid-2`}).Stage(stage)

	__ArcNormalVectorShapeGrid__00000000_ := (&models.ArcNormalVectorShapeGrid{Name: `Plant 1-ArcNormalVectorShapeGrid`}).Stage(stage)

	__AxesShape__00000000_ := (&models.AxesShape{Name: `Plant 1-AxesShape`}).Stage(stage)

	__BaseVectorShape__00005434_ := (&models.BaseVectorShape{Name: `Plant 1-BaseVectorShapeGrid-0`}).Stage(stage)
	__BaseVectorShape__00005435_ := (&models.BaseVectorShape{Name: `Plant 1-BaseVectorShapeGrid-1`}).Stage(stage)
	__BaseVectorShape__00005436_ := (&models.BaseVectorShape{Name: `Plant 1-BaseVectorShapeGrid-2`}).Stage(stage)

	__BaseVectorShapeGrid__00000000_ := (&models.BaseVectorShapeGrid{Name: `Plant 1-BaseVectorShapeGrid`}).Stage(stage)

	__BottomEndArcShapeV2__00000566_ := (&models.BottomEndArcShapeV2{Name: `Plant 1-BottomEndArcShapeV2Grid-0`}).Stage(stage)
	__BottomEndArcShapeV2__00000567_ := (&models.BottomEndArcShapeV2{Name: `Plant 1-BottomEndArcShapeV2Grid-1`}).Stage(stage)
	__BottomEndArcShapeV2__00000568_ := (&models.BottomEndArcShapeV2{Name: `Plant 1-BottomEndArcShapeV2Grid-2`}).Stage(stage)

	__BottomEndArcShapeV2Grid__00000000_ := (&models.BottomEndArcShapeV2Grid{Name: `Plant 1-BottomEndArcShapeV2Grid`}).Stage(stage)

	__BottomStartArcShapeV2__00000566_ := (&models.BottomStartArcShapeV2{Name: `Plant 1-BottomStartArcShapeV2Grid-0`}).Stage(stage)
	__BottomStartArcShapeV2__00000567_ := (&models.BottomStartArcShapeV2{Name: `Plant 1-BottomStartArcShapeV2Grid-1`}).Stage(stage)
	__BottomStartArcShapeV2__00000568_ := (&models.BottomStartArcShapeV2{Name: `Plant 1-BottomStartArcShapeV2Grid-2`}).Stage(stage)

	__BottomStartArcShapeV2Grid__00000000_ := (&models.BottomStartArcShapeV2Grid{Name: `Plant 1-BottomStartArcShapeV2Grid`}).Stage(stage)

	__EndArcShape__00006270_ := (&models.EndArcShape{Name: `Plant 1-EndArcShapeGrid-0`}).Stage(stage)
	__EndArcShape__00006271_ := (&models.EndArcShape{Name: `Plant 1-EndArcShapeGrid-1`}).Stage(stage)
	__EndArcShape__00006272_ := (&models.EndArcShape{Name: `Plant 1-EndArcShapeGrid-2`}).Stage(stage)

	__EndArcShapeGrid__00000000_ := (&models.EndArcShapeGrid{Name: `Plant 1-EndArcShapeGrid`}).Stage(stage)

	__EndArcShapeV2__00003196_ := (&models.EndArcShapeV2{Name: `Plant 1-EndArcShapeV2Grid-0`}).Stage(stage)
	__EndArcShapeV2__00003197_ := (&models.EndArcShapeV2{Name: `Plant 1-EndArcShapeV2Grid-1`}).Stage(stage)
	__EndArcShapeV2__00003198_ := (&models.EndArcShapeV2{Name: `Plant 1-EndArcShapeV2Grid-2`}).Stage(stage)

	__EndArcShapeV2Grid__00000000_ := (&models.EndArcShapeV2Grid{Name: `Plant 1-EndArcShapeV2Grid`}).Stage(stage)

	__ExplanationTextShape__00000000_ := (&models.ExplanationTextShape{Name: `Plant 1-ExplanationTextShape`}).Stage(stage)

	__GridPathShape__00000000_ := (&models.GridPathShape{Name: `Plant 1-GridPathShape`}).Stage(stage)
	__GridPathShape__00000001_ := (&models.GridPathShape{Name: `Plant 1-RotatedGridPathShape`}).Stage(stage)

	__GrowthCurveBezierShape__00036116_ := (&models.GrowthCurveBezierShape{Name: `Plant 1-GrowthCurveBezierShapeGrid-0`}).Stage(stage)
	__GrowthCurveBezierShape__00036117_ := (&models.GrowthCurveBezierShape{Name: `Plant 1-GrowthCurveBezierShapeGrid-translated-0`}).Stage(stage)
	__GrowthCurveBezierShape__00036118_ := (&models.GrowthCurveBezierShape{Name: `Plant 1-GrowthCurveBezierShapeGrid-1`}).Stage(stage)
	__GrowthCurveBezierShape__00036119_ := (&models.GrowthCurveBezierShape{Name: `Plant 1-GrowthCurveBezierShapeGrid-translated-1`}).Stage(stage)
	__GrowthCurveBezierShape__00036120_ := (&models.GrowthCurveBezierShape{Name: `Plant 1-GrowthCurveBezierShapeGrid-2`}).Stage(stage)
	__GrowthCurveBezierShape__00036121_ := (&models.GrowthCurveBezierShape{Name: `Plant 1-GrowthCurveBezierShapeGrid-translated-2`}).Stage(stage)

	__GrowthCurveBezierShapeGrid__00000000_ := (&models.GrowthCurveBezierShapeGrid{Name: `Plant 1-GrowthCurveBezierShapeGrid`}).Stage(stage)

	__GrowthCurveRhombusGridShape__00000000_ := (&models.GrowthCurveRhombusGridShape{Name: `Plant 1-GrowthCurveRhombusGridShape`}).Stage(stage)

	__GrowthCurveRhombusShape__00015299_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-0`}).Stage(stage)
	__GrowthCurveRhombusShape__00015300_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-1`}).Stage(stage)
	__GrowthCurveRhombusShape__00015301_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-2`}).Stage(stage)
	__GrowthCurveRhombusShape__00015302_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-translated`}).Stage(stage)

	__GrowthVectorShape__00000000_ := (&models.GrowthVectorShape{Name: `Plant 1-GrowthVectorShape`}).Stage(stage)

	__InitialRhombusGridShape__00000000_ := (&models.InitialRhombusGridShape{Name: `Plant 1-InitialRhombusGridShape`}).Stage(stage)

	__InitialRhombusShape__00000803_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape--1-0`}).Stage(stage)
	__InitialRhombusShape__00000804_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape--1-1`}).Stage(stage)
	__InitialRhombusShape__00000805_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-0-0`}).Stage(stage)
	__InitialRhombusShape__00000806_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-0-1`}).Stage(stage)

	__Library__00000000_ := (&models.Library{Name: ``}).Stage(stage)

	__PerpendicularVector__00011094_ := (&models.PerpendicularVector{Name: `Plant 1-PerpendicularVectorGrid-0`}).Stage(stage)
	__PerpendicularVector__00011095_ := (&models.PerpendicularVector{Name: `Plant 1-PerpendicularVectorGrid-1`}).Stage(stage)
	__PerpendicularVector__00011096_ := (&models.PerpendicularVector{Name: `Plant 1-PerpendicularVectorGrid-2`}).Stage(stage)
	__PerpendicularVector__00011097_ := (&models.PerpendicularVector{Name: `Plant 1-PerpendicularVectorGrid-3`}).Stage(stage)

	__PerpendicularVectorGrid__00000000_ := (&models.PerpendicularVectorGrid{Name: `Plant 1-PerpendicularVectorGrid`}).Stage(stage)

	__PerpendicularVectorGridHalfway__00000000_ := (&models.PerpendicularVectorGridHalfway{Name: `Plant 1-PerpendicularVectorGridHalfway`}).Stage(stage)

	__PerpendicularVectorHalfway__00007195_ := (&models.PerpendicularVectorHalfway{Name: `Plant 1-PerpendicularVectorGridHalfway-0`}).Stage(stage)
	__PerpendicularVectorHalfway__00007196_ := (&models.PerpendicularVectorHalfway{Name: `Plant 1-PerpendicularVectorGridHalfway-1`}).Stage(stage)
	__PerpendicularVectorHalfway__00007197_ := (&models.PerpendicularVectorHalfway{Name: `Plant 1-PerpendicularVectorGridHalfway-2`}).Stage(stage)

	__Plant__00000000_ := (&models.Plant{Name: `Plant 1`}).Stage(stage)

	__PlantCircumferenceShape__00000000_ := (&models.PlantCircumferenceShape{Name: `Plant 1-RotatedPlantCircumferenceShape`}).Stage(stage)
	__PlantCircumferenceShape__00000001_ := (&models.PlantCircumferenceShape{Name: `Plant 1-PlantCircumferenceShape`}).Stage(stage)

	__PlantDiagram__00000001_ := (&models.PlantDiagram{Name: `Plant 1 - rotated`}).Stage(stage)

	__Rendered3DShape__00000001_ := (&models.Rendered3DShape{Name: `Plant 1 - rotated-Rendered3DShape`}).Stage(stage)

	__RhombusShape__00000000_ := (&models.RhombusShape{Name: `Plant 1-ReferenceRhombus`}).Stage(stage)
	__RhombusShape__00000003_ := (&models.RhombusShape{Name: `Plant 1-RotatedReferenceRhombus`}).Stage(stage)

	__RotatedRhombusGridShape__00000000_ := (&models.RotatedRhombusGridShape{Name: `Plant 1-RotatedRhombusGridShape`}).Stage(stage)

	__RotatedRhombusShape__00000803_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape--1-0`}).Stage(stage)
	__RotatedRhombusShape__00000804_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape--1-1`}).Stage(stage)
	__RotatedRhombusShape__00000805_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-0-0`}).Stage(stage)
	__RotatedRhombusShape__00000806_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-0-1`}).Stage(stage)

	__StackOfGrowthCurve__00000000_ := (&models.StackOfGrowthCurve{Name: `Plant 1-StackOfGrowthCurve`}).Stage(stage)

	__StartArcShape__00007200_ := (&models.StartArcShape{Name: `Plant 1-StartArcShapeGrid-0`}).Stage(stage)
	__StartArcShape__00007201_ := (&models.StartArcShape{Name: `Plant 1-StartArcShapeGrid-1`}).Stage(stage)
	__StartArcShape__00007202_ := (&models.StartArcShape{Name: `Plant 1-StartArcShapeGrid-2`}).Stage(stage)

	__StartArcShapeGrid__00000000_ := (&models.StartArcShapeGrid{Name: `Plant 1-StartArcShapeGrid`}).Stage(stage)

	__StartArcShapeV2__00003576_ := (&models.StartArcShapeV2{Name: `Plant 1-StartArcShapeV2Grid-0`}).Stage(stage)
	__StartArcShapeV2__00003577_ := (&models.StartArcShapeV2{Name: `Plant 1-StartArcShapeV2Grid-1`}).Stage(stage)
	__StartArcShapeV2__00003578_ := (&models.StartArcShapeV2{Name: `Plant 1-StartArcShapeV2Grid-2`}).Stage(stage)

	__StartArcShapeV2Grid__00000000_ := (&models.StartArcShapeV2Grid{Name: `Plant 1-StartArcShapeV2Grid`}).Stage(stage)

	__TopEndArcShapeV2__00001041_ := (&models.TopEndArcShapeV2{Name: `Plant 1-TopEndArcShapeV2Grid-0`}).Stage(stage)
	__TopEndArcShapeV2__00001042_ := (&models.TopEndArcShapeV2{Name: `Plant 1-TopEndArcShapeV2Grid-1`}).Stage(stage)
	__TopEndArcShapeV2__00001043_ := (&models.TopEndArcShapeV2{Name: `Plant 1-TopEndArcShapeV2Grid-2`}).Stage(stage)

	__TopEndArcShapeV2Grid__00000000_ := (&models.TopEndArcShapeV2Grid{Name: `Plant 1-TopEndArcShapeV2Grid`}).Stage(stage)

	__TopStartArcShapeV2__00001041_ := (&models.TopStartArcShapeV2{Name: `Plant 1-TopStartArcShapeV2Grid-0`}).Stage(stage)
	__TopStartArcShapeV2__00001042_ := (&models.TopStartArcShapeV2{Name: `Plant 1-TopStartArcShapeV2Grid-1`}).Stage(stage)
	__TopStartArcShapeV2__00001043_ := (&models.TopStartArcShapeV2{Name: `Plant 1-TopStartArcShapeV2Grid-2`}).Stage(stage)

	__TopStartArcShapeV2Grid__00000000_ := (&models.TopStartArcShapeV2Grid{Name: `Plant 1-TopStartArcShapeV2Grid`}).Stage(stage)

	// insertion point for initialization of values

	__ArcNormalVectorShape__00000966_.Name = `Plant 1-ArcNormalVectorShapeGrid-0`
	__ArcNormalVectorShape__00000966_.StartX = 96.477299
	__ArcNormalVectorShape__00000966_.StartY = 26.308379
	__ArcNormalVectorShape__00000966_.EndX = 46.556629
	__ArcNormalVectorShape__00000966_.EndY = 88.501301

	__ArcNormalVectorShape__00000967_.Name = `Plant 1-ArcNormalVectorShapeGrid-1`
	__ArcNormalVectorShape__00000967_.StartX = 277.992688
	__ArcNormalVectorShape__00000967_.StartY = 0.000000
	__ArcNormalVectorShape__00000967_.EndX = 343.516401
	__ArcNormalVectorShape__00000967_.EndY = 45.460707

	__ArcNormalVectorShape__00000968_.Name = `Plant 1-ArcNormalVectorShapeGrid-2`
	__ArcNormalVectorShape__00000968_.StartX = 459.508077
	__ArcNormalVectorShape__00000968_.StartY = -26.308379
	__ArcNormalVectorShape__00000968_.EndX = 409.587407
	__ArcNormalVectorShape__00000968_.EndY = 35.884543

	__ArcNormalVectorShapeGrid__00000000_.Name = `Plant 1-ArcNormalVectorShapeGrid`

	__AxesShape__00000000_.Name = `Plant 1-AxesShape`
	__AxesShape__00000000_.LengthX = 200.000000
	__AxesShape__00000000_.LengthY = 648.000000
	__AxesShape__00000000_.IsWithHiddenHandle = true

	__BaseVectorShape__00005434_.Name = `Plant 1-BaseVectorShapeGrid-0`
	__BaseVectorShape__00005434_.StartX = 0.000000
	__BaseVectorShape__00005434_.StartY = 0.000000
	__BaseVectorShape__00005434_.EndX = 192.954598
	__BaseVectorShape__00005434_.EndY = 52.616758

	__BaseVectorShape__00005435_.Name = `Plant 1-BaseVectorShapeGrid-1`
	__BaseVectorShape__00005435_.StartX = 192.954598
	__BaseVectorShape__00005435_.StartY = 52.616758
	__BaseVectorShape__00005435_.EndX = 363.030778
	__BaseVectorShape__00005435_.EndY = -52.616758

	__BaseVectorShape__00005436_.Name = `Plant 1-BaseVectorShapeGrid-2`
	__BaseVectorShape__00005436_.StartX = 363.030778
	__BaseVectorShape__00005436_.StartY = -52.616758
	__BaseVectorShape__00005436_.EndX = 555.985375
	__BaseVectorShape__00005436_.EndY = 0.000000

	__BaseVectorShapeGrid__00000000_.Name = `Plant 1-BaseVectorShapeGrid`

	__BottomEndArcShapeV2__00000566_.Name = `Plant 1-BottomEndArcShapeV2Grid-0`
	__BottomEndArcShapeV2__00000566_.StartX = 192.093966
	__BottomEndArcShapeV2__00000566_.StartY = 46.678803
	__BottomEndArcShapeV2__00000566_.EndX = 100.233095
	__BottomEndArcShapeV2__00000566_.EndY = 21.629277
	__BottomEndArcShapeV2__00000566_.XAxisRotation = 0.000000
	__BottomEndArcShapeV2__00000566_.LargeArcFlag = false
	__BottomEndArcShapeV2__00000566_.SweepFlag = false
	__BottomEndArcShapeV2__00000566_.RadiusX = 119.392142
	__BottomEndArcShapeV2__00000566_.RadiusY = 119.392142

	__BottomEndArcShapeV2__00000567_.Name = `Plant 1-BottomEndArcShapeV2Grid-1`
	__BottomEndArcShapeV2__00000567_.StartX = 362.170146
	__BottomEndArcShapeV2__00000567_.StartY = -58.554713
	__BottomEndArcShapeV2__00000567_.EndX = 273.062992
	__BottomEndArcShapeV2__00000567_.EndY = -3.420249
	__BottomEndArcShapeV2__00000567_.XAxisRotation = 0.000000
	__BottomEndArcShapeV2__00000567_.LargeArcFlag = false
	__BottomEndArcShapeV2__00000567_.SweepFlag = true
	__BottomEndArcShapeV2__00000567_.RadiusX = 131.392142
	__BottomEndArcShapeV2__00000567_.RadiusY = 131.392142

	__BottomEndArcShapeV2__00000568_.Name = `Plant 1-BottomEndArcShapeV2Grid-2`
	__BottomEndArcShapeV2__00000568_.StartX = 555.124743
	__BottomEndArcShapeV2__00000568_.StartY = -5.937955
	__BottomEndArcShapeV2__00000568_.EndX = 463.263872
	__BottomEndArcShapeV2__00000568_.EndY = -30.987481
	__BottomEndArcShapeV2__00000568_.XAxisRotation = 0.000000
	__BottomEndArcShapeV2__00000568_.LargeArcFlag = false
	__BottomEndArcShapeV2__00000568_.SweepFlag = false
	__BottomEndArcShapeV2__00000568_.RadiusX = 119.392142
	__BottomEndArcShapeV2__00000568_.RadiusY = 119.392142

	__BottomEndArcShapeV2Grid__00000000_.Name = `Plant 1-BottomEndArcShapeV2Grid`

	__BottomStartArcShapeV2__00000566_.Name = `Plant 1-BottomStartArcShapeV2Grid-0`
	__BottomStartArcShapeV2__00000566_.StartX = -0.860632
	__BottomStartArcShapeV2__00000566_.StartY = -5.937955
	__BottomStartArcShapeV2__00000566_.EndX = 100.233095
	__BottomStartArcShapeV2__00000566_.EndY = 21.629277
	__BottomStartArcShapeV2__00000566_.XAxisRotation = 0.000000
	__BottomStartArcShapeV2__00000566_.LargeArcFlag = false
	__BottomStartArcShapeV2__00000566_.SweepFlag = false
	__BottomStartArcShapeV2__00000566_.RadiusX = 131.392142
	__BottomStartArcShapeV2__00000566_.RadiusY = 131.392142

	__BottomStartArcShapeV2__00000567_.Name = `Plant 1-BottomStartArcShapeV2Grid-1`
	__BottomStartArcShapeV2__00000567_.StartX = 192.093966
	__BottomStartArcShapeV2__00000567_.StartY = 46.678803
	__BottomStartArcShapeV2__00000567_.EndX = 273.062992
	__BottomStartArcShapeV2__00000567_.EndY = -3.420249
	__BottomStartArcShapeV2__00000567_.XAxisRotation = 0.000000
	__BottomStartArcShapeV2__00000567_.LargeArcFlag = false
	__BottomStartArcShapeV2__00000567_.SweepFlag = true
	__BottomStartArcShapeV2__00000567_.RadiusX = 119.392142
	__BottomStartArcShapeV2__00000567_.RadiusY = 119.392142

	__BottomStartArcShapeV2__00000568_.Name = `Plant 1-BottomStartArcShapeV2Grid-2`
	__BottomStartArcShapeV2__00000568_.StartX = 362.170146
	__BottomStartArcShapeV2__00000568_.StartY = -58.554713
	__BottomStartArcShapeV2__00000568_.EndX = 463.263872
	__BottomStartArcShapeV2__00000568_.EndY = -30.987481
	__BottomStartArcShapeV2__00000568_.XAxisRotation = 0.000000
	__BottomStartArcShapeV2__00000568_.LargeArcFlag = false
	__BottomStartArcShapeV2__00000568_.SweepFlag = false
	__BottomStartArcShapeV2__00000568_.RadiusX = 131.392142
	__BottomStartArcShapeV2__00000568_.RadiusY = 131.392142

	__BottomStartArcShapeV2Grid__00000000_.Name = `Plant 1-BottomStartArcShapeV2Grid`

	__EndArcShape__00006270_.Name = `Plant 1-EndArcShapeGrid-0`
	__EndArcShape__00006270_.StartX = 192.954598
	__EndArcShape__00006270_.StartY = 52.616758
	__EndArcShape__00006270_.EndX = 89.042714
	__EndArcShape__00006270_.EndY = -24.986747
	__EndArcShape__00006270_.XAxisRotation = 0.000000
	__EndArcShape__00006270_.LargeArcFlag = false
	__EndArcShape__00006270_.SweepFlag = false
	__EndArcShape__00006270_.RadiusX = 91.706007
	__EndArcShape__00006270_.RadiusY = 91.706007

	__EndArcShape__00006271_.Name = `Plant 1-EndArcShapeGrid-1`
	__EndArcShape__00006271_.StartX = 363.030778
	__EndArcShape__00006271_.StartY = -52.616758
	__EndArcShape__00006271_.EndX = 285.427273
	__EndArcShape__00006271_.EndY = 51.295126
	__EndArcShape__00006271_.XAxisRotation = 0.000000
	__EndArcShape__00006271_.LargeArcFlag = false
	__EndArcShape__00006271_.SweepFlag = true
	__EndArcShape__00006271_.RadiusX = 91.706007
	__EndArcShape__00006271_.RadiusY = 91.706007

	__EndArcShape__00006272_.Name = `Plant 1-EndArcShapeGrid-2`
	__EndArcShape__00006272_.StartX = 555.985375
	__EndArcShape__00006272_.StartY = 0.000000
	__EndArcShape__00006272_.EndX = 452.073491
	__EndArcShape__00006272_.EndY = -77.603505
	__EndArcShape__00006272_.XAxisRotation = 0.000000
	__EndArcShape__00006272_.LargeArcFlag = false
	__EndArcShape__00006272_.SweepFlag = false
	__EndArcShape__00006272_.RadiusX = 91.706007
	__EndArcShape__00006272_.RadiusY = 91.706007

	__EndArcShapeGrid__00000000_.Name = `Plant 1-EndArcShapeGrid`

	__EndArcShapeV2__00003196_.Name = `Plant 1-EndArcShapeV2Grid-0`
	__EndArcShapeV2__00003196_.StartX = 192.954598
	__EndArcShapeV2__00003196_.StartY = 52.616758
	__EndArcShapeV2__00003196_.EndX = 96.477299
	__EndArcShapeV2__00003196_.EndY = 26.308379
	__EndArcShapeV2__00003196_.XAxisRotation = 0.000000
	__EndArcShapeV2__00003196_.LargeArcFlag = false
	__EndArcShapeV2__00003196_.SweepFlag = false
	__EndArcShapeV2__00003196_.RadiusX = 125.392142
	__EndArcShapeV2__00003196_.RadiusY = 125.392142

	__EndArcShapeV2__00003197_.Name = `Plant 1-EndArcShapeV2Grid-1`
	__EndArcShapeV2__00003197_.StartX = 363.030778
	__EndArcShapeV2__00003197_.StartY = -52.616758
	__EndArcShapeV2__00003197_.EndX = 277.992688
	__EndArcShapeV2__00003197_.EndY = 0.000000
	__EndArcShapeV2__00003197_.XAxisRotation = 0.000000
	__EndArcShapeV2__00003197_.LargeArcFlag = false
	__EndArcShapeV2__00003197_.SweepFlag = true
	__EndArcShapeV2__00003197_.RadiusX = 125.392142
	__EndArcShapeV2__00003197_.RadiusY = 125.392142

	__EndArcShapeV2__00003198_.Name = `Plant 1-EndArcShapeV2Grid-2`
	__EndArcShapeV2__00003198_.StartX = 555.985375
	__EndArcShapeV2__00003198_.StartY = 0.000000
	__EndArcShapeV2__00003198_.EndX = 459.508077
	__EndArcShapeV2__00003198_.EndY = -26.308379
	__EndArcShapeV2__00003198_.XAxisRotation = 0.000000
	__EndArcShapeV2__00003198_.LargeArcFlag = false
	__EndArcShapeV2__00003198_.SweepFlag = false
	__EndArcShapeV2__00003198_.RadiusX = 125.392142
	__EndArcShapeV2__00003198_.RadiusY = 125.392142

	__EndArcShapeV2Grid__00000000_.Name = `Plant 1-EndArcShapeV2Grid`

	__ExplanationTextShape__00000000_.Name = `Plant 1-ExplanationTextShape`

	__GridPathShape__00000000_.Name = `Plant 1-GridPathShape`

	__GridPathShape__00000001_.Name = `Plant 1-RotatedGridPathShape`

	__GrowthCurveBezierShape__00036116_.Name = `Plant 1-GrowthCurveBezierShapeGrid-0`
	__GrowthCurveBezierShape__00036116_.StartX = 0.000000
	__GrowthCurveBezierShape__00036116_.StartY = 0.000000
	__GrowthCurveBezierShape__00036116_.ControlPointStartX = 65.317508
	__GrowthCurveBezierShape__00036116_.ControlPointStartY = -9.466954
	__GrowthCurveBezierShape__00036116_.EndX = 192.954598
	__GrowthCurveBezierShape__00036116_.EndY = 52.616758
	__GrowthCurveBezierShape__00036116_.ControlPointEndX = 127.637090
	__GrowthCurveBezierShape__00036116_.ControlPointEndY = 62.083712

	__GrowthCurveBezierShape__00036117_.Name = `Plant 1-GrowthCurveBezierShapeGrid-translated-0`
	__GrowthCurveBezierShape__00036117_.StartX = 555.985375
	__GrowthCurveBezierShape__00036117_.StartY = 0.000000
	__GrowthCurveBezierShape__00036117_.ControlPointStartX = 621.302883
	__GrowthCurveBezierShape__00036117_.ControlPointStartY = -9.466954
	__GrowthCurveBezierShape__00036117_.EndX = 748.939973
	__GrowthCurveBezierShape__00036117_.EndY = 52.616758
	__GrowthCurveBezierShape__00036117_.ControlPointEndX = 683.622465
	__GrowthCurveBezierShape__00036117_.ControlPointEndY = 62.083712

	__GrowthCurveBezierShape__00036118_.Name = `Plant 1-GrowthCurveBezierShapeGrid-1`
	__GrowthCurveBezierShape__00036118_.StartX = 192.954598
	__GrowthCurveBezierShape__00036118_.StartY = 52.616758
	__GrowthCurveBezierShape__00036118_.ControlPointStartX = 258.272105
	__GrowthCurveBezierShape__00036118_.ControlPointStartY = 43.149805
	__GrowthCurveBezierShape__00036118_.EndX = 363.030778
	__GrowthCurveBezierShape__00036118_.EndY = -52.616758
	__GrowthCurveBezierShape__00036118_.ControlPointEndX = 297.713270
	__GrowthCurveBezierShape__00036118_.ControlPointEndY = -43.149805

	__GrowthCurveBezierShape__00036119_.Name = `Plant 1-GrowthCurveBezierShapeGrid-translated-1`
	__GrowthCurveBezierShape__00036119_.StartX = 748.939973
	__GrowthCurveBezierShape__00036119_.StartY = 52.616758
	__GrowthCurveBezierShape__00036119_.ControlPointStartX = 814.257481
	__GrowthCurveBezierShape__00036119_.ControlPointStartY = 43.149805
	__GrowthCurveBezierShape__00036119_.EndX = 919.016153
	__GrowthCurveBezierShape__00036119_.EndY = -52.616758
	__GrowthCurveBezierShape__00036119_.ControlPointEndX = 853.698646
	__GrowthCurveBezierShape__00036119_.ControlPointEndY = -43.149805

	__GrowthCurveBezierShape__00036120_.Name = `Plant 1-GrowthCurveBezierShapeGrid-2`
	__GrowthCurveBezierShape__00036120_.StartX = 363.030778
	__GrowthCurveBezierShape__00036120_.StartY = -52.616758
	__GrowthCurveBezierShape__00036120_.ControlPointStartX = 428.348285
	__GrowthCurveBezierShape__00036120_.ControlPointStartY = -62.083712
	__GrowthCurveBezierShape__00036120_.EndX = 555.985375
	__GrowthCurveBezierShape__00036120_.EndY = 0.000000
	__GrowthCurveBezierShape__00036120_.ControlPointEndX = 490.667868
	__GrowthCurveBezierShape__00036120_.ControlPointEndY = 9.466954

	__GrowthCurveBezierShape__00036121_.Name = `Plant 1-GrowthCurveBezierShapeGrid-translated-2`
	__GrowthCurveBezierShape__00036121_.StartX = 919.016153
	__GrowthCurveBezierShape__00036121_.StartY = -52.616758
	__GrowthCurveBezierShape__00036121_.ControlPointStartX = 984.333661
	__GrowthCurveBezierShape__00036121_.ControlPointStartY = -62.083712
	__GrowthCurveBezierShape__00036121_.EndX = 1111.970751
	__GrowthCurveBezierShape__00036121_.EndY = 0.000000
	__GrowthCurveBezierShape__00036121_.ControlPointEndX = 1046.653243
	__GrowthCurveBezierShape__00036121_.ControlPointEndY = 9.466954

	__GrowthCurveBezierShapeGrid__00000000_.Name = `Plant 1-GrowthCurveBezierShapeGrid`

	__GrowthCurveRhombusGridShape__00000000_.Name = `Plant 1-GrowthCurveRhombusGridShape`

	__GrowthCurveRhombusShape__00015299_.Name = `Plant 1-GrowthCurveRhombusGridShape-0`
	__GrowthCurveRhombusShape__00015299_.X = 11.439209
	__GrowthCurveRhombusShape__00015299_.Y = 78.925137

	__GrowthCurveRhombusShape__00015300_.Name = `Plant 1-GrowthCurveRhombusGridShape-1`
	__GrowthCurveRhombusShape__00015300_.X = 204.393806
	__GrowthCurveRhombusShape__00015300_.Y = 131.541896

	__GrowthCurveRhombusShape__00015301_.Name = `Plant 1-GrowthCurveRhombusGridShape-2`
	__GrowthCurveRhombusShape__00015301_.X = 374.469987
	__GrowthCurveRhombusShape__00015301_.Y = 26.308379

	__GrowthCurveRhombusShape__00015302_.Name = `Plant 1-GrowthCurveRhombusGridShape-translated`
	__GrowthCurveRhombusShape__00015302_.X = 567.424584
	__GrowthCurveRhombusShape__00015302_.Y = 78.925137

	__GrowthVectorShape__00000000_.Name = `Plant 1-GrowthVectorShape`
	__GrowthVectorShape__00000000_.X = 192.954597
	__GrowthVectorShape__00000000_.Y = 52.616759

	__InitialRhombusGridShape__00000000_.Name = `Plant 1-InitialRhombusGridShape`

	__InitialRhombusShape__00000803_.Name = `Plant 1-InitialRhombusGridShape--1-0`
	__InitialRhombusShape__00000803_.X = -79.749814
	__InitialRhombusShape__00000803_.Y = 0.000000

	__InitialRhombusShape__00000804_.Name = `Plant 1-InitialRhombusGridShape--1-1`
	__InitialRhombusShape__00000804_.X = -159.499628
	__InitialRhombusShape__00000804_.Y = 183.412015

	__InitialRhombusShape__00000805_.Name = `Plant 1-InitialRhombusGridShape-0-0`
	__InitialRhombusShape__00000805_.X = 0.000000
	__InitialRhombusShape__00000805_.Y = 183.412015

	__InitialRhombusShape__00000806_.Name = `Plant 1-InitialRhombusGridShape-0-1`
	__InitialRhombusShape__00000806_.X = -79.749814
	__InitialRhombusShape__00000806_.Y = 366.824030

	__Library__00000000_.Name = ``
	__Library__00000000_.NbPixPerCharacter = 8.000000
	__Library__00000000_.LogoSVGFile = ``
	__Library__00000000_.ComputedPrefix = ``
	__Library__00000000_.IsExpanded = true
	__Library__00000000_.IsRootLibrary = true

	__PerpendicularVector__00011094_.Name = `Plant 1-PerpendicularVectorGrid-0`
	__PerpendicularVector__00011094_.StartX = 0.000000
	__PerpendicularVector__00011094_.StartY = -0.000000
	__PerpendicularVector__00011094_.EndX = 11.439209
	__PerpendicularVector__00011094_.EndY = 78.925137

	__PerpendicularVector__00011095_.Name = `Plant 1-PerpendicularVectorGrid-1`
	__PerpendicularVector__00011095_.StartX = 192.954597
	__PerpendicularVector__00011095_.StartY = 52.616759
	__PerpendicularVector__00011095_.EndX = 204.393806
	__PerpendicularVector__00011095_.EndY = 131.541896

	__PerpendicularVector__00011096_.Name = `Plant 1-PerpendicularVectorGrid-2`
	__PerpendicularVector__00011096_.StartX = 363.030778
	__PerpendicularVector__00011096_.StartY = -52.616758
	__PerpendicularVector__00011096_.EndX = 374.469987
	__PerpendicularVector__00011096_.EndY = 26.308379

	__PerpendicularVector__00011097_.Name = `Plant 1-PerpendicularVectorGrid-3`
	__PerpendicularVector__00011097_.StartX = 555.985375
	__PerpendicularVector__00011097_.StartY = -0.000000
	__PerpendicularVector__00011097_.EndX = 567.424584
	__PerpendicularVector__00011097_.EndY = 78.925137

	__PerpendicularVectorGrid__00000000_.Name = `Plant 1-PerpendicularVectorGrid`

	__PerpendicularVectorGridHalfway__00000000_.Name = `Plant 1-PerpendicularVectorGridHalfway`

	__PerpendicularVectorHalfway__00007195_.Name = `Plant 1-PerpendicularVectorGridHalfway-0`
	__PerpendicularVectorHalfway__00007195_.StartX = 96.477299
	__PerpendicularVectorHalfway__00007195_.StartY = 26.308379
	__PerpendicularVectorHalfway__00007195_.EndX = 107.916508
	__PerpendicularVectorHalfway__00007195_.EndY = 105.233516

	__PerpendicularVectorHalfway__00007196_.Name = `Plant 1-PerpendicularVectorGridHalfway-1`
	__PerpendicularVectorHalfway__00007196_.StartX = 277.992688
	__PerpendicularVectorHalfway__00007196_.StartY = 0.000000
	__PerpendicularVectorHalfway__00007196_.EndX = 289.431896
	__PerpendicularVectorHalfway__00007196_.EndY = 78.925137

	__PerpendicularVectorHalfway__00007197_.Name = `Plant 1-PerpendicularVectorGridHalfway-2`
	__PerpendicularVectorHalfway__00007197_.StartX = 459.508077
	__PerpendicularVectorHalfway__00007197_.StartY = -26.308379
	__PerpendicularVectorHalfway__00007197_.EndX = 470.947285
	__PerpendicularVectorHalfway__00007197_.EndY = 52.616758

	__Plant__00000000_.Name = `Plant 1`
	__Plant__00000000_.N = 1
	__Plant__00000000_.M = 2
	__Plant__00000000_.StackHeight = 0
	__Plant__00000000_.RhombusInsideAngle = 133.000000
	__Plant__00000000_.Thickness = 6.000000
	__Plant__00000000_.RhombusSideLength = 200.000000
	__Plant__00000000_.ComputedPrefix = ``
	__Plant__00000000_.IsExpanded = true
	__Plant__00000000_.IsSelected = true
	__Plant__00000000_.IsPlantDiagramsNodeExpanded = true

	__PlantCircumferenceShape__00000000_.Name = `Plant 1-RotatedPlantCircumferenceShape`
	__PlantCircumferenceShape__00000000_.AngleDegree = 0.000000
	__PlantCircumferenceShape__00000000_.Length = 555.985375

	__PlantCircumferenceShape__00000001_.Name = `Plant 1-PlantCircumferenceShape`
	__PlantCircumferenceShape__00000001_.AngleDegree = 98.246878
	__PlantCircumferenceShape__00000001_.Length = 555.985375

	__PlantDiagram__00000001_.Name = `Plant 1 - rotated`
	__PlantDiagram__00000001_.OriginX = 216.709677
	__PlantDiagram__00000001_.OriginY = 395.838710
	__PlantDiagram__00000001_.IsHiddenAxesShape = false
	__PlantDiagram__00000001_.IsHiddenReferenceRhombus = true
	__PlantDiagram__00000001_.IsHiddenPlantCircumferenceShape = true
	__PlantDiagram__00000001_.IsHiddenGridPathShape = true
	__PlantDiagram__00000001_.IsHiddenRhombusGridShape = true
	__PlantDiagram__00000001_.IsHiddenExplanationTextShape = true
	__PlantDiagram__00000001_.IsHiddenRotatedReferenceRhombus = true
	__PlantDiagram__00000001_.IsHiddenRotatedPlantCircumferenceShape = true
	__PlantDiagram__00000001_.IsHiddenRotatedGridPathShape = true
	__PlantDiagram__00000001_.IsHiddenRotatedRhombusGridShape = true
	__PlantDiagram__00000001_.IsHiddenGrowthPathRhombusGridShape = true
	__PlantDiagram__00000001_.IsHiddenGrowthVectorShape = true
	__PlantDiagram__00000001_.IsHiddenPerpendicularVectorGrid = true
	__PlantDiagram__00000001_.IsHiddenPerpendicularVectorGridHalfway = true
	__PlantDiagram__00000001_.IsHiddenBaseVectorShapeGrid = true
	__PlantDiagram__00000001_.IsHiddenArcNormalVectorShapeGrid = true
	__PlantDiagram__00000001_.IsHiddenStartArcShapeGrid = true
	__PlantDiagram__00000001_.IsHiddenStartArcShapeV2Grid = false
	__PlantDiagram__00000001_.IsHiddenTopStartArcShapeV2Grid = false
	__PlantDiagram__00000001_.IsHiddenEndArcShapeGrid = true
	__PlantDiagram__00000001_.IsHiddenEndArcShapeV2Grid = false
	__PlantDiagram__00000001_.IsHiddenTopEndArcShapeV2Grid = false
	__PlantDiagram__00000001_.IsHiddenBottomStartArcShapeV2Grid = true
	__PlantDiagram__00000001_.IsHiddenBottomEndArcShapeV2Grid = true
	__PlantDiagram__00000001_.IsHiddenGrowthCurveBezierShapeGrid = true
	__PlantDiagram__00000001_.IsHiddenStackOfGrowthCurve = true
	__PlantDiagram__00000001_.IsChecked = true
	__PlantDiagram__00000001_.ComputedPrefix = ``
	__PlantDiagram__00000001_.IsExpanded = true

	__Rendered3DShape__00000001_.Name = `Plant 1 - rotated-Rendered3DShape`
	__Rendered3DShape__00000001_.ViewX = 500.000000
	__Rendered3DShape__00000001_.ViewY = 145.000000
	__Rendered3DShape__00000001_.ViewZ = 36.000000
	__Rendered3DShape__00000001_.TargetX = 0.000000
	__Rendered3DShape__00000001_.TargetY = 200.000000
	__Rendered3DShape__00000001_.TargetZ = 0.000000
	__Rendered3DShape__00000001_.Fov = 48.000000

	__RhombusShape__00000000_.Name = `Plant 1-ReferenceRhombus`
	__RhombusShape__00000000_.X = 0.000000
	__RhombusShape__00000000_.Y = 0.000000

	__RhombusShape__00000003_.Name = `Plant 1-RotatedReferenceRhombus`
	__RhombusShape__00000003_.X = 0.000000
	__RhombusShape__00000003_.Y = 0.000000

	__RotatedRhombusGridShape__00000000_.Name = `Plant 1-RotatedRhombusGridShape`

	__RotatedRhombusShape__00000803_.Name = `Plant 1-RotatedRhombusGridShape--1-0`
	__RotatedRhombusShape__00000803_.X = 11.439209
	__RotatedRhombusShape__00000803_.Y = 78.925137

	__RotatedRhombusShape__00000804_.Name = `Plant 1-RotatedRhombusGridShape--1-1`
	__RotatedRhombusShape__00000804_.X = 204.393806
	__RotatedRhombusShape__00000804_.Y = 131.541896

	__RotatedRhombusShape__00000805_.Name = `Plant 1-RotatedRhombusGridShape-0-0`
	__RotatedRhombusShape__00000805_.X = 181.515389
	__RotatedRhombusShape__00000805_.Y = -26.308379

	__RotatedRhombusShape__00000806_.Name = `Plant 1-RotatedRhombusGridShape-0-1`
	__RotatedRhombusShape__00000806_.X = 374.469987
	__RotatedRhombusShape__00000806_.Y = 26.308379

	__StackOfGrowthCurve__00000000_.Name = `Plant 1-StackOfGrowthCurve`

	__StartArcShape__00007200_.Name = `Plant 1-StartArcShapeGrid-0`
	__StartArcShape__00007200_.StartX = 0.000000
	__StartArcShape__00007200_.StartY = 0.000000
	__StartArcShape__00007200_.EndX = 103.911884
	__StartArcShape__00007200_.EndY = 77.603505
	__StartArcShape__00007200_.XAxisRotation = 0.000000
	__StartArcShape__00007200_.LargeArcFlag = false
	__StartArcShape__00007200_.SweepFlag = false
	__StartArcShape__00007200_.RadiusX = 91.706007
	__StartArcShape__00007200_.RadiusY = 91.706007

	__StartArcShape__00007201_.Name = `Plant 1-StartArcShapeGrid-1`
	__StartArcShape__00007201_.StartX = 192.954598
	__StartArcShape__00007201_.StartY = 52.616758
	__StartArcShape__00007201_.EndX = 270.558103
	__StartArcShape__00007201_.EndY = -51.295126
	__StartArcShape__00007201_.XAxisRotation = 0.000000
	__StartArcShape__00007201_.LargeArcFlag = false
	__StartArcShape__00007201_.SweepFlag = true
	__StartArcShape__00007201_.RadiusX = 91.706007
	__StartArcShape__00007201_.RadiusY = 91.706007

	__StartArcShape__00007202_.Name = `Plant 1-StartArcShapeGrid-2`
	__StartArcShape__00007202_.StartX = 363.030778
	__StartArcShape__00007202_.StartY = -52.616758
	__StartArcShape__00007202_.EndX = 466.942662
	__StartArcShape__00007202_.EndY = 24.986747
	__StartArcShape__00007202_.XAxisRotation = 0.000000
	__StartArcShape__00007202_.LargeArcFlag = false
	__StartArcShape__00007202_.SweepFlag = false
	__StartArcShape__00007202_.RadiusX = 91.706007
	__StartArcShape__00007202_.RadiusY = 91.706007

	__StartArcShapeGrid__00000000_.Name = `Plant 1-StartArcShapeGrid`

	__StartArcShapeV2__00003576_.Name = `Plant 1-StartArcShapeV2Grid-0`
	__StartArcShapeV2__00003576_.StartX = 0.000000
	__StartArcShapeV2__00003576_.StartY = 0.000000
	__StartArcShapeV2__00003576_.EndX = 96.477299
	__StartArcShapeV2__00003576_.EndY = 26.308379
	__StartArcShapeV2__00003576_.XAxisRotation = 0.000000
	__StartArcShapeV2__00003576_.LargeArcFlag = false
	__StartArcShapeV2__00003576_.SweepFlag = false
	__StartArcShapeV2__00003576_.RadiusX = 125.392142
	__StartArcShapeV2__00003576_.RadiusY = 125.392142

	__StartArcShapeV2__00003577_.Name = `Plant 1-StartArcShapeV2Grid-1`
	__StartArcShapeV2__00003577_.StartX = 192.954598
	__StartArcShapeV2__00003577_.StartY = 52.616758
	__StartArcShapeV2__00003577_.EndX = 277.992688
	__StartArcShapeV2__00003577_.EndY = 0.000000
	__StartArcShapeV2__00003577_.XAxisRotation = 0.000000
	__StartArcShapeV2__00003577_.LargeArcFlag = false
	__StartArcShapeV2__00003577_.SweepFlag = true
	__StartArcShapeV2__00003577_.RadiusX = 125.392142
	__StartArcShapeV2__00003577_.RadiusY = 125.392142

	__StartArcShapeV2__00003578_.Name = `Plant 1-StartArcShapeV2Grid-2`
	__StartArcShapeV2__00003578_.StartX = 363.030778
	__StartArcShapeV2__00003578_.StartY = -52.616758
	__StartArcShapeV2__00003578_.EndX = 459.508077
	__StartArcShapeV2__00003578_.EndY = -26.308379
	__StartArcShapeV2__00003578_.XAxisRotation = 0.000000
	__StartArcShapeV2__00003578_.LargeArcFlag = false
	__StartArcShapeV2__00003578_.SweepFlag = false
	__StartArcShapeV2__00003578_.RadiusX = 125.392142
	__StartArcShapeV2__00003578_.RadiusY = 125.392142

	__StartArcShapeV2Grid__00000000_.Name = `Plant 1-StartArcShapeV2Grid`

	__TopEndArcShapeV2__00001041_.Name = `Plant 1-TopEndArcShapeV2Grid-0`
	__TopEndArcShapeV2__00001041_.StartX = 193.815230
	__TopEndArcShapeV2__00001041_.StartY = 58.554713
	__TopEndArcShapeV2__00001041_.EndX = 92.721503
	__TopEndArcShapeV2__00001041_.EndY = 30.987481
	__TopEndArcShapeV2__00001041_.XAxisRotation = 0.000000
	__TopEndArcShapeV2__00001041_.LargeArcFlag = false
	__TopEndArcShapeV2__00001041_.SweepFlag = false
	__TopEndArcShapeV2__00001041_.RadiusX = 131.392142
	__TopEndArcShapeV2__00001041_.RadiusY = 131.392142

	__TopEndArcShapeV2__00001042_.Name = `Plant 1-TopEndArcShapeV2Grid-1`
	__TopEndArcShapeV2__00001042_.StartX = 363.891410
	__TopEndArcShapeV2__00001042_.StartY = -46.678803
	__TopEndArcShapeV2__00001042_.EndX = 282.922383
	__TopEndArcShapeV2__00001042_.EndY = 3.420249
	__TopEndArcShapeV2__00001042_.XAxisRotation = 0.000000
	__TopEndArcShapeV2__00001042_.LargeArcFlag = false
	__TopEndArcShapeV2__00001042_.SweepFlag = true
	__TopEndArcShapeV2__00001042_.RadiusX = 119.392142
	__TopEndArcShapeV2__00001042_.RadiusY = 119.392142

	__TopEndArcShapeV2__00001043_.Name = `Plant 1-TopEndArcShapeV2Grid-2`
	__TopEndArcShapeV2__00001043_.StartX = 556.846007
	__TopEndArcShapeV2__00001043_.StartY = 5.937955
	__TopEndArcShapeV2__00001043_.EndX = 455.752281
	__TopEndArcShapeV2__00001043_.EndY = -21.629277
	__TopEndArcShapeV2__00001043_.XAxisRotation = 0.000000
	__TopEndArcShapeV2__00001043_.LargeArcFlag = false
	__TopEndArcShapeV2__00001043_.SweepFlag = false
	__TopEndArcShapeV2__00001043_.RadiusX = 131.392142
	__TopEndArcShapeV2__00001043_.RadiusY = 131.392142

	__TopEndArcShapeV2Grid__00000000_.Name = `Plant 1-TopEndArcShapeV2Grid`

	__TopStartArcShapeV2__00001041_.Name = `Plant 1-TopStartArcShapeV2Grid-0`
	__TopStartArcShapeV2__00001041_.StartX = 0.860632
	__TopStartArcShapeV2__00001041_.StartY = 5.937955
	__TopStartArcShapeV2__00001041_.EndX = 92.721503
	__TopStartArcShapeV2__00001041_.EndY = 30.987481
	__TopStartArcShapeV2__00001041_.XAxisRotation = 0.000000
	__TopStartArcShapeV2__00001041_.LargeArcFlag = false
	__TopStartArcShapeV2__00001041_.SweepFlag = false
	__TopStartArcShapeV2__00001041_.RadiusX = 119.392142
	__TopStartArcShapeV2__00001041_.RadiusY = 119.392142

	__TopStartArcShapeV2__00001042_.Name = `Plant 1-TopStartArcShapeV2Grid-1`
	__TopStartArcShapeV2__00001042_.StartX = 193.815230
	__TopStartArcShapeV2__00001042_.StartY = 58.554713
	__TopStartArcShapeV2__00001042_.EndX = 282.922383
	__TopStartArcShapeV2__00001042_.EndY = 3.420249
	__TopStartArcShapeV2__00001042_.XAxisRotation = 0.000000
	__TopStartArcShapeV2__00001042_.LargeArcFlag = false
	__TopStartArcShapeV2__00001042_.SweepFlag = true
	__TopStartArcShapeV2__00001042_.RadiusX = 131.392142
	__TopStartArcShapeV2__00001042_.RadiusY = 131.392142

	__TopStartArcShapeV2__00001043_.Name = `Plant 1-TopStartArcShapeV2Grid-2`
	__TopStartArcShapeV2__00001043_.StartX = 363.891410
	__TopStartArcShapeV2__00001043_.StartY = -46.678803
	__TopStartArcShapeV2__00001043_.EndX = 455.752281
	__TopStartArcShapeV2__00001043_.EndY = -21.629277
	__TopStartArcShapeV2__00001043_.XAxisRotation = 0.000000
	__TopStartArcShapeV2__00001043_.LargeArcFlag = false
	__TopStartArcShapeV2__00001043_.SweepFlag = false
	__TopStartArcShapeV2__00001043_.RadiusX = 119.392142
	__TopStartArcShapeV2__00001043_.RadiusY = 119.392142

	__TopStartArcShapeV2Grid__00000000_.Name = `Plant 1-TopStartArcShapeV2Grid`

	// insertion point for setup of pointers
	__ArcNormalVectorShapeGrid__00000000_.ArcNormalVectorShapes = append(__ArcNormalVectorShapeGrid__00000000_.ArcNormalVectorShapes, __ArcNormalVectorShape__00000966_)
	__ArcNormalVectorShapeGrid__00000000_.ArcNormalVectorShapes = append(__ArcNormalVectorShapeGrid__00000000_.ArcNormalVectorShapes, __ArcNormalVectorShape__00000967_)
	__ArcNormalVectorShapeGrid__00000000_.ArcNormalVectorShapes = append(__ArcNormalVectorShapeGrid__00000000_.ArcNormalVectorShapes, __ArcNormalVectorShape__00000968_)
	__BaseVectorShapeGrid__00000000_.BaseVectorShapes = append(__BaseVectorShapeGrid__00000000_.BaseVectorShapes, __BaseVectorShape__00005434_)
	__BaseVectorShapeGrid__00000000_.BaseVectorShapes = append(__BaseVectorShapeGrid__00000000_.BaseVectorShapes, __BaseVectorShape__00005435_)
	__BaseVectorShapeGrid__00000000_.BaseVectorShapes = append(__BaseVectorShapeGrid__00000000_.BaseVectorShapes, __BaseVectorShape__00005436_)
	__BottomEndArcShapeV2Grid__00000000_.BottomEndArcShapesV2 = append(__BottomEndArcShapeV2Grid__00000000_.BottomEndArcShapesV2, __BottomEndArcShapeV2__00000566_)
	__BottomEndArcShapeV2Grid__00000000_.BottomEndArcShapesV2 = append(__BottomEndArcShapeV2Grid__00000000_.BottomEndArcShapesV2, __BottomEndArcShapeV2__00000567_)
	__BottomEndArcShapeV2Grid__00000000_.BottomEndArcShapesV2 = append(__BottomEndArcShapeV2Grid__00000000_.BottomEndArcShapesV2, __BottomEndArcShapeV2__00000568_)
	__BottomStartArcShapeV2Grid__00000000_.BottomStartArcShapesV2 = append(__BottomStartArcShapeV2Grid__00000000_.BottomStartArcShapesV2, __BottomStartArcShapeV2__00000566_)
	__BottomStartArcShapeV2Grid__00000000_.BottomStartArcShapesV2 = append(__BottomStartArcShapeV2Grid__00000000_.BottomStartArcShapesV2, __BottomStartArcShapeV2__00000567_)
	__BottomStartArcShapeV2Grid__00000000_.BottomStartArcShapesV2 = append(__BottomStartArcShapeV2Grid__00000000_.BottomStartArcShapesV2, __BottomStartArcShapeV2__00000568_)
	__EndArcShapeGrid__00000000_.EndArcShapes = append(__EndArcShapeGrid__00000000_.EndArcShapes, __EndArcShape__00006270_)
	__EndArcShapeGrid__00000000_.EndArcShapes = append(__EndArcShapeGrid__00000000_.EndArcShapes, __EndArcShape__00006271_)
	__EndArcShapeGrid__00000000_.EndArcShapes = append(__EndArcShapeGrid__00000000_.EndArcShapes, __EndArcShape__00006272_)
	__EndArcShapeV2Grid__00000000_.EndArcShapesV2 = append(__EndArcShapeV2Grid__00000000_.EndArcShapesV2, __EndArcShapeV2__00003196_)
	__EndArcShapeV2Grid__00000000_.EndArcShapesV2 = append(__EndArcShapeV2Grid__00000000_.EndArcShapesV2, __EndArcShapeV2__00003197_)
	__EndArcShapeV2Grid__00000000_.EndArcShapesV2 = append(__EndArcShapeV2Grid__00000000_.EndArcShapesV2, __EndArcShapeV2__00003198_)
	__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes = append(__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes, __GrowthCurveBezierShape__00036116_)
	__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes = append(__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes, __GrowthCurveBezierShape__00036118_)
	__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes = append(__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes, __GrowthCurveBezierShape__00036120_)
	__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes = append(__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes, __GrowthCurveBezierShape__00036117_)
	__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes = append(__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes, __GrowthCurveBezierShape__00036119_)
	__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes = append(__GrowthCurveBezierShapeGrid__00000000_.GrowthCurveBezierShapes, __GrowthCurveBezierShape__00036121_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00015299_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00015300_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00015301_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00015302_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000803_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000804_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000805_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000806_)
	__Library__00000000_.Plants = append(__Library__00000000_.Plants, __Plant__00000000_)
	__PerpendicularVectorGrid__00000000_.PerpendicularVectors = append(__PerpendicularVectorGrid__00000000_.PerpendicularVectors, __PerpendicularVector__00011094_)
	__PerpendicularVectorGrid__00000000_.PerpendicularVectors = append(__PerpendicularVectorGrid__00000000_.PerpendicularVectors, __PerpendicularVector__00011095_)
	__PerpendicularVectorGrid__00000000_.PerpendicularVectors = append(__PerpendicularVectorGrid__00000000_.PerpendicularVectors, __PerpendicularVector__00011096_)
	__PerpendicularVectorGrid__00000000_.PerpendicularVectors = append(__PerpendicularVectorGrid__00000000_.PerpendicularVectors, __PerpendicularVector__00011097_)
	__PerpendicularVectorGridHalfway__00000000_.PerpendicularVectorHalfways = append(__PerpendicularVectorGridHalfway__00000000_.PerpendicularVectorHalfways, __PerpendicularVectorHalfway__00007195_)
	__PerpendicularVectorGridHalfway__00000000_.PerpendicularVectorHalfways = append(__PerpendicularVectorGridHalfway__00000000_.PerpendicularVectorHalfways, __PerpendicularVectorHalfway__00007196_)
	__PerpendicularVectorGridHalfway__00000000_.PerpendicularVectorHalfways = append(__PerpendicularVectorGridHalfway__00000000_.PerpendicularVectorHalfways, __PerpendicularVectorHalfway__00007197_)
	__Plant__00000000_.PlantDiagrams = append(__Plant__00000000_.PlantDiagrams, __PlantDiagram__00000001_)
	__Plant__00000000_.AxesShape = __AxesShape__00000000_
	__Plant__00000000_.ReferenceRhombus = __RhombusShape__00000000_
	__Plant__00000000_.PlantCircumferenceShape = __PlantCircumferenceShape__00000001_
	__Plant__00000000_.GridPathShape = __GridPathShape__00000000_
	__Plant__00000000_.InitialRhombusGridShape = __InitialRhombusGridShape__00000000_
	__Plant__00000000_.ExplanationTextShape = __ExplanationTextShape__00000000_
	__Plant__00000000_.RotatedReferenceRhombus = __RhombusShape__00000003_
	__Plant__00000000_.RotatedPlantCircumferenceShape = __PlantCircumferenceShape__00000000_
	__Plant__00000000_.RotatedGridPathShape = __GridPathShape__00000001_
	__Plant__00000000_.RotatedRhombusGridShape2 = __RotatedRhombusGridShape__00000000_
	__Plant__00000000_.GrowthCurveRhombusGridShape = __GrowthCurveRhombusGridShape__00000000_
	__Plant__00000000_.GrowthVectorShape = __GrowthVectorShape__00000000_
	__Plant__00000000_.PerpendicularVectorGrid = __PerpendicularVectorGrid__00000000_
	__Plant__00000000_.PerpendicularVectorGridHalfway = __PerpendicularVectorGridHalfway__00000000_
	__Plant__00000000_.BaseVectorShapeGrid = __BaseVectorShapeGrid__00000000_
	__Plant__00000000_.ArcNormalVectorShapeGrid = __ArcNormalVectorShapeGrid__00000000_
	__Plant__00000000_.StartArcShapeGrid = __StartArcShapeGrid__00000000_
	__Plant__00000000_.StartArcShapeV2Grid = __StartArcShapeV2Grid__00000000_
	__Plant__00000000_.TopStartArcShapeV2Grid = __TopStartArcShapeV2Grid__00000000_
	__Plant__00000000_.EndArcShapeGrid = __EndArcShapeGrid__00000000_
	__Plant__00000000_.EndArcShapeV2Grid = __EndArcShapeV2Grid__00000000_
	__Plant__00000000_.TopEndArcShapeV2Grid = __TopEndArcShapeV2Grid__00000000_
	__Plant__00000000_.BottomStartArcShapeV2Grid = __BottomStartArcShapeV2Grid__00000000_
	__Plant__00000000_.BottomEndArcShapeV2Grid = __BottomEndArcShapeV2Grid__00000000_
	__Plant__00000000_.GrowthCurveBezierShapeGrid = __GrowthCurveBezierShapeGrid__00000000_
	__Plant__00000000_.StackOfGrowthCurve = __StackOfGrowthCurve__00000000_
	__PlantDiagram__00000001_.Rendered3DShape = __Rendered3DShape__00000001_
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000803_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000804_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000805_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000806_)
	__StartArcShapeGrid__00000000_.StartArcShapes = append(__StartArcShapeGrid__00000000_.StartArcShapes, __StartArcShape__00007200_)
	__StartArcShapeGrid__00000000_.StartArcShapes = append(__StartArcShapeGrid__00000000_.StartArcShapes, __StartArcShape__00007201_)
	__StartArcShapeGrid__00000000_.StartArcShapes = append(__StartArcShapeGrid__00000000_.StartArcShapes, __StartArcShape__00007202_)
	__StartArcShapeV2Grid__00000000_.StartArcShapesV2 = append(__StartArcShapeV2Grid__00000000_.StartArcShapesV2, __StartArcShapeV2__00003576_)
	__StartArcShapeV2Grid__00000000_.StartArcShapesV2 = append(__StartArcShapeV2Grid__00000000_.StartArcShapesV2, __StartArcShapeV2__00003577_)
	__StartArcShapeV2Grid__00000000_.StartArcShapesV2 = append(__StartArcShapeV2Grid__00000000_.StartArcShapesV2, __StartArcShapeV2__00003578_)
	__TopEndArcShapeV2Grid__00000000_.TopEndArcShapesV2 = append(__TopEndArcShapeV2Grid__00000000_.TopEndArcShapesV2, __TopEndArcShapeV2__00001041_)
	__TopEndArcShapeV2Grid__00000000_.TopEndArcShapesV2 = append(__TopEndArcShapeV2Grid__00000000_.TopEndArcShapesV2, __TopEndArcShapeV2__00001042_)
	__TopEndArcShapeV2Grid__00000000_.TopEndArcShapesV2 = append(__TopEndArcShapeV2Grid__00000000_.TopEndArcShapesV2, __TopEndArcShapeV2__00001043_)
	__TopStartArcShapeV2Grid__00000000_.TopStartArcShapesV2 = append(__TopStartArcShapeV2Grid__00000000_.TopStartArcShapesV2, __TopStartArcShapeV2__00001041_)
	__TopStartArcShapeV2Grid__00000000_.TopStartArcShapesV2 = append(__TopStartArcShapeV2Grid__00000000_.TopStartArcShapesV2, __TopStartArcShapeV2__00001042_)
	__TopStartArcShapeV2Grid__00000000_.TopStartArcShapesV2 = append(__TopStartArcShapeV2Grid__00000000_.TopStartArcShapesV2, __TopStartArcShapeV2__00001043_)
}
