// file generated by gong
// go module version: v0.0.0-20260709081613-fce61d464b0e+dirty
/* to edit this file with the default probe, use the command
go run github.com/fullstack-lang/gong/dsm/phylla/go/probe/cmd/probe@v0.0.0-20260709081613-fce61d464b0e stage.go
*/
package main

import (
	"slices"
	"time"

	"github.com/fullstack-lang/gong/dsm/phylla/go/models"
	// injection point for ident package import declaration{{ImportPackageDeclaration}}
)

// generated in order to avoid error in the package import
// if there are no elements in the stage to marshall
var (
	_ time.Time
	_ = slices.Index[[]int, int]
)

// function will stage objects
func _(stage *models.Stage) {

	// insertion point for declaration of instances to stage

	__AxesShape__00000000_ := (&models.AxesShape{Name: `Plant 1-AxesShape`}).Stage(stage)

	__ExplanationTextShape__00000000_ := (&models.ExplanationTextShape{Name: `Plant 1-ExplanationTextShape`}).Stage(stage)

	__GridPathShape__00000000_ := (&models.GridPathShape{Name: `Plant 1-GridPathShape`}).Stage(stage)
	__GridPathShape__00000001_ := (&models.GridPathShape{Name: `Plant 1-RotatedGridPathShape`}).Stage(stage)

	__GrowthCurveRhombusGridShape__00000000_ := (&models.GrowthCurveRhombusGridShape{Name: `Plant 1-GrowthCurveRhombusGridShape`}).Stage(stage)

	__GrowthCurveRhombusShape__00000000_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-0`}).Stage(stage)
	__GrowthCurveRhombusShape__00000001_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-1`}).Stage(stage)
	__GrowthCurveRhombusShape__00000002_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-2`}).Stage(stage)
	__GrowthCurveRhombusShape__00000003_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-3`}).Stage(stage)
	__GrowthCurveRhombusShape__00000004_ := (&models.GrowthCurveRhombusShape{Name: `Plant 1-GrowthCurveRhombusGridShape-4`}).Stage(stage)

	__InitialRhombusGridShape__00000000_ := (&models.InitialRhombusGridShape{Name: `Plant 1-InitialRhombusGridShape`}).Stage(stage)

	__InitialRhombusShape__00000000_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape--1-0`}).Stage(stage)
	__InitialRhombusShape__00000001_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape--1-1`}).Stage(stage)
	__InitialRhombusShape__00000002_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape--1-2`}).Stage(stage)
	__InitialRhombusShape__00000003_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-0-0`}).Stage(stage)
	__InitialRhombusShape__00000004_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-0-1`}).Stage(stage)
	__InitialRhombusShape__00000005_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-0-2`}).Stage(stage)
	__InitialRhombusShape__00000006_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-1-0`}).Stage(stage)
	__InitialRhombusShape__00000007_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-1-1`}).Stage(stage)
	__InitialRhombusShape__00000008_ := (&models.InitialRhombusShape{Name: `Plant 1-InitialRhombusGridShape-1-2`}).Stage(stage)

	__Library__00000000_ := (&models.Library{Name: ``}).Stage(stage)

	__Plant__00000000_ := (&models.Plant{Name: `Plant 1`}).Stage(stage)

	__PlantCircumferenceShape__00000000_ := (&models.PlantCircumferenceShape{Name: `Plant 1-RotatedPlantCircumferenceShape`}).Stage(stage)
	__PlantCircumferenceShape__00000001_ := (&models.PlantCircumferenceShape{Name: `Plant 1-PlantCircumferenceShape`}).Stage(stage)

	__PlantDiagram__00000000_ := (&models.PlantDiagram{Name: `Plant 1 - reference Rhombus`}).Stage(stage)
	__PlantDiagram__00000001_ := (&models.PlantDiagram{Name: `Plant 1 - rotated`}).Stage(stage)

	__RhombusShape__00000000_ := (&models.RhombusShape{Name: `Plant 1-ReferenceRhombus`}).Stage(stage)
	__RhombusShape__00000003_ := (&models.RhombusShape{Name: `Plant 1-RotatedReferenceRhombus`}).Stage(stage)

	__RotatedRhombusGridShape__00000000_ := (&models.RotatedRhombusGridShape{Name: `Plant 1-RotatedRhombusGridShape`}).Stage(stage)

	__RotatedRhombusShape__00000000_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape--1-0`}).Stage(stage)
	__RotatedRhombusShape__00000001_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape--1-1`}).Stage(stage)
	__RotatedRhombusShape__00000002_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape--1-2`}).Stage(stage)
	__RotatedRhombusShape__00000003_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-0-0`}).Stage(stage)
	__RotatedRhombusShape__00000004_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-0-1`}).Stage(stage)
	__RotatedRhombusShape__00000005_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-0-2`}).Stage(stage)
	__RotatedRhombusShape__00000006_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-1-0`}).Stage(stage)
	__RotatedRhombusShape__00000007_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-1-1`}).Stage(stage)
	__RotatedRhombusShape__00000008_ := (&models.RotatedRhombusShape{Name: `Plant 1-RotatedRhombusGridShape-1-2`}).Stage(stage)

	// insertion point for initialization of values

	__AxesShape__00000000_.Name = `Plant 1-AxesShape`
	__AxesShape__00000000_.LengthX = 200.000000
	__AxesShape__00000000_.LengthY = 677.000000
	__AxesShape__00000000_.IsWithHiddenHandle = true

	__ExplanationTextShape__00000000_.Name = `Plant 1-ExplanationTextShape`

	__GridPathShape__00000000_.Name = `Plant 1-GridPathShape`

	__GridPathShape__00000001_.Name = `Plant 1-RotatedGridPathShape`

	__GrowthCurveRhombusGridShape__00000000_.Name = `Plant 1-GrowthCurveRhombusGridShape`

	__GrowthCurveRhombusShape__00000000_.Name = `Plant 1-GrowthCurveRhombusGridShape-0`
	__GrowthCurveRhombusShape__00000000_.X = -61.279040
	__GrowthCurveRhombusShape__00000000_.Y = -79.024548

	__GrowthCurveRhombusShape__00000001_.Name = `Plant 1-GrowthCurveRhombusGridShape-1`
	__GrowthCurveRhombusShape__00000001_.X = 23.718008
	__GrowthCurveRhombusShape__00000001_.Y = -131.707581

	__GrowthCurveRhombusShape__00000002_.Name = `Plant 1-GrowthCurveRhombusGridShape-2`
	__GrowthCurveRhombusShape__00000002_.X = 84.997048
	__GrowthCurveRhombusShape__00000002_.Y = -52.683032

	__GrowthCurveRhombusShape__00000003_.Name = `Plant 1-GrowthCurveRhombusGridShape-3`
	__GrowthCurveRhombusShape__00000003_.X = 169.994095
	__GrowthCurveRhombusShape__00000003_.Y = -105.366065

	__GrowthCurveRhombusShape__00000004_.Name = `Plant 1-GrowthCurveRhombusGridShape-4`
	__GrowthCurveRhombusShape__00000004_.X = 231.273135
	__GrowthCurveRhombusShape__00000004_.Y = -26.341516

	__InitialRhombusGridShape__00000000_.Name = `Plant 1-InitialRhombusGridShape`

	__InitialRhombusShape__00000000_.Name = `Plant 1-InitialRhombusGridShape--1-0`
	__InitialRhombusShape__00000000_.X = -66.913061
	__InitialRhombusShape__00000000_.Y = 74.314483

	__InitialRhombusShape__00000001_.Name = `Plant 1-InitialRhombusGridShape--1-1`
	__InitialRhombusShape__00000001_.X = -133.826121
	__InitialRhombusShape__00000001_.Y = 0.000000

	__InitialRhombusShape__00000002_.Name = `Plant 1-InitialRhombusGridShape--1-2`
	__InitialRhombusShape__00000002_.X = -200.739182
	__InitialRhombusShape__00000002_.Y = -74.314483

	__InitialRhombusShape__00000003_.Name = `Plant 1-InitialRhombusGridShape-0-0`
	__InitialRhombusShape__00000003_.X = 0.000000
	__InitialRhombusShape__00000003_.Y = 0.000000

	__InitialRhombusShape__00000004_.Name = `Plant 1-InitialRhombusGridShape-0-1`
	__InitialRhombusShape__00000004_.X = -66.913061
	__InitialRhombusShape__00000004_.Y = -74.314483

	__InitialRhombusShape__00000005_.Name = `Plant 1-InitialRhombusGridShape-0-2`
	__InitialRhombusShape__00000005_.X = -133.826121
	__InitialRhombusShape__00000005_.Y = -148.628965

	__InitialRhombusShape__00000006_.Name = `Plant 1-InitialRhombusGridShape-1-0`
	__InitialRhombusShape__00000006_.X = 66.913061
	__InitialRhombusShape__00000006_.Y = -74.314483

	__InitialRhombusShape__00000007_.Name = `Plant 1-InitialRhombusGridShape-1-1`
	__InitialRhombusShape__00000007_.X = 0.000000
	__InitialRhombusShape__00000007_.Y = -148.628965

	__InitialRhombusShape__00000008_.Name = `Plant 1-InitialRhombusGridShape-1-2`
	__InitialRhombusShape__00000008_.X = -66.913061
	__InitialRhombusShape__00000008_.Y = -222.943448

	__Library__00000000_.Name = ``
	__Library__00000000_.NbPixPerCharacter = 8.000000
	__Library__00000000_.LogoSVGFile = ``
	__Library__00000000_.ComputedPrefix = ``
	__Library__00000000_.IsExpanded = true
	__Library__00000000_.IsRootLibrary = true

	__Plant__00000000_.Name = `Plant 1`
	__Plant__00000000_.N = 2
	__Plant__00000000_.M = 3
	__Plant__00000000_.RhombusInsideAngle = 96.000000
	__Plant__00000000_.RhombusSideLength = 100.000000
	__Plant__00000000_.ShiftToNearestCircle = 0
	__Plant__00000000_.ComputedPrefix = ``
	__Plant__00000000_.IsExpanded = true
	__Plant__00000000_.IsSelected = true
	__Plant__00000000_.IsPlantDiagramsNodeExpanded = true

	__PlantCircumferenceShape__00000000_.Name = `Plant 1-RotatedPlantCircumferenceShape`
	__PlantCircumferenceShape__00000000_.AngleDegree = 0.000000
	__PlantCircumferenceShape__00000000_.Length = 377.549223

	__PlantCircumferenceShape__00000001_.Name = `Plant 1-PlantCircumferenceShape`
	__PlantCircumferenceShape__00000001_.AngleDegree = 100.208458
	__PlantCircumferenceShape__00000001_.Length = 377.549223

	__PlantDiagram__00000000_.Name = `Plant 1 - reference Rhombus`
	__PlantDiagram__00000000_.OriginX = 297.000000
	__PlantDiagram__00000000_.OriginY = 792.000000
	__PlantDiagram__00000000_.IsHiddenAxesShape = false
	__PlantDiagram__00000000_.IsHiddenReferenceRhombus = false
	__PlantDiagram__00000000_.IsHiddenPlantCircumferenceShape = false
	__PlantDiagram__00000000_.IsHiddenGridPathShape = false
	__PlantDiagram__00000000_.IsHiddenRhombusGridShape = false
	__PlantDiagram__00000000_.IsHiddenExplanationTextShape = false
	__PlantDiagram__00000000_.IsHiddenRotatedReferenceRhombus = true
	__PlantDiagram__00000000_.IsHiddenRotatedPlantCircumferenceShape = true
	__PlantDiagram__00000000_.IsHiddenRotatedGridPathShape = true
	__PlantDiagram__00000000_.IsHiddenRotatedRhombusGridShape = true
	__PlantDiagram__00000000_.IsHiddenGrowthPathRhombusGridShape = true
	__PlantDiagram__00000000_.IsChecked = false
	__PlantDiagram__00000000_.ComputedPrefix = ``
	__PlantDiagram__00000000_.IsExpanded = false

	__PlantDiagram__00000001_.Name = `Plant 1 - rotated`
	__PlantDiagram__00000001_.OriginX = 417.000000
	__PlantDiagram__00000001_.OriginY = 757.000000
	__PlantDiagram__00000001_.IsHiddenAxesShape = false
	__PlantDiagram__00000001_.IsHiddenReferenceRhombus = true
	__PlantDiagram__00000001_.IsHiddenPlantCircumferenceShape = true
	__PlantDiagram__00000001_.IsHiddenGridPathShape = true
	__PlantDiagram__00000001_.IsHiddenRhombusGridShape = true
	__PlantDiagram__00000001_.IsHiddenExplanationTextShape = false
	__PlantDiagram__00000001_.IsHiddenRotatedReferenceRhombus = false
	__PlantDiagram__00000001_.IsHiddenRotatedPlantCircumferenceShape = false
	__PlantDiagram__00000001_.IsHiddenRotatedGridPathShape = false
	__PlantDiagram__00000001_.IsHiddenRotatedRhombusGridShape = false
	__PlantDiagram__00000001_.IsHiddenGrowthPathRhombusGridShape = false
	__PlantDiagram__00000001_.IsChecked = true
	__PlantDiagram__00000001_.ComputedPrefix = ``
	__PlantDiagram__00000001_.IsExpanded = true

	__RhombusShape__00000000_.Name = `Plant 1-ReferenceRhombus`
	__RhombusShape__00000000_.X = 0.000000
	__RhombusShape__00000000_.Y = 0.000000

	__RhombusShape__00000003_.Name = `Plant 1-RotatedReferenceRhombus`
	__RhombusShape__00000003_.X = 0.000000
	__RhombusShape__00000003_.Y = 0.000000

	__RotatedRhombusGridShape__00000000_.Name = `Plant 1-RotatedRhombusGridShape`

	__RotatedRhombusShape__00000000_.Name = `Plant 1-RotatedRhombusGridShape--1-0`
	__RotatedRhombusShape__00000000_.X = -61.279040
	__RotatedRhombusShape__00000000_.Y = -79.024548

	__RotatedRhombusShape__00000001_.Name = `Plant 1-RotatedRhombusGridShape--1-1`
	__RotatedRhombusShape__00000001_.X = 23.718008
	__RotatedRhombusShape__00000001_.Y = -131.707581

	__RotatedRhombusShape__00000002_.Name = `Plant 1-RotatedRhombusGridShape--1-2`
	__RotatedRhombusShape__00000002_.X = 108.715055
	__RotatedRhombusShape__00000002_.Y = -184.390613

	__RotatedRhombusShape__00000003_.Name = `Plant 1-RotatedRhombusGridShape-0-0`
	__RotatedRhombusShape__00000003_.X = 0.000000
	__RotatedRhombusShape__00000003_.Y = 0.000000

	__RotatedRhombusShape__00000004_.Name = `Plant 1-RotatedRhombusGridShape-0-1`
	__RotatedRhombusShape__00000004_.X = 84.997048
	__RotatedRhombusShape__00000004_.Y = -52.683032

	__RotatedRhombusShape__00000005_.Name = `Plant 1-RotatedRhombusGridShape-0-2`
	__RotatedRhombusShape__00000005_.X = 169.994095
	__RotatedRhombusShape__00000005_.Y = -105.366065

	__RotatedRhombusShape__00000006_.Name = `Plant 1-RotatedRhombusGridShape-1-0`
	__RotatedRhombusShape__00000006_.X = 61.279040
	__RotatedRhombusShape__00000006_.Y = 79.024548

	__RotatedRhombusShape__00000007_.Name = `Plant 1-RotatedRhombusGridShape-1-1`
	__RotatedRhombusShape__00000007_.X = 146.276088
	__RotatedRhombusShape__00000007_.Y = 26.341516

	__RotatedRhombusShape__00000008_.Name = `Plant 1-RotatedRhombusGridShape-1-2`
	__RotatedRhombusShape__00000008_.X = 231.273135
	__RotatedRhombusShape__00000008_.Y = -26.341516

	// insertion point for setup of pointers
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00000000_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00000001_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00000002_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00000003_)
	__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes = append(__GrowthCurveRhombusGridShape__00000000_.GrowthCurveRhombusShapes, __GrowthCurveRhombusShape__00000004_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000000_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000001_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000002_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000003_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000004_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000005_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000006_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000007_)
	__InitialRhombusGridShape__00000000_.InitialRhombusShapes = append(__InitialRhombusGridShape__00000000_.InitialRhombusShapes, __InitialRhombusShape__00000008_)
	__Library__00000000_.Plants = append(__Library__00000000_.Plants, __Plant__00000000_)
	__Plant__00000000_.PlantDiagrams = append(__Plant__00000000_.PlantDiagrams, __PlantDiagram__00000000_)
	__Plant__00000000_.PlantDiagrams = append(__Plant__00000000_.PlantDiagrams, __PlantDiagram__00000001_)
	__Plant__00000000_.AxesShape = __AxesShape__00000000_
	__Plant__00000000_.ReferenceRhombus = __RhombusShape__00000000_
	__Plant__00000000_.PlantCircumferenceShape = __PlantCircumferenceShape__00000001_
	__Plant__00000000_.GridPathShape = __GridPathShape__00000000_
	__Plant__00000000_.InitialRhombusGridShape = __InitialRhombusGridShape__00000000_
	__Plant__00000000_.ExplanationTextShape = __ExplanationTextShape__00000000_
	__Plant__00000000_.RotatedReferenceRhombus = __RhombusShape__00000003_
	__Plant__00000000_.RotatedPlantCircumferenceShape = __PlantCircumferenceShape__00000000_
	__Plant__00000000_.RotatedGridPathShape = __GridPathShape__00000001_
	__Plant__00000000_.RotatedRhombusGridShape2 = __RotatedRhombusGridShape__00000000_
	__Plant__00000000_.GrowthCurveRhombusGridShape = __GrowthCurveRhombusGridShape__00000000_
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000000_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000001_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000002_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000003_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000004_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000005_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000006_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000007_)
	__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes = append(__RotatedRhombusGridShape__00000000_.RotatedRhombusShapes, __RotatedRhombusShape__00000008_)
}
