// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, NullInt64, SelectionMode } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { AstructBstruct2UseDB } from '../astructbstruct2use-db'
import { AstructBstruct2UseService } from '../astructbstruct2use.service'

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-astructbstruct2usestable',
  templateUrl: './astructbstruct2uses-table.component.html',
  styleUrls: ['./astructbstruct2uses-table.component.css'],
})
export class AstructBstruct2UsesTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode

  // used if the component is called as a selection component of AstructBstruct2Use instances
  selection: SelectionModel<AstructBstruct2UseDB>;
  initialSelection = new Array<AstructBstruct2UseDB>();

  // the data source for the table
  astructbstruct2uses: AstructBstruct2UseDB[];
  matTableDataSource: MatTableDataSource<AstructBstruct2UseDB>

  // front repo, that will be referenced by this.astructbstruct2uses
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (astructbstruct2useDB: AstructBstruct2UseDB, property: string) => {
      switch (property) {
        // insertion point for specific sorting accessor
        case 'Name':
          return astructbstruct2useDB.Name;

        case 'Bstrcut2':
          return (astructbstruct2useDB.Bstrcut2 ? astructbstruct2useDB.Bstrcut2.Name : '');

        case 'Astruct_Anarrayofb2Use':
          return this.frontRepo.Astructs.get(astructbstruct2useDB.Astruct_Anarrayofb2UseDBID.Int64)?.Name;

        default:
          return AstructBstruct2UseDB[property];
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (astructbstruct2useDB: AstructBstruct2UseDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the astructbstruct2useDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += astructbstruct2useDB.Name.toLowerCase()
      if (astructbstruct2useDB.Bstrcut2) {
        mergedContent += astructbstruct2useDB.Bstrcut2.Name.toLowerCase()
      }
      if (astructbstruct2useDB.Astruct_Anarrayofb2UseDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Astructs.get(astructbstruct2useDB.Astruct_Anarrayofb2UseDBID.Int64)?.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private astructbstruct2useService: AstructBstruct2UseService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of astructbstruct2use instances
    public dialogRef: MatDialogRef<AstructBstruct2UsesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.astructbstruct2useService.AstructBstruct2UseServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getAstructBstruct2Uses()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "Bstrcut2",
        "Astruct_Anarrayofb2Use",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Bstrcut2",
        "Astruct_Anarrayofb2Use",
      ]
      this.selection = new SelectionModel<AstructBstruct2UseDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getAstructBstruct2Uses()
    this.matTableDataSource = new MatTableDataSource(this.astructbstruct2uses)
  }

  getAstructBstruct2Uses(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.astructbstruct2uses = this.frontRepo.AstructBstruct2Uses_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          this.astructbstruct2uses.forEach(
            astructbstruct2use => {
              let ID = this.dialogData.ID
              let revPointer = astructbstruct2use[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(astructbstruct2use)
              }
            }
          )
          this.selection = new SelectionModel<AstructBstruct2UseDB>(allowMultiSelect, this.initialSelection);
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

          if (sourceInstance[this.dialogData.SourceField]) {
            for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
              let astructbstruct2use = associationInstance[this.dialogData.IntermediateStructField]
              this.initialSelection.push(astructbstruct2use)
            }
          }
          this.selection = new SelectionModel<AstructBstruct2UseDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.astructbstruct2uses
      }
    )
  }

  // newAstructBstruct2Use initiate a new astructbstruct2use
  // create a new AstructBstruct2Use objet
  newAstructBstruct2Use() {
  }

  deleteAstructBstruct2Use(astructbstruct2useID: number, astructbstruct2use: AstructBstruct2UseDB) {
    // list of astructbstruct2uses is truncated of astructbstruct2use before the delete
    this.astructbstruct2uses = this.astructbstruct2uses.filter(h => h !== astructbstruct2use);

    this.astructbstruct2useService.deleteAstructBstruct2Use(astructbstruct2useID).subscribe(
      astructbstruct2use => {
        this.astructbstruct2useService.AstructBstruct2UseServiceChanged.next("delete")
      }
    );
  }

  editAstructBstruct2Use(astructbstruct2useID: number, astructbstruct2use: AstructBstruct2UseDB) {

  }

  // display astructbstruct2use in router
  displayAstructBstruct2UseInRouter(astructbstruct2useID: number) {
    this.router.navigate(["github_com_fullstack_lang_gong_test_go-" + "astructbstruct2use-display", astructbstruct2useID])
  }

  // set editor outlet
  setEditorRouterOutlet(astructbstruct2useID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gong_test_go_editor: ["github_com_fullstack_lang_gong_test_go-" + "astructbstruct2use-detail", astructbstruct2useID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(astructbstruct2useID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gong_test_go_presentation: ["github_com_fullstack_lang_gong_test_go-" + "astructbstruct2use-presentation", astructbstruct2useID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.astructbstruct2uses.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.astructbstruct2uses.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<AstructBstruct2UseDB>()

      // reset all initial selection of astructbstruct2use that belong to astructbstruct2use
      this.initialSelection.forEach(
        astructbstruct2use => {
          astructbstruct2use[this.dialogData.ReversePointer].Int64 = 0
          astructbstruct2use[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(astructbstruct2use)
        }
      )

      // from selection, set astructbstruct2use that belong to astructbstruct2use
      this.selection.selected.forEach(
        astructbstruct2use => {
          let ID = +this.dialogData.ID
          astructbstruct2use[this.dialogData.ReversePointer].Int64 = ID
          astructbstruct2use[this.dialogData.ReversePointer].Valid = true
          toUpdate.add(astructbstruct2use)
        }
      )

      // update all astructbstruct2use (only update selection & initial selection)
      toUpdate.forEach(
        astructbstruct2use => {
          this.astructbstruct2useService.updateAstructBstruct2Use(astructbstruct2use)
            .subscribe(astructbstruct2use => {
              this.astructbstruct2useService.AstructBstruct2UseServiceChanged.next("update")
            });
        }
      )
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s"]
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedAstructBstruct2Use = new Set<number>()
      for (let astructbstruct2use of this.initialSelection) {
        if (this.selection.selected.includes(astructbstruct2use)) {
          // console.log("astructbstruct2use " + astructbstruct2use.Name + " is still selected")
        } else {
          console.log("astructbstruct2use " + astructbstruct2use.Name + " has been unselected")
          unselectedAstructBstruct2Use.add(astructbstruct2use.ID)
          console.log("is unselected " + unselectedAstructBstruct2Use.has(astructbstruct2use.ID))
        }
      }

      // delete the association instance
      if (sourceInstance[this.dialogData.SourceField]) {
        for (let associationInstance of sourceInstance[this.dialogData.SourceField]) {
          let astructbstruct2use = associationInstance[this.dialogData.IntermediateStructField]
          if (unselectedAstructBstruct2Use.has(astructbstruct2use.ID)) {

            this.frontRepoService.deleteService( this.dialogData.IntermediateStruct, associationInstance )
          }
        }
      }

      // is the source array is emptyn create it
      if (sourceInstance[this.dialogData.SourceField] == undefined) {
        sourceInstance[this.dialogData.SourceField] = new Array<any>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField]) {
        this.selection.selected.forEach(
          astructbstruct2use => {
            if (!this.initialSelection.includes(astructbstruct2use)) {
              // console.log("astructbstruct2use " + astructbstruct2use.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + astructbstruct2use.Name,
              }

              associationInstance[this.dialogData.IntermediateStructField+"ID"] = new NullInt64
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Int64 = astructbstruct2use.ID
              associationInstance[this.dialogData.IntermediateStructField+"ID"].Valid = true

              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"] = new NullInt64
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Int64 = sourceInstance["ID"]
              associationInstance[this.dialogData.SourceStruct + "_" + this.dialogData.SourceField + "DBID"].Valid = true

              this.frontRepoService.postService( this.dialogData.IntermediateStruct, associationInstance )

            } else {
              // console.log("astructbstruct2use " + astructbstruct2use.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<AstructBstruct2UseDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
