// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { SliceOfPointerToGongStructFieldDB } from '../sliceofpointertogongstructfield-db'
import { SliceOfPointerToGongStructFieldService } from '../sliceofpointertogongstructfield.service'

// insertion point for additional imports

import { RouteService } from '../route-service';

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-sliceofpointertogongstructfieldstable',
  templateUrl: './sliceofpointertogongstructfields-table.component.html',
  styleUrls: ['./sliceofpointertogongstructfields-table.component.css'],
})
export class SliceOfPointerToGongStructFieldsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of SliceOfPointerToGongStructField instances
  selection: SelectionModel<SliceOfPointerToGongStructFieldDB> = new (SelectionModel)
  initialSelection = new Array<SliceOfPointerToGongStructFieldDB>()

  // the data source for the table
  sliceofpointertogongstructfields: SliceOfPointerToGongStructFieldDB[] = []
  matTableDataSource: MatTableDataSource<SliceOfPointerToGongStructFieldDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.sliceofpointertogongstructfields
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (sliceofpointertogongstructfieldDB: SliceOfPointerToGongStructFieldDB, property: string) => {
      switch (property) {
        case 'ID':
          return sliceofpointertogongstructfieldDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return sliceofpointertogongstructfieldDB.Name;

        case 'GongStruct':
          return (sliceofpointertogongstructfieldDB.GongStruct ? sliceofpointertogongstructfieldDB.GongStruct.Name : '');

        case 'Index':
          return sliceofpointertogongstructfieldDB.Index;

        case 'CompositeStructName':
          return sliceofpointertogongstructfieldDB.CompositeStructName;

        case 'GongStruct_SliceOfPointerToGongStructFields':
          if (this.frontRepo.GongStructs.get(sliceofpointertogongstructfieldDB.GongStruct_SliceOfPointerToGongStructFieldsDBID.Int64) != undefined) {
            return this.frontRepo.GongStructs.get(sliceofpointertogongstructfieldDB.GongStruct_SliceOfPointerToGongStructFieldsDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (sliceofpointertogongstructfieldDB: SliceOfPointerToGongStructFieldDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the sliceofpointertogongstructfieldDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += sliceofpointertogongstructfieldDB.Name.toLowerCase()
      if (sliceofpointertogongstructfieldDB.GongStruct) {
        mergedContent += sliceofpointertogongstructfieldDB.GongStruct.Name.toLowerCase()
      }
      mergedContent += sliceofpointertogongstructfieldDB.Index.toString()
      mergedContent += sliceofpointertogongstructfieldDB.CompositeStructName.toLowerCase()
      if (sliceofpointertogongstructfieldDB.GongStruct_SliceOfPointerToGongStructFieldsDBID.Int64 != 0) {
        mergedContent += this.frontRepo.GongStructs.get(sliceofpointertogongstructfieldDB.GongStruct_SliceOfPointerToGongStructFieldsDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private sliceofpointertogongstructfieldService: SliceOfPointerToGongStructFieldService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of sliceofpointertogongstructfield instances
    public dialogRef: MatDialogRef<SliceOfPointerToGongStructFieldsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,

    private routeService: RouteService,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.sliceofpointertogongstructfieldService.SliceOfPointerToGongStructFieldServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getSliceOfPointerToGongStructFields()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "GongStruct",
        "Index",
        "CompositeStructName",
        "GongStruct_SliceOfPointerToGongStructFields",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "GongStruct",
        "Index",
        "CompositeStructName",
        "GongStruct_SliceOfPointerToGongStructFields",
      ]
      this.selection = new SelectionModel<SliceOfPointerToGongStructFieldDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getSliceOfPointerToGongStructFields()

    this.matTableDataSource = new MatTableDataSource(this.sliceofpointertogongstructfields)
  }

  getSliceOfPointerToGongStructFields(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.sliceofpointertogongstructfields = this.frontRepo.SliceOfPointerToGongStructFields_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let sliceofpointertogongstructfield of this.sliceofpointertogongstructfields) {
            let ID = this.dialogData.ID
            let revPointer = sliceofpointertogongstructfield[this.dialogData.ReversePointer as keyof SliceOfPointerToGongStructFieldDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(sliceofpointertogongstructfield)
            }
            this.selection = new SelectionModel<SliceOfPointerToGongStructFieldDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, SliceOfPointerToGongStructFieldDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to SliceOfPointerToGongStructFieldDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as SliceOfPointerToGongStructFieldDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let sliceofpointertogongstructfield = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as SliceOfPointerToGongStructFieldDB
              this.initialSelection.push(sliceofpointertogongstructfield)
            }
          }

          this.selection = new SelectionModel<SliceOfPointerToGongStructFieldDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.sliceofpointertogongstructfields
      }
    )
  }

  // newSliceOfPointerToGongStructField initiate a new sliceofpointertogongstructfield
  // create a new SliceOfPointerToGongStructField objet
  newSliceOfPointerToGongStructField() {
  }

  deleteSliceOfPointerToGongStructField(sliceofpointertogongstructfieldID: number, sliceofpointertogongstructfield: SliceOfPointerToGongStructFieldDB) {
    // list of sliceofpointertogongstructfields is truncated of sliceofpointertogongstructfield before the delete
    this.sliceofpointertogongstructfields = this.sliceofpointertogongstructfields.filter(h => h !== sliceofpointertogongstructfield);

    this.sliceofpointertogongstructfieldService.deleteSliceOfPointerToGongStructField(sliceofpointertogongstructfieldID, this.GONG__StackPath).subscribe(
      sliceofpointertogongstructfield => {
        this.sliceofpointertogongstructfieldService.SliceOfPointerToGongStructFieldServiceChanged.next("delete")
      }
    );
  }

  editSliceOfPointerToGongStructField(sliceofpointertogongstructfieldID: number, sliceofpointertogongstructfield: SliceOfPointerToGongStructFieldDB) {

  }

  // set editor outlet
  setEditorRouterOutlet(sliceofpointertogongstructfieldID: number) {
    let outletName = this.routeService.getEditorOutlet(this.GONG__StackPath)
    let fullPath = this.routeService.getPathRoot() + "-" + "sliceofpointertogongstructfield" + "-detail"

    let outletConf: any = {}
    outletConf[outletName] = [fullPath, sliceofpointertogongstructfieldID, this.GONG__StackPath]

    this.router.navigate([{ outlets: outletConf }])
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.sliceofpointertogongstructfields.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.sliceofpointertogongstructfields.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<SliceOfPointerToGongStructFieldDB>()

      // reset all initial selection of sliceofpointertogongstructfield that belong to sliceofpointertogongstructfield
      for (let sliceofpointertogongstructfield of this.initialSelection) {
        let index = sliceofpointertogongstructfield[this.dialogData.ReversePointer as keyof SliceOfPointerToGongStructFieldDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(sliceofpointertogongstructfield)

      }

      // from selection, set sliceofpointertogongstructfield that belong to sliceofpointertogongstructfield
      for (let sliceofpointertogongstructfield of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = sliceofpointertogongstructfield[this.dialogData.ReversePointer as keyof SliceOfPointerToGongStructFieldDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(sliceofpointertogongstructfield)
      }


      // update all sliceofpointertogongstructfield (only update selection & initial selection)
      for (let sliceofpointertogongstructfield of toUpdate) {
        this.sliceofpointertogongstructfieldService.updateSliceOfPointerToGongStructField(sliceofpointertogongstructfield, this.GONG__StackPath)
          .subscribe(sliceofpointertogongstructfield => {
            this.sliceofpointertogongstructfieldService.SliceOfPointerToGongStructFieldServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, SliceOfPointerToGongStructFieldDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedSliceOfPointerToGongStructField = new Set<number>()
      for (let sliceofpointertogongstructfield of this.initialSelection) {
        if (this.selection.selected.includes(sliceofpointertogongstructfield)) {
          // console.log("sliceofpointertogongstructfield " + sliceofpointertogongstructfield.Name + " is still selected")
        } else {
          console.log("sliceofpointertogongstructfield " + sliceofpointertogongstructfield.Name + " has been unselected")
          unselectedSliceOfPointerToGongStructField.add(sliceofpointertogongstructfield.ID)
          console.log("is unselected " + unselectedSliceOfPointerToGongStructField.has(sliceofpointertogongstructfield.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let sliceofpointertogongstructfield = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as SliceOfPointerToGongStructFieldDB
      if (unselectedSliceOfPointerToGongStructField.has(sliceofpointertogongstructfield.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<SliceOfPointerToGongStructFieldDB>) = new Array<SliceOfPointerToGongStructFieldDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          sliceofpointertogongstructfield => {
            if (!this.initialSelection.includes(sliceofpointertogongstructfield)) {
              // console.log("sliceofpointertogongstructfield " + sliceofpointertogongstructfield.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + sliceofpointertogongstructfield.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = sliceofpointertogongstructfield.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = sliceofpointertogongstructfield.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("sliceofpointertogongstructfield " + sliceofpointertogongstructfield.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<SliceOfPointerToGongStructFieldDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
