package models

var abstractSyntax = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="1236.5"
   height="461.32935"
   viewBox="-10 -10 1236.5 461.32936"
   version="1.1"
   id="svg68"
   sodipodi:docname="abstract syntaxt.svg"
   inkscape:version="1.4 (e7c3feb1, 2024-10-09)"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <defs
     id="defs68" />
  <sodipodi:namedview
     id="namedview68"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:zoom="0.82164634"
     inkscape:cx="590.27829"
     inkscape:cy="539.16141"
     inkscape:window-width="1200"
     inkscape:window-height="1115"
     inkscape:window-x="0"
     inkscape:window-y="30"
     inkscape:window-maximized="0"
     inkscape:current-layer="svg68" />
  <style
     id="style1">text { font-family: Roboto, Arial, sans-serif !important; }</style>
  <g
     id="g68"
     transform="translate(-65.5,-53.17065)">
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <rect
       class="mat-mdc-tooltip-trigger mat-mdc-tooltip-disabled"
       x="568"
       y="49"
       width="240"
       height="100"
       rx="8"
       fill="#ffffff"
       fill-opacity="1"
       stroke="#d3d3d3"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="rect1">
      <!---->
    </rect>
    <!---->
    <rect
       class="click-through"
       x="571"
       y="52"
       width="240"
       height="30"
       rx="0"
       fill="#ffffff"
       fill-opacity="0"
       stroke="#ffffff"
       stroke-opacity="1"
       stroke-width="0"
       id="rect2" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="688"
       y="69"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="middle"
       font-weight="bold"
       font-style=""
       font-size=""
       font-family=""
       id="text2"><tspan
         x="688"
         dy="0"
         text-anchor="middle"
         id="tspan2">Movement</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="578"
       y="99"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="start"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text3"><tspan
         x="578"
         dy="0"
         text-anchor="start"
         id="tspan3">Date : Time</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="797"
       y="69"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="end"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text4"><tspan
         x="797"
         dy="0"
         text-anchor="end"
         id="tspan4">(17)</tspan><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <rect
       class="mat-mdc-tooltip-trigger mat-mdc-tooltip-disabled"
       x="1049"
       y="239"
       width="240"
       height="63"
       rx="8"
       fill="#ffffff"
       fill-opacity="1"
       stroke="#d3d3d3"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="rect4">
      <!---->
    </rect>
    <!---->
    <rect
       class="click-through"
       x="1052"
       y="242"
       width="240"
       height="30"
       rx="0"
       fill="#ffffff"
       fill-opacity="0"
       stroke="#ffffff"
       stroke-opacity="1"
       stroke-width="0"
       id="rect5" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="1169"
       y="259"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="middle"
       font-weight="bold"
       font-style=""
       font-size=""
       font-family=""
       id="text5"><tspan
         x="1169"
         dy="0"
         text-anchor="middle"
         id="tspan5">Place</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="1278"
       y="259"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="end"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text6"><tspan
         x="1278"
         dy="0"
         text-anchor="end"
         id="tspan6">(12)</tspan><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <rect
       class="mat-mdc-tooltip-trigger mat-mdc-tooltip-disabled"
       x="57"
       y="51"
       width="240"
       height="452"
       rx="8"
       fill="#ffffff"
       fill-opacity="1"
       stroke="#d3d3d3"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="rect6">
      <!---->
    </rect>
    <!---->
    <rect
       class="click-through"
       x="60"
       y="54"
       width="240"
       height="30"
       rx="0"
       fill="#ffffff"
       fill-opacity="0"
       stroke="#ffffff"
       stroke-opacity="1"
       stroke-width="0"
       id="rect7" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="177"
       y="71"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="middle"
       font-weight="bold"
       font-style=""
       font-size=""
       font-family=""
       id="text7"><tspan
         x="177"
         dy="0"
         text-anchor="middle"
         id="tspan7">Influence</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="67"
       y="101"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="start"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text8"><tspan
         x="67"
         dy="0"
         text-anchor="start"
         id="tspan8">IsHypothtical : bool</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="286"
       y="71"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="end"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text9"><tspan
         x="286"
         dy="0"
         text-anchor="end"
         id="tspan9">(49)</tspan><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <rect
       class="mat-mdc-tooltip-trigger mat-mdc-tooltip-disabled"
       x="571"
       y="209"
       width="240"
       height="117"
       rx="8"
       fill="#ffffff"
       fill-opacity="1"
       stroke="#d3d3d3"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="rect9">
      <!---->
    </rect>
    <!---->
    <rect
       class="click-through"
       x="574"
       y="212"
       width="240"
       height="30"
       rx="0"
       fill="#ffffff"
       fill-opacity="0"
       stroke="#ffffff"
       stroke-opacity="1"
       stroke-width="0"
       id="rect10" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="691"
       y="229"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="middle"
       font-weight="bold"
       font-style=""
       font-size=""
       font-family=""
       id="text10"><tspan
         x="691"
         dy="0"
         text-anchor="middle"
         id="tspan10">Artist</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="581"
       y="259"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="start"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text11"><tspan
         x="581"
         dy="0"
         text-anchor="start"
         id="tspan11">IsDead : bool</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="581"
       y="279"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="start"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text12"><tspan
         x="581"
         dy="0"
         text-anchor="start"
         id="tspan12">DateOfDeath : Time</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="800"
       y="229"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="end"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text13"><tspan
         x="800"
         dy="0"
         text-anchor="end"
         id="tspan13">(7)</tspan><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <rect
       class="mat-mdc-tooltip-trigger mat-mdc-tooltip-disabled"
       x="571"
       y="382"
       width="240"
       height="111"
       rx="8"
       fill="#ffffff"
       fill-opacity="1"
       stroke="#d3d3d3"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="rect13">
      <!---->
    </rect>
    <!---->
    <rect
       class="click-through"
       x="574"
       y="385"
       width="240"
       height="30"
       rx="0"
       fill="#ffffff"
       fill-opacity="0"
       stroke="#ffffff"
       stroke-opacity="1"
       stroke-width="0"
       id="rect14" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="691"
       y="402"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="middle"
       font-weight="bold"
       font-style=""
       font-size=""
       font-family=""
       id="text14"><tspan
         x="691"
         dy="0"
         text-anchor="middle"
         id="tspan14">ArtefactType</tspan><!----></text>
    <!---->
    <text
       class="click-through"
       x="800"
       y="402"
       fill="#000000"
       fill-opacity="1"
       stroke=""
       stroke-opacity="0"
       stroke-dasharray="none"
       writing-mode=""
       dominant-baseline=""
       text-anchor="end"
       font-weight=""
       font-style=""
       font-size=""
       font-family=""
       id="text15"><tspan
         x="800"
         dy="0"
         text-anchor="end"
         id="tspan15">(4)</tspan><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g18">
      <line
         class="moveable-line"
         x1="808"
         y1="99"
         x2="1157.7578"
         y2="99"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line15" />
      <line
         class="hit-area"
         x1="808"
         y1="99"
         x2="1157.7578"
         y2="99"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line16" />
      <line
         class="moveable-line"
         x1="1165.7578"
         y1="107"
         x2="1165.7578"
         y2="239"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="vertical"
         segment-number="1"
         id="line17" />
      <line
         class="hit-area"
         x1="1165.7578"
         y1="107"
         x2="1165.7578"
         y2="239"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="vertical"
         id="line18" />
      <!---->
    </g>
    <!---->
    <path
       d="m 1157.7578,99 a 8,8 0 0 1 8,8"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path18" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 1166.8185,240.06066 1157.7578,231 m 6.9394,9.06066 9.0606,-9.06066"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path19" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="1165.7578"
       y="223.39999"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text19"><tspan
         x="1165.7578"
         dy="0"
         text-anchor="end"
         id="tspan19"> Places </tspan><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g24">
      <line
         class="moveable-line"
         x1="297"
         y1="147.00797"
         x2="410.75784"
         y2="147.00797"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line19" />
      <line
         class="hit-area"
         x1="297"
         y1="147.00797"
         x2="410.75784"
         y2="147.00797"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line20" />
      <line
         class="moveable-line"
         x1="410.75784"
         y1="147.00797"
         x2="410.75784"
         y2="147.00797"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line21" />
      <line
         class="hit-area"
         x1="410.75784"
         y1="147.00797"
         x2="410.75784"
         y2="147.00797"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line22" />
      <line
         class="moveable-line"
         x1="410.75784"
         y1="147.00797"
         x2="568"
         y2="147.00797"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line23" />
      <line
         class="hit-area"
         x1="410.75784"
         y1="147.00797"
         x2="568"
         y2="147.00797"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line24" />
      <!---->
    </g>
    <!---->
    <path
       d="M 410.75784,147.00796"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path24" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 410.75784,147.00796"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path25" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 569.06066,148.06862 560,139.00796 m 9.06066,6.93934 L 560,155.00796"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path26" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="568"
       y="131.40796"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text26"><!----><tspan
         x="568"
         dy="0"
         text-anchor="end"
         id="tspan26"> SourceMovement </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g31">
      <line
         class="moveable-line"
         x1="297"
         y1="402.90054"
         x2="369.75793"
         y2="402.90054"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line26" />
      <line
         class="hit-area"
         x1="297"
         y1="402.90054"
         x2="369.75793"
         y2="402.90054"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line27" />
      <line
         class="moveable-line"
         x1="369.75793"
         y1="402.90054"
         x2="369.75793"
         y2="402.90054"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line28" />
      <line
         class="hit-area"
         x1="369.75793"
         y1="402.90054"
         x2="369.75793"
         y2="402.90054"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line29" />
      <line
         class="moveable-line"
         x1="369.75793"
         y1="402.90054"
         x2="571"
         y2="402.90054"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line30" />
      <line
         class="hit-area"
         x1="369.75793"
         y1="402.90054"
         x2="571"
         y2="402.90054"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line31" />
      <!---->
    </g>
    <!---->
    <path
       d="M 369.75792,402.90053"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path31" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 369.75792,402.90053"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path32" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 572.06066,403.96119 563,394.90053 m 9.06066,6.93934 L 563,410.90053"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path33" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="571"
       y="387.30054"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text33"><!----><tspan
         x="571"
         dy="0"
         text-anchor="end"
         id="tspan33"> SourceArtefactType </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g38">
      <line
         class="moveable-line"
         x1="297"
         y1="228.00772"
         x2="410.75784"
         y2="228.00772"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line33" />
      <line
         class="hit-area"
         x1="297"
         y1="228.00772"
         x2="410.75784"
         y2="228.00772"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line34" />
      <line
         class="moveable-line"
         x1="410.75784"
         y1="228.00772"
         x2="410.75784"
         y2="228.00772"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line35" />
      <line
         class="hit-area"
         x1="410.75784"
         y1="228.00772"
         x2="410.75784"
         y2="228.00772"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line36" />
      <line
         class="moveable-line"
         x1="410.75784"
         y1="228.00772"
         x2="571"
         y2="228.00772"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line37" />
      <line
         class="hit-area"
         x1="410.75784"
         y1="228.00772"
         x2="571"
         y2="228.00772"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line38" />
      <!---->
    </g>
    <!---->
    <path
       d="M 410.75784,228.00772"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path38" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 410.75784,228.00772"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path39" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 572.06066,229.06838 563,220.00772 m 9.06066,6.93934 L 563,236.00772"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path40" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="571"
       y="212.40771"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text40"><!----><tspan
         x="571"
         dy="0"
         text-anchor="end"
         id="tspan40"> SourceArtist </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g45">
      <line
         class="moveable-line"
         x1="297"
         y1="70.007957"
         x2="402.75793"
         y2="70.007957"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line40" />
      <line
         class="hit-area"
         x1="297"
         y1="70.007957"
         x2="402.75793"
         y2="70.007957"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line41" />
      <line
         class="moveable-line"
         x1="402.75793"
         y1="70.007957"
         x2="402.75793"
         y2="70.007957"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line42" />
      <line
         class="hit-area"
         x1="402.75793"
         y1="70.007957"
         x2="402.75793"
         y2="70.007957"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line43" />
      <line
         class="moveable-line"
         x1="402.75793"
         y1="70.007957"
         x2="568"
         y2="70.007957"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line44" />
      <line
         class="hit-area"
         x1="402.75793"
         y1="70.007957"
         x2="568"
         y2="70.007957"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line45" />
      <!---->
    </g>
    <!---->
    <path
       d="M 402.75792,70.007956"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path45" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 402.75792,70.007956"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path46" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 569.06066,71.068616 560,62.007956 m 9.06066,6.93934 L 560,78.007956"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path47" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="568"
       y="54.407955"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text47"><!----><tspan
         x="568"
         dy="0"
         text-anchor="end"
         id="tspan47"> TargetMovement </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g52">
      <line
         class="moveable-line"
         x1="297"
         y1="479.51364"
         x2="394.75775"
         y2="479.51364"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line47" />
      <line
         class="hit-area"
         x1="297"
         y1="479.51364"
         x2="394.75775"
         y2="479.51364"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line48" />
      <line
         class="moveable-line"
         x1="394.75775"
         y1="479.51364"
         x2="394.75775"
         y2="479.51364"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line49" />
      <line
         class="hit-area"
         x1="394.75775"
         y1="479.51364"
         x2="394.75775"
         y2="479.51364"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line50" />
      <line
         class="moveable-line"
         x1="394.75775"
         y1="479.51364"
         x2="571"
         y2="479.51364"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line51" />
      <line
         class="hit-area"
         x1="394.75775"
         y1="479.51364"
         x2="571"
         y2="479.51364"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line52" />
      <!---->
    </g>
    <!---->
    <path
       d="M 394.75776,479.51363"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path52" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 394.75776,479.51363"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path53" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 572.06066,480.57429 563,471.51363 m 9.06066,6.93934 L 563,487.51363"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path54" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="571"
       y="463.91364"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text54"><!----><tspan
         x="571"
         dy="0"
         text-anchor="end"
         id="tspan54"> TargetArtefactType </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g59">
      <line
         class="moveable-line"
         x1="297"
         y1="309.87125"
         x2="388.20001"
         y2="309.87125"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line54" />
      <line
         class="hit-area"
         x1="297"
         y1="309.87125"
         x2="388.20001"
         y2="309.87125"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line55" />
      <line
         class="moveable-line"
         x1="388.20001"
         y1="309.87125"
         x2="388.20001"
         y2="309.87125"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line56" />
      <line
         class="hit-area"
         x1="388.20001"
         y1="309.87125"
         x2="388.20001"
         y2="309.87125"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line57" />
      <line
         class="moveable-line"
         x1="388.20001"
         y1="309.87125"
         x2="571"
         y2="309.87125"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line58" />
      <line
         class="hit-area"
         x1="388.20001"
         y1="309.87125"
         x2="571"
         y2="309.87125"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line59" />
      <!---->
    </g>
    <!---->
    <path
       d="M 388.2,309.87125"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path59" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 388.2,309.87125"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path60" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 572.06066,310.93191 563,301.87125 m 9.06066,6.93934 L 563,317.87125"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path61" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="571"
       y="294.27124"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text61"><!----><tspan
         x="571"
         dy="0"
         text-anchor="end"
         id="tspan61"> TargetArtist </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <g
       id="g66">
      <line
         class="moveable-line"
         x1="811"
         y1="267.5"
         x2="902.20001"
         y2="267.5"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="0"
         id="line61" />
      <line
         class="hit-area"
         x1="811"
         y1="267.5"
         x2="902.20001"
         y2="267.5"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line62" />
      <line
         class="moveable-line"
         x1="902.20001"
         y1="267.5"
         x2="902.20001"
         y2="267.5"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="1"
         id="line63" />
      <line
         class="hit-area"
         x1="902.20001"
         y1="267.5"
         x2="902.20001"
         y2="267.5"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line64" />
      <line
         class="moveable-line"
         x1="902.20001"
         y1="267.5"
         x2="1049"
         y2="267.5"
         fill=""
         fill-opacity="0"
         stroke="#708090"
         stroke-opacity="1"
         stroke-width="3"
         stroke-dasharray="none"
         segment-orientation="horizontal"
         segment-number="2"
         id="line65" />
      <line
         class="hit-area"
         x1="902.20001"
         y1="267.5"
         x2="1049"
         y2="267.5"
         stroke="transparent"
         stroke-width="13"
         segment-orientation="horizontal"
         id="line66" />
      <!---->
    </g>
    <!---->
    <path
       d="M 902.2,267.5"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path66" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 902.2,267.5"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path67" />
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <path
       d="M 1050.0607,268.56066 1041,259.5 m 9.0607,6.93934 L 1041,275.5"
       fill=""
       fill-opacity="0"
       stroke="#708090"
       stroke-opacity="1"
       stroke-width="3"
       stroke-dasharray="none"
       id="path68" />
    <!---->
    <!---->
    <!---->
    <text
       class="click-through"
       x="1049"
       y="251.89999"
       font-weight="300"
       font-family=""
       font-size="15px"
       letter-spacing="0.1em"
       white-space=""
       fill="#000000"
       fill-opacity="1"
       stroke="#000000"
       stroke-opacity="1"
       stroke-width="1"
       stroke-dasharray="none"
       id="text68"><!----><tspan
         x="1049"
         dy="0"
         text-anchor="end"
         id="tspan68"> Place </tspan><!----><!----><!----><!----></text>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
  </g>
</svg>

`
