basePath: /api/github.com/fullstack-lang/gong/test2/go/v1
consumes:
- application/json
definitions:
  DeletedAt:
    $ref: '#/definitions/NullTime'
  Duration:
    description: |-
      A Duration represents the elapsed time between two instants
      as an int64 nanosecond count. The representation limits the
      largest representable duration to approximately 290 years.
    format: int64
    type: integer
    x-go-package: time
  NullBool:
    description: |-
      NullBool implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Bool:
        type: boolean
      Valid:
        type: boolean
    title: NullBool represents a bool that may be null.
    type: object
    x-go-package: database/sql
  NullFloat64:
    description: |-
      NullFloat64 implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Float64:
        format: double
        type: number
      Valid:
        type: boolean
    title: NullFloat64 represents a float64 that may be null.
    type: object
    x-go-package: database/sql
  NullInt64:
    description: |-
      NullInt64 implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Int64:
        format: int64
        type: integer
      Valid:
        type: boolean
    title: NullInt64 represents an int64 that may be null.
    type: object
    x-go-package: database/sql
  NullString:
    description: |-
      var s NullString
      err := db.QueryRow("SELECT name FROM foo WHERE id=?", id).Scan(&s)
      ...
      if s.Valid {
      use s.String
      } else {
      NULL value
      }
    properties:
      String:
        type: string
      Valid:
        type: boolean
    title: |-
      NullString represents a string that may be null.
      NullString implements the Scanner interface so
      it can be used as a scan destination:
    type: object
    x-go-package: database/sql
  NullTime:
    description: |-
      NullTime implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Time:
        format: date-time
        type: string
      Valid:
        type: boolean
    title: NullTime represents a time.Time that may be null.
    type: object
    x-go-package: database/sql
  aclassAPI:
    description: |-
      for POST, API, one needs the fields of the model as well as the fields
      from associations ("Has One" and "Has Many") that are generated to
      fullfill the ORM requirements for associations
    properties:
      Anotherbooleanfield:
        type: boolean
      Booleanfield:
        type: boolean
      CreatedAt:
        format: date-time
        type: string
      Date:
        format: date-time
        type: string
      DeletedAt:
        $ref: '#/definitions/DeletedAt'
      Duration1:
        $ref: '#/definitions/Duration'
      Floatfield:
        format: double
        type: number
      ID:
        format: uint64
        type: integer
      Intfield:
        format: int64
        type: integer
      Name:
        type: string
      UpdatedAt:
        format: date-time
        type: string
    title: AclassAPI is the input in POST API
    type: object
    x-go-name: AclassAPI
    x-go-package: github.com/fullstack-lang/gong/test2/go/orm
  aclassDB:
    description: |-
      It incorporates the GORM ID, basic fields from the model (because they can be serialized),
      the encoded version of pointers
    properties:
      Anotherbooleanfield_Data:
        $ref: '#/definitions/NullBool'
      Booleanfield_Data:
        $ref: '#/definitions/NullBool'
      CreatedAt:
        format: date-time
        type: string
      Date_Data:
        $ref: '#/definitions/NullTime'
      DeletedAt:
        $ref: '#/definitions/DeletedAt'
      Duration1_Data:
        $ref: '#/definitions/NullInt64'
      Floatfield_Data:
        $ref: '#/definitions/NullFloat64'
      ID:
        format: uint64
        type: integer
      Intfield_Data:
        $ref: '#/definitions/NullInt64'
      Name_Data:
        $ref: '#/definitions/NullString'
      UpdatedAt:
        format: date-time
        type: string
    title: AclassDB describes a aclass in the database
    type: object
    x-go-name: AclassDB
    x-go-package: github.com/fullstack-lang/gong/test2/go/orm
host: localhost:8080
info:
  description: test2 exposes types of a package.
  title: test2 backend API
  version: "0.1"
paths:
  /aclasss:
    get:
      description: Get all aclasss
      operationId: getAclasss
      responses:
        "200":
          $ref: '#/responses/aclassDBsResponse'
        default:
          $ref: '#/responses/genericError'
      tags:
      - aclasss
    post:
      consumes:
      - application/json
      description: Creates a aclass
      operationId: postAclass
      parameters:
      - description: The Aclass to submit or modify
        in: body
        name: Aclass
        schema:
          $ref: '#/definitions/aclassAPI'
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/aclassDBResponse'
      tags:
      - aclasss
  /aclasss/{ID}:
    delete:
      description: Delete a aclass
      operationId: deleteAclass
      parameters:
      - description: The ID of the order
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      responses:
        default:
          $ref: '#/responses/genericError'
      tags:
      - aclasss
    get:
      operationId: getAclass
      parameters:
      - description: The ID of the order
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/aclassDBResponse'
        default:
          $ref: '#/responses/genericError'
      summary: Gets the details for a aclass.
      tags:
      - aclasss
    patch:
      description: Update a aclass
      operationId: updateAclass
      parameters:
      - description: The ID of the order
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      - description: The Aclass to submit or modify
        in: body
        name: Aclass
        schema:
          $ref: '#/definitions/aclassAPI'
      responses:
        "200":
          $ref: '#/responses/aclassDBResponse'
        default:
          $ref: '#/responses/genericError'
      tags:
      - aclasss
  /commitnb:
    get:
      operationId: GetLastCommitNb
      tags:
      - backrepo
  /pushfromfrontnb:
    get:
      operationId: GetLastPushFromFrontNb
      tags:
      - backrepo
produces:
- application/json
responses:
  aclassDBResponse:
    description: AclassDBResponse provides response
    headers:
      Anotherbooleanfield_Data:
        description: |-
          Declation for basic field aclassDB.Anotherbooleanfield bool (to be completed)
          provide the sql storage for the boolan
      Booleanfield_Data:
        description: |-
          Declation for basic field aclassDB.Booleanfield bool (to be completed)
          provide the sql storage for the boolan
      CreatedAt:
        format: date-time
        type: string
      Date_Data:
        description: Declation for basic field aclassDB.Date
      DeletedAt: {}
      Duration1_Data:
        description: Declation for basic field aclassDB.Duration1 {{BasicKind}} (to
          be completed)
      Floatfield_Data:
        description: Declation for basic field aclassDB.Floatfield {{BasicKind}} (to
          be completed)
      ID:
        format: uint64
        type: integer
      Intfield_Data:
        description: Declation for basic field aclassDB.Intfield {{BasicKind}} (to
          be completed)
      Name_Data:
        description: |-
          insertion for basic fields declaration
          Declation for basic field aclassDB.Name {{BasicKind}} (to be completed)
      UpdatedAt:
        format: date-time
        type: string
    schema:
      $ref: '#/definitions/NullInt64'
  aclassDBsResponse:
    description: AclassDBs arrays aclassDBs
    schema:
      items:
        $ref: '#/definitions/aclassDB'
      type: array
  genericError:
    description: |-
      A GenericError is the default error message that is generated.
      For certain status codes there are more appropriate error structures.
    schema:
      properties:
        code:
          format: int32
          type: integer
          x-go-name: Code
        message:
          type: string
          x-go-name: Message
      type: object
  validationError:
    description: |-
      A ValidationError is an that is generated for validation failures.
      It has the same fields as a generic error but adds a Field property.
    schema:
      properties:
        code:
          format: int32
          type: integer
          x-go-name: Code
        field:
          type: string
          x-go-name: Field
        message:
          type: string
          x-go-name: Message
      type: object
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
