basePath: /api/github.com/fullstack-lang/gong/test2/go/v1
consumes:
- application/json
definitions:
  Astruct:
    description: Astruct demonstrate basic metabaron
    properties:
      Anarrayofa:
        items:
          $ref: '#/definitions/Astruct'
        type: array
      Name:
        type: string
    type: object
    x-go-package: github.com/fullstack-lang/gong/test2/go/models
  DeletedAt:
    $ref: '#/definitions/NullTime'
  NullInt64:
    description: |-
      NullInt64 implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Int64:
        format: int64
        type: integer
      Valid:
        type: boolean
    title: NullInt64 represents an int64 that may be null.
    type: object
    x-go-package: database/sql
  NullString:
    description: |-
      var s NullString
      err := db.QueryRow("SELECT name FROM foo WHERE id=?", id).Scan(&s)
      ...
      if s.Valid {
      use s.String
      } else {
      NULL value
      }
    properties:
      String:
        type: string
      Valid:
        type: boolean
    title: |-
      NullString represents a string that may be null.
      NullString implements the Scanner interface so
      it can be used as a scan destination:
    type: object
    x-go-package: database/sql
  NullTime:
    description: |-
      NullTime implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Time:
        format: date-time
        type: string
      Valid:
        type: boolean
    title: NullTime represents a time.Time that may be null.
    type: object
    x-go-package: database/sql
  astructAPI:
    description: |-
      for POST, API, one needs the fields of the model as well as the fields
      from associations ("Has One" and "Has Many") that are generated to
      fullfill the ORM requirements for associations
    properties:
      Anarrayofa:
        items:
          $ref: '#/definitions/Astruct'
        type: array
      Astruct_AnarrayofaDBID:
        $ref: '#/definitions/NullInt64'
      Astruct_AnarrayofaDBID_Index:
        $ref: '#/definitions/NullInt64'
      CreatedAt:
        format: date-time
        type: string
      DeletedAt:
        $ref: '#/definitions/DeletedAt'
      ID:
        format: uint64
        type: integer
      Name:
        type: string
      UpdatedAt:
        format: date-time
        type: string
    title: AstructAPI is the input in POST API
    type: object
    x-go-name: AstructAPI
    x-go-package: github.com/fullstack-lang/gong/test2/go/orm
  astructDB:
    description: |-
      It incorporates the GORM ID, basic fields from the model (because they can be serialized),
      the encoded version of pointers
    properties:
      Astruct_AnarrayofaDBID:
        $ref: '#/definitions/NullInt64'
      Astruct_AnarrayofaDBID_Index:
        $ref: '#/definitions/NullInt64'
      CreatedAt:
        format: date-time
        type: string
      DeletedAt:
        $ref: '#/definitions/DeletedAt'
      ID:
        format: uint64
        type: integer
      Name_Data:
        $ref: '#/definitions/NullString'
      UpdatedAt:
        format: date-time
        type: string
    title: AstructDB describes a astruct in the database
    type: object
    x-go-name: AstructDB
    x-go-package: github.com/fullstack-lang/gong/test2/go/orm
host: localhost:8080
info:
  description: test2 exposes types of a package.
  title: test2 backend API
  version: "0.1"
paths:
  /astructs:
    get:
      description: Get all astructs
      operationId: getAstructs
      responses:
        "200":
          $ref: '#/responses/astructDBsResponse'
        default:
          $ref: '#/responses/genericError'
      tags:
      - astructs
    post:
      consumes:
      - application/json
      description: Creates a astruct
      operationId: postAstruct
      parameters:
      - description: The Astruct to submit or modify
        in: body
        name: Astruct
        schema:
          $ref: '#/definitions/astructAPI'
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/astructDBResponse'
      tags:
      - astructs
  /astructs/{ID}:
    delete:
      description: Delete a astruct
      operationId: deleteAstruct
      parameters:
      - description: The ID of the order
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      responses:
        default:
          $ref: '#/responses/genericError'
      tags:
      - astructs
    get:
      operationId: getAstruct
      parameters:
      - description: The ID of the order
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      responses:
        "200":
          $ref: '#/responses/astructDBResponse'
        default:
          $ref: '#/responses/genericError'
      summary: Gets the details for a astruct.
      tags:
      - astructs
    patch:
      description: Update a astruct
      operationId: updateAstruct
      parameters:
      - description: The ID of the order
        format: int64
        in: path
        name: ID
        required: true
        type: integer
      - description: The Astruct to submit or modify
        in: body
        name: Astruct
        schema:
          $ref: '#/definitions/astructAPI'
      responses:
        "200":
          $ref: '#/responses/astructDBResponse'
        default:
          $ref: '#/responses/genericError'
      tags:
      - astructs
  /commitnb:
    get:
      operationId: GetLastCommitNb
      tags:
      - backrepo
  /pushfromfrontnb:
    get:
      operationId: GetLastPushFromFrontNb
      tags:
      - backrepo
produces:
- application/json
responses:
  astructDBResponse:
    description: AstructDBResponse provides response
    headers:
      Astruct_AnarrayofaDBID:
        description: |-
          insertion for pointer fields encoding declaration
          Implementation of a reverse ID for field Astruct{}.Anarrayofa []*Astruct
      Astruct_AnarrayofaDBID_Index:
        description: implementation of the index of the withing the slice
      CreatedAt:
        format: date-time
        type: string
      DeletedAt: {}
      ID:
        format: uint64
        type: integer
      Name_Data:
        description: |-
          insertion for basic fields declaration
          Declation for basic field astructDB.Name {{BasicKind}} (to be completed)
      UpdatedAt:
        format: date-time
        type: string
    schema:
      $ref: '#/definitions/NullInt64'
  astructDBsResponse:
    description: AstructDBs arrays astructDBs
    schema:
      items:
        $ref: '#/definitions/astructDB'
      type: array
  genericError:
    description: |-
      A GenericError is the default error message that is generated.
      For certain status codes there are more appropriate error structures.
    schema:
      properties:
        code:
          format: int32
          type: integer
          x-go-name: Code
        message:
          type: string
          x-go-name: Message
      type: object
  validationError:
    description: |-
      A ValidationError is an that is generated for validation failures.
      It has the same fields as a generic error but adds a Field property.
    schema:
      properties:
        code:
          format: int32
          type: integer
          x-go-name: Code
        field:
          type: string
          x-go-name: Field
        message:
          type: string
          x-go-name: Message
      type: object
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
