// generated from ng_file_public_api_ts.go
/*
* Public API Surface of gong
*/

export * from './lib/gong.module'

export * from './lib/splitter/splitter.component'
export * from './lib/sidebar/sidebar.component'

export * from './lib/front-repo.service'
export * from './lib/commitnb.service'


export * from './lib/gongbasicfield-detail/gongbasicfield-detail.component'
export * from './lib/gongbasicfield-presentation/gongbasicfield-presentation.component'
export * from './lib/gongbasicfields-table/gongbasicfields-table.component'
export * from './lib/gongbasicfield-db'
export * from './lib/gongbasicfield-api'
export * from './lib/gongbasicfield.service'

export * from './lib/gongenum-detail/gongenum-detail.component'
export * from './lib/gongenum-presentation/gongenum-presentation.component'
export * from './lib/gongenums-table/gongenums-table.component'
export * from './lib/gongenum-db'
export * from './lib/gongenum-api'
export * from './lib/gongenum.service'

export * from './lib/gongenumvalue-detail/gongenumvalue-detail.component'
export * from './lib/gongenumvalue-presentation/gongenumvalue-presentation.component'
export * from './lib/gongenumvalues-table/gongenumvalues-table.component'
export * from './lib/gongenumvalue-db'
export * from './lib/gongenumvalue-api'
export * from './lib/gongenumvalue.service'

export * from './lib/gongstruct-detail/gongstruct-detail.component'
export * from './lib/gongstruct-presentation/gongstruct-presentation.component'
export * from './lib/gongstructs-table/gongstructs-table.component'
export * from './lib/gongstruct-db'
export * from './lib/gongstruct-api'
export * from './lib/gongstruct.service'

export * from './lib/gongtimefield-detail/gongtimefield-detail.component'
export * from './lib/gongtimefield-presentation/gongtimefield-presentation.component'
export * from './lib/gongtimefields-table/gongtimefields-table.component'
export * from './lib/gongtimefield-db'
export * from './lib/gongtimefield-api'
export * from './lib/gongtimefield.service'

export * from './lib/modelpkg-detail/modelpkg-detail.component'
export * from './lib/modelpkg-presentation/modelpkg-presentation.component'
export * from './lib/modelpkgs-table/modelpkgs-table.component'
export * from './lib/modelpkg-db'
export * from './lib/modelpkg-api'
export * from './lib/modelpkg.service'

export * from './lib/pointertogongstructfield-detail/pointertogongstructfield-detail.component'
export * from './lib/pointertogongstructfield-presentation/pointertogongstructfield-presentation.component'
export * from './lib/pointertogongstructfields-table/pointertogongstructfields-table.component'
export * from './lib/pointertogongstructfield-db'
export * from './lib/pointertogongstructfield-api'
export * from './lib/pointertogongstructfield.service'

export * from './lib/sliceofpointertogongstructfield-detail/sliceofpointertogongstructfield-detail.component'
export * from './lib/sliceofpointertogongstructfield-presentation/sliceofpointertogongstructfield-presentation.component'
export * from './lib/sliceofpointertogongstructfields-table/sliceofpointertogongstructfields-table.component'
export * from './lib/sliceofpointertogongstructfield-db'
export * from './lib/sliceofpointertogongstructfield-api'
export * from './lib/sliceofpointertogongstructfield.service'


export * from './lib/BackRepoInsertionPoint'
export * from './lib/BackRepoPerStructSubTemplate'
export * from './lib/BackRepoSubTemplateInsertion'
export * from './lib/ControllerFilPerStructSubTemplate'
export * from './lib/ControllerFileInsertionPoint'
export * from './lib/ControllersRegistrationsSubTemplateInsertions'
export * from './lib/ModelGongInsertionPoints'
export * from './lib/ModelGongSubTemplate'
export * from './lib/NgClassSubTemplate'
export * from './lib/NgClassTsInsertionPoint'
export * from './lib/NgDetailHtmlInsertionPoint'
export * from './lib/NgDetailHtmlSubTemplate'
export * from './lib/NgDetailSubTemplate'
export * from './lib/NgDetailTsInsertionPoint'
export * from './lib/NgEnumInsertionPoint'
export * from './lib/NgEnumSubTemplate'
export * from './lib/NgLibFrontRepoServiceSubSubTemplate'
export * from './lib/NgLibFrontRepoServiceSubTemplate'
export * from './lib/NgLibMapComponentsServiceSubTemplate'
export * from './lib/NgLibModuleServiceSubTemplate'
export * from './lib/NgPresentationHtmlSubTemplate'
export * from './lib/NgPresentationSubTemplate'
export * from './lib/NgPresentationTsInsertionPoint'
export * from './lib/NgPublicApiInsertionPoint'
export * from './lib/NgPublicApiSubTemplate'
export * from './lib/NgRoutingServiceSubTemplate'
export * from './lib/NgServiceSubTemplate'
export * from './lib/NgServiceTsInsertionPoint'
export * from './lib/NgSidebarHtmlInsertionPoint'
export * from './lib/NgSidebarHtmlSubTemplate'
export * from './lib/NgSidebarTsInsertionPoint'
export * from './lib/NgSidebarTsStructSubTemplate'
export * from './lib/NgSidebarTsSubInsertionPoint'
export * from './lib/NgSidebarTsSubTemplate'
export * from './lib/NgTableHTMLSubTemplate'
export * from './lib/NgTableHtmlInsertionPoint'
export * from './lib/NgTableSubTemplate'
export * from './lib/NgTableTsInsertionPoint'
export * from './lib/OrmFileStructSubSubTemplate'
export * from './lib/OrmFileStructSubTemplate'
export * from './lib/OrmSetupCumulSubTemplate'
