// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"net/http"

	"github.com/fullstack-lang/gong/stacks/gong/go/models"
	"github.com/fullstack-lang/gong/stacks/gong/go/orm"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// declaration in order to justify use of the models import
var __PointerToGongStructField__dummysDeclaration__ models.PointerToGongStructField

// An PointerToGongStructFieldID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getPointerToGongStructField updatePointerToGongStructField deletePointerToGongStructField
type PointerToGongStructFieldID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// PointerToGongStructFieldInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postPointerToGongStructField updatePointerToGongStructField
type PointerToGongStructFieldInput struct {
	// The PointerToGongStructField to submit or modify
	// in: body
	PointerToGongStructField *orm.PointerToGongStructFieldAPI
}

// GetPointerToGongStructFields
//
// swagger:route GET /pointertogongstructfields pointertogongstructfields getPointerToGongStructFields
//
// Get all pointertogongstructfields
//
// Responses:
//    default: genericError
//        200: pointertogongstructfieldDBsResponse
func GetPointerToGongStructFields(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	var pointertogongstructfields []orm.PointerToGongStructFieldDB
	query := db.Find(&pointertogongstructfields)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// for each pointertogongstructfield, update fields from the database nullable fields
	for idx := range pointertogongstructfields {
		pointertogongstructfield := &pointertogongstructfields[idx]
		_ = pointertogongstructfield
		// insertion point for updating fields
		if pointertogongstructfield.Name_Data.Valid {
			pointertogongstructfield.Name = pointertogongstructfield.Name_Data.String
		}

	}

	c.JSON(http.StatusOK, pointertogongstructfields)
}

// PostPointerToGongStructField
//
// swagger:route POST /pointertogongstructfields pointertogongstructfields postPointerToGongStructField
//
// Creates a pointertogongstructfield
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: pointertogongstructfieldDBResponse
func PostPointerToGongStructField(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Validate input
	var input orm.PointerToGongStructFieldAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create pointertogongstructfield
	pointertogongstructfieldDB := orm.PointerToGongStructFieldDB{}
	pointertogongstructfieldDB.PointerToGongStructFieldAPI = input
	// insertion point for nullable field set
	pointertogongstructfieldDB.Name_Data.String = input.Name
	pointertogongstructfieldDB.Name_Data.Valid = true

	query := db.Create(&pointertogongstructfieldDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, pointertogongstructfieldDB)
}

// GetPointerToGongStructField
//
// swagger:route GET /pointertogongstructfields/{ID} pointertogongstructfields getPointerToGongStructField
//
// Gets the details for a pointertogongstructfield.
//
// Responses:
//    default: genericError
//        200: pointertogongstructfieldDBResponse
func GetPointerToGongStructField(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get pointertogongstructfield in DB
	var pointertogongstructfield orm.PointerToGongStructFieldDB
	if err := db.First(&pointertogongstructfield, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// insertion point for fields value set from nullable fields
	if pointertogongstructfield.Name_Data.Valid {
		pointertogongstructfield.Name = pointertogongstructfield.Name_Data.String
	}

	c.JSON(http.StatusOK, pointertogongstructfield)
}

// UpdatePointerToGongStructField
//
// swagger:route PATCH /pointertogongstructfields/{ID} pointertogongstructfields updatePointerToGongStructField
//
// Update a pointertogongstructfield
//
// Responses:
//    default: genericError
//        200: pointertogongstructfieldDBResponse
func UpdatePointerToGongStructField(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var pointertogongstructfieldDB orm.PointerToGongStructFieldDB

	// fetch the pointertogongstructfield
	query := db.First(&pointertogongstructfieldDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.PointerToGongStructFieldAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	// insertion point for nullable field set
	input.Name_Data.String = input.Name
	input.Name_Data.Valid = true

	query = db.Model(&pointertogongstructfieldDB).Updates(input)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	// return status OK with the marshalling of the the pointertogongstructfieldDB
	c.JSON(http.StatusOK, pointertogongstructfieldDB)
}

// DeletePointerToGongStructField
//
// swagger:route DELETE /pointertogongstructfields/{ID} pointertogongstructfields deletePointerToGongStructField
//
// Delete a pointertogongstructfield
//
// Responses:
//    default: genericError
func DeletePointerToGongStructField(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var pointertogongstructfieldDB orm.PointerToGongStructFieldDB
	if err := db.First(&pointertogongstructfieldDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&pointertogongstructfieldDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
