// generated by ng_file_service_ts
import { Injectable, Component, Inject, DOCUMENT } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Location } from '@angular/common'
/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { ShapeAPI } from './shape-api'
import { Shape, CopyShapeToShapeAPI } from './shape'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { Vector2API } from './vector2-api'

@Injectable({
  providedIn: 'root'
})
export class ShapeService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ShapeServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private shapesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.shapesUrl = origin + '/api/github.com/fullstack-lang/gong/lib/threejs/go/v1/shapes';
  }

  /** GET shapes from the server */
  // gets is more robust to refactoring
  gets(Name: string, frontRepo: FrontRepo): Observable<ShapeAPI[]> {
    return this.getShapes(Name, frontRepo)
  }
  getShapes(Name: string, frontRepo: FrontRepo): Observable<ShapeAPI[]> {

    let params = new HttpParams().set("Name", Name)

    return this.http.get<ShapeAPI[]>(this.shapesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<ShapeAPI[]>('getShapes', []))
      );
  }

  /** GET shape by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, Name: string, frontRepo: FrontRepo): Observable<ShapeAPI> {
    return this.getShape(id, Name, frontRepo)
  }
  getShape(id: number, Name: string, frontRepo: FrontRepo): Observable<ShapeAPI> {

    let params = new HttpParams().set("Name", Name)

    const url = `${this.shapesUrl}/${id}`;
    return this.http.get<ShapeAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched shape id=${id}`)),
      catchError(this.handleError<ShapeAPI>(`getShape id=${id}`))
    );
  }

  // postFront copy shape to a version with encoded pointers and post to the back
  postFront(shape: Shape, Name: string): Observable<ShapeAPI> {
    let shapeAPI = new ShapeAPI
    CopyShapeToShapeAPI(shape, shapeAPI)
    const id = typeof shapeAPI === 'number' ? shapeAPI : shapeAPI.ID
    const url = `${this.shapesUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ShapeAPI>(url, shapeAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ShapeAPI>('postShape'))
    );
  }

  /** POST: add a new shape to the server */
  post(shapedb: ShapeAPI, Name: string, frontRepo: FrontRepo): Observable<ShapeAPI> {
    return this.postShape(shapedb, Name, frontRepo)
  }
  postShape(shapedb: ShapeAPI, Name: string, frontRepo: FrontRepo): Observable<ShapeAPI> {

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ShapeAPI>(this.shapesUrl, shapedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted shapedb id=${shapedb.ID}`)
      }),
      catchError(this.handleError<ShapeAPI>('postShape'))
    );
  }

  /** DELETE: delete the shapedb from the server */
  delete(shapedb: ShapeAPI | number, Name: string): Observable<ShapeAPI> {
    return this.deleteShape(shapedb, Name)
  }
  deleteShape(shapedb: ShapeAPI | number, Name: string): Observable<ShapeAPI> {
    const id = typeof shapedb === 'number' ? shapedb : shapedb.ID;
    const url = `${this.shapesUrl}/${id}`;

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ShapeAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted shapedb id=${id}`)),
      catchError(this.handleError<ShapeAPI>('deleteShape'))
    );
  }

  // updateFront copy shape to a version with encoded pointers and update to the back
  updateFront(shape: Shape, Name: string): Observable<ShapeAPI> {
    let shapeAPI = new ShapeAPI
    CopyShapeToShapeAPI(shape, shapeAPI)
    const id = typeof shapeAPI === 'number' ? shapeAPI : shapeAPI.ID
    const url = `${this.shapesUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<ShapeAPI>(url, shapeAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ShapeAPI>('updateShape'))
    );
  }

  /** PUT: update the shapedb on the server */
  update(shapedb: ShapeAPI, Name: string, frontRepo: FrontRepo): Observable<ShapeAPI> {
    return this.updateShape(shapedb, Name, frontRepo)
  }
  updateShape(shapedb: ShapeAPI, Name: string, frontRepo: FrontRepo): Observable<ShapeAPI> {
    const id = typeof shapedb === 'number' ? shapedb : shapedb.ID;
    const url = `${this.shapesUrl}/${id}`;


    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ShapeAPI>(url, shapedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated shapedb id=${shapedb.ID}`)
      }),
      catchError(this.handleError<ShapeAPI>('updateShape'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ShapeService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging
      console.error("ShapeService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
