// generated by ng_file_service_ts
import { Injectable, Component, Inject, DOCUMENT } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Location } from '@angular/common'
/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { Form2API } from './form2-api'
import { Form2, CopyForm2ToForm2API } from './form2'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class Form2Service {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  Form2ServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private form2sUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.form2sUrl = origin + '/api/github.com/fullstack-lang/gong/lib/form/go/v1/form2s';
  }

  /** GET form2s from the server */
  // gets is more robust to refactoring
  gets(Name: string, frontRepo: FrontRepo): Observable<Form2API[]> {
    return this.getForm2s(Name, frontRepo)
  }
  getForm2s(Name: string, frontRepo: FrontRepo): Observable<Form2API[]> {

    let params = new HttpParams().set("Name", Name)

    return this.http.get<Form2API[]>(this.form2sUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<Form2API[]>('getForm2s', []))
      );
  }

  /** GET form2 by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, Name: string, frontRepo: FrontRepo): Observable<Form2API> {
    return this.getForm2(id, Name, frontRepo)
  }
  getForm2(id: number, Name: string, frontRepo: FrontRepo): Observable<Form2API> {

    let params = new HttpParams().set("Name", Name)

    const url = `${this.form2sUrl}/${id}`;
    return this.http.get<Form2API>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched form2 id=${id}`)),
      catchError(this.handleError<Form2API>(`getForm2 id=${id}`))
    );
  }

  // postFront copy form2 to a version with encoded pointers and post to the back
  postFront(form2: Form2, Name: string): Observable<Form2API> {
    let form2API = new Form2API
    CopyForm2ToForm2API(form2, form2API)
    const id = typeof form2API === 'number' ? form2API : form2API.ID
    const url = `${this.form2sUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<Form2API>(url, form2API, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<Form2API>('postForm2'))
    );
  }

  /** POST: add a new form2 to the server */
  post(form2db: Form2API, Name: string, frontRepo: FrontRepo): Observable<Form2API> {
    return this.postForm2(form2db, Name, frontRepo)
  }
  postForm2(form2db: Form2API, Name: string, frontRepo: FrontRepo): Observable<Form2API> {

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<Form2API>(this.form2sUrl, form2db, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted form2db id=${form2db.ID}`)
      }),
      catchError(this.handleError<Form2API>('postForm2'))
    );
  }

  /** DELETE: delete the form2db from the server */
  delete(form2db: Form2API | number, Name: string): Observable<Form2API> {
    return this.deleteForm2(form2db, Name)
  }
  deleteForm2(form2db: Form2API | number, Name: string): Observable<Form2API> {
    const id = typeof form2db === 'number' ? form2db : form2db.ID;
    const url = `${this.form2sUrl}/${id}`;

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<Form2API>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted form2db id=${id}`)),
      catchError(this.handleError<Form2API>('deleteForm2'))
    );
  }

  // updateFront copy form2 to a version with encoded pointers and update to the back
  updateFront(form2: Form2, Name: string): Observable<Form2API> {
    let form2API = new Form2API
    CopyForm2ToForm2API(form2, form2API)
    const id = typeof form2API === 'number' ? form2API : form2API.ID
    const url = `${this.form2sUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<Form2API>(url, form2API, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<Form2API>('updateForm2'))
    );
  }

  /** PUT: update the form2db on the server */
  update(form2db: Form2API, Name: string, frontRepo: FrontRepo): Observable<Form2API> {
    return this.updateForm2(form2db, Name, frontRepo)
  }
  updateForm2(form2db: Form2API, Name: string, frontRepo: FrontRepo): Observable<Form2API> {
    const id = typeof form2db === 'number' ? form2db : form2db.ID;
    const url = `${this.form2sUrl}/${id}`;


    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<Form2API>(url, form2db, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated form2db id=${form2db.ID}`)
      }),
      catchError(this.handleError<Form2API>('updateForm2'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in Form2Service', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging
      console.error("Form2Service" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
