// generated by ng_file_service_ts
import { Injectable, Component, Inject, DOCUMENT } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Location } from '@angular/common'
/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { RectAnchoredJpgImageAPI } from './rectanchoredjpgimage-api'
import { RectAnchoredJpgImage, CopyRectAnchoredJpgImageToRectAnchoredJpgImageAPI } from './rectanchoredjpgimage'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class RectAnchoredJpgImageService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  RectAnchoredJpgImageServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private rectanchoredjpgimagesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.rectanchoredjpgimagesUrl = origin + '/api/github.com/fullstack-lang/gong/lib/svg/go/v1/rectanchoredjpgimages';
  }

  /** GET rectanchoredjpgimages from the server */
  // gets is more robust to refactoring
  gets(Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI[]> {
    return this.getRectAnchoredJpgImages(Name, frontRepo)
  }
  getRectAnchoredJpgImages(Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI[]> {

    let params = new HttpParams().set("Name", Name)

    return this.http.get<RectAnchoredJpgImageAPI[]>(this.rectanchoredjpgimagesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<RectAnchoredJpgImageAPI[]>('getRectAnchoredJpgImages', []))
      );
  }

  /** GET rectanchoredjpgimage by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI> {
    return this.getRectAnchoredJpgImage(id, Name, frontRepo)
  }
  getRectAnchoredJpgImage(id: number, Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI> {

    let params = new HttpParams().set("Name", Name)

    const url = `${this.rectanchoredjpgimagesUrl}/${id}`;
    return this.http.get<RectAnchoredJpgImageAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched rectanchoredjpgimage id=${id}`)),
      catchError(this.handleError<RectAnchoredJpgImageAPI>(`getRectAnchoredJpgImage id=${id}`))
    );
  }

  // postFront copy rectanchoredjpgimage to a version with encoded pointers and post to the back
  postFront(rectanchoredjpgimage: RectAnchoredJpgImage, Name: string): Observable<RectAnchoredJpgImageAPI> {
    let rectanchoredjpgimageAPI = new RectAnchoredJpgImageAPI
    CopyRectAnchoredJpgImageToRectAnchoredJpgImageAPI(rectanchoredjpgimage, rectanchoredjpgimageAPI)
    const id = typeof rectanchoredjpgimageAPI === 'number' ? rectanchoredjpgimageAPI : rectanchoredjpgimageAPI.ID
    const url = `${this.rectanchoredjpgimagesUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<RectAnchoredJpgImageAPI>(url, rectanchoredjpgimageAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<RectAnchoredJpgImageAPI>('postRectAnchoredJpgImage'))
    );
  }

  /** POST: add a new rectanchoredjpgimage to the server */
  post(rectanchoredjpgimagedb: RectAnchoredJpgImageAPI, Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI> {
    return this.postRectAnchoredJpgImage(rectanchoredjpgimagedb, Name, frontRepo)
  }
  postRectAnchoredJpgImage(rectanchoredjpgimagedb: RectAnchoredJpgImageAPI, Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI> {

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<RectAnchoredJpgImageAPI>(this.rectanchoredjpgimagesUrl, rectanchoredjpgimagedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted rectanchoredjpgimagedb id=${rectanchoredjpgimagedb.ID}`)
      }),
      catchError(this.handleError<RectAnchoredJpgImageAPI>('postRectAnchoredJpgImage'))
    );
  }

  /** DELETE: delete the rectanchoredjpgimagedb from the server */
  delete(rectanchoredjpgimagedb: RectAnchoredJpgImageAPI | number, Name: string): Observable<RectAnchoredJpgImageAPI> {
    return this.deleteRectAnchoredJpgImage(rectanchoredjpgimagedb, Name)
  }
  deleteRectAnchoredJpgImage(rectanchoredjpgimagedb: RectAnchoredJpgImageAPI | number, Name: string): Observable<RectAnchoredJpgImageAPI> {
    const id = typeof rectanchoredjpgimagedb === 'number' ? rectanchoredjpgimagedb : rectanchoredjpgimagedb.ID;
    const url = `${this.rectanchoredjpgimagesUrl}/${id}`;

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<RectAnchoredJpgImageAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted rectanchoredjpgimagedb id=${id}`)),
      catchError(this.handleError<RectAnchoredJpgImageAPI>('deleteRectAnchoredJpgImage'))
    );
  }

  // updateFront copy rectanchoredjpgimage to a version with encoded pointers and update to the back
  updateFront(rectanchoredjpgimage: RectAnchoredJpgImage, Name: string): Observable<RectAnchoredJpgImageAPI> {
    let rectanchoredjpgimageAPI = new RectAnchoredJpgImageAPI
    CopyRectAnchoredJpgImageToRectAnchoredJpgImageAPI(rectanchoredjpgimage, rectanchoredjpgimageAPI)
    const id = typeof rectanchoredjpgimageAPI === 'number' ? rectanchoredjpgimageAPI : rectanchoredjpgimageAPI.ID
    const url = `${this.rectanchoredjpgimagesUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<RectAnchoredJpgImageAPI>(url, rectanchoredjpgimageAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<RectAnchoredJpgImageAPI>('updateRectAnchoredJpgImage'))
    );
  }

  /** PUT: update the rectanchoredjpgimagedb on the server */
  update(rectanchoredjpgimagedb: RectAnchoredJpgImageAPI, Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI> {
    return this.updateRectAnchoredJpgImage(rectanchoredjpgimagedb, Name, frontRepo)
  }
  updateRectAnchoredJpgImage(rectanchoredjpgimagedb: RectAnchoredJpgImageAPI, Name: string, frontRepo: FrontRepo): Observable<RectAnchoredJpgImageAPI> {
    const id = typeof rectanchoredjpgimagedb === 'number' ? rectanchoredjpgimagedb : rectanchoredjpgimagedb.ID;
    const url = `${this.rectanchoredjpgimagesUrl}/${id}`;


    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<RectAnchoredJpgImageAPI>(url, rectanchoredjpgimagedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated rectanchoredjpgimagedb id=${rectanchoredjpgimagedb.ID}`)
      }),
      catchError(this.handleError<RectAnchoredJpgImageAPI>('updateRectAnchoredJpgImage'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in RectAnchoredJpgImageService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging
      console.error("RectAnchoredJpgImageService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
