// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { FileToUploadAPI } from './filetoupload-api'
import { FileToUpload, CopyFileToUploadToFileToUploadAPI } from './filetoupload'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class FileToUploadService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  FileToUploadServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private filetouploadsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.filetouploadsUrl = origin + '/api/github.com/fullstack-lang/gong/lib/load/go/v1/filetouploads';
  }

  /** GET filetouploads from the server */
  // gets is more robust to refactoring
  gets(Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI[]> {
    return this.getFileToUploads(Name, frontRepo)
  }
  getFileToUploads(Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI[]> {

    let params = new HttpParams().set("Name", Name)

    return this.http.get<FileToUploadAPI[]>(this.filetouploadsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<FileToUploadAPI[]>('getFileToUploads', []))
      );
  }

  /** GET filetoupload by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI> {
    return this.getFileToUpload(id, Name, frontRepo)
  }
  getFileToUpload(id: number, Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI> {

    let params = new HttpParams().set("Name", Name)

    const url = `${this.filetouploadsUrl}/${id}`;
    return this.http.get<FileToUploadAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched filetoupload id=${id}`)),
      catchError(this.handleError<FileToUploadAPI>(`getFileToUpload id=${id}`))
    );
  }

  // postFront copy filetoupload to a version with encoded pointers and post to the back
  postFront(filetoupload: FileToUpload, Name: string): Observable<FileToUploadAPI> {
    let filetouploadAPI = new FileToUploadAPI
    CopyFileToUploadToFileToUploadAPI(filetoupload, filetouploadAPI)
    const id = typeof filetouploadAPI === 'number' ? filetouploadAPI : filetouploadAPI.ID
    const url = `${this.filetouploadsUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FileToUploadAPI>(url, filetouploadAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<FileToUploadAPI>('postFileToUpload'))
    );
  }
  
  /** POST: add a new filetoupload to the server */
  post(filetouploaddb: FileToUploadAPI, Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI> {
    return this.postFileToUpload(filetouploaddb, Name, frontRepo)
  }
  postFileToUpload(filetouploaddb: FileToUploadAPI, Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI> {

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<FileToUploadAPI>(this.filetouploadsUrl, filetouploaddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted filetouploaddb id=${filetouploaddb.ID}`)
      }),
      catchError(this.handleError<FileToUploadAPI>('postFileToUpload'))
    );
  }

  /** DELETE: delete the filetouploaddb from the server */
  delete(filetouploaddb: FileToUploadAPI | number, Name: string): Observable<FileToUploadAPI> {
    return this.deleteFileToUpload(filetouploaddb, Name)
  }
  deleteFileToUpload(filetouploaddb: FileToUploadAPI | number, Name: string): Observable<FileToUploadAPI> {
    const id = typeof filetouploaddb === 'number' ? filetouploaddb : filetouploaddb.ID;
    const url = `${this.filetouploadsUrl}/${id}`;

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<FileToUploadAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted filetouploaddb id=${id}`)),
      catchError(this.handleError<FileToUploadAPI>('deleteFileToUpload'))
    );
  }

  // updateFront copy filetoupload to a version with encoded pointers and update to the back
  updateFront(filetoupload: FileToUpload, Name: string): Observable<FileToUploadAPI> {
    let filetouploadAPI = new FileToUploadAPI
    CopyFileToUploadToFileToUploadAPI(filetoupload, filetouploadAPI)
    const id = typeof filetouploadAPI === 'number' ? filetouploadAPI : filetouploadAPI.ID
    const url = `${this.filetouploadsUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<FileToUploadAPI>(url, filetouploadAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<FileToUploadAPI>('updateFileToUpload'))
    );
  }

  /** PUT: update the filetouploaddb on the server */
  update(filetouploaddb: FileToUploadAPI, Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI> {
    return this.updateFileToUpload(filetouploaddb, Name, frontRepo)
  }
  updateFileToUpload(filetouploaddb: FileToUploadAPI, Name: string, frontRepo: FrontRepo): Observable<FileToUploadAPI> {
    const id = typeof filetouploaddb === 'number' ? filetouploaddb : filetouploaddb.ID;
    const url = `${this.filetouploadsUrl}/${id}`;


    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<FileToUploadAPI>(url, filetouploaddb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated filetouploaddb id=${filetouploaddb.ID}`)
      }),
      catchError(this.handleError<FileToUploadAPI>('updateFileToUpload'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in FileToUploadService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("FileToUploadService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
