// file generated by gong
package main

import (
	"slices"
	"time"

	__stage_0__ "github.com/fullstack-lang/gong/dsm/process/go/models"
)

var (
	_ time.Time
	_ = slices.Index[[]int, int]

	_ *__stage_0__.Stage
)

// function will stage objects across all coordinated stages
func _(stageSet *__stage_0__.StageSet) {

	// ------------------------------------------------------------------------
	// Phase 1: Declarations (in topological order: leaves first)
	// ------------------------------------------------------------------------
	__stage_0__Data__00000000_ := (&__stage_0__.Data{Name: `D1`}).Stage(stageSet.Stage)
	__stage_0__DataFlow__00000000_ := (&__stage_0__.DataFlow{Name: `"T1" to "T2"`}).Stage(stageSet.Stage)
	__stage_0__DataFlowShape__00000000_ := (&__stage_0__.DataFlowShape{Name: `"T1" to "T2"`}).Stage(stageSet.Stage)
	__stage_0__DataShape__00000000_ := (&__stage_0__.DataShape{Name: `D1`}).Stage(stageSet.Stage)
	__stage_0__DiagramProcess__00000000_ := (&__stage_0__.DiagramProcess{Name: `P1`}).Stage(stageSet.Stage)
	__stage_0__Library__00000000_ := (&__stage_0__.Library{Name: `issue 1427`}).Stage(stageSet.Stage)
	__stage_0__Note__00000000_ := (&__stage_0__.Note{Name: `AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA`}).Stage(stageSet.Stage)
	__stage_0__NoteShape__00000000_ := (&__stage_0__.NoteShape{Name: `AAA AAA AAA shape`}).Stage(stageSet.Stage)
	__stage_0__Participant__00000000_ := (&__stage_0__.Participant{Name: `Pa 1`}).Stage(stageSet.Stage)
	__stage_0__Participant__00000001_ := (&__stage_0__.Participant{Name: `Pa2`}).Stage(stageSet.Stage)
	__stage_0__Participant__00000002_ := (&__stage_0__.Participant{Name: `P5`}).Stage(stageSet.Stage)
	__stage_0__ParticipantShape__00000000_ := (&__stage_0__.ParticipantShape{Name: `Pa 1-P1`}).Stage(stageSet.Stage)
	__stage_0__ParticipantShape__00000001_ := (&__stage_0__.ParticipantShape{Name: `Pa2-P1`}).Stage(stageSet.Stage)
	__stage_0__ParticipantShape__00000002_ := (&__stage_0__.ParticipantShape{Name: `-P1`}).Stage(stageSet.Stage)
	__stage_0__Process__00000000_ := (&__stage_0__.Process{Name: `P1`}).Stage(stageSet.Stage)
	__stage_0__ProcessShape__00000000_ := (&__stage_0__.ProcessShape{Name: `ProcessShape`}).Stage(stageSet.Stage)
	__stage_0__Task__00000000_ := (&__stage_0__.Task{Name: `T1`}).Stage(stageSet.Stage)
	__stage_0__Task__00000001_ := (&__stage_0__.Task{Name: `T2`}).Stage(stageSet.Stage)
	__stage_0__TaskShape__00000000_ := (&__stage_0__.TaskShape{Name: `-P1`}).Stage(stageSet.Stage)
	__stage_0__TaskShape__00000001_ := (&__stage_0__.TaskShape{Name: `-P1`}).Stage(stageSet.Stage)

	// ------------------------------------------------------------------------
	// Phase 2: Value Initializations
	// ------------------------------------------------------------------------
	__stage_0__Data__00000000_.Name = `D1`
	__stage_0__Data__00000000_.Acronym = ``
	__stage_0__Data__00000000_.Description = ``
	__stage_0__Data__00000000_.ComputedPrefix = ``
	__stage_0__Data__00000000_.IsExpanded = false
	__stage_0__Data__00000000_.SVG_Path = ``
	__stage_0__Data__00000000_.InverseAppliedScaling = 0.000000
	__stage_0__DataFlow__00000000_.Name = `"T1" to "T2"`
	__stage_0__DataFlow__00000000_.Description = ``
	__stage_0__DataFlow__00000000_.ComputedPrefix = ``
	__stage_0__DataFlow__00000000_.IsExpanded = false
	__stage_0__DataFlow__00000000_.Type = __stage_0__.DataFlow_Task2Task
	__stage_0__DataFlow__00000000_.IsDatasNodeExpanded = false
	__stage_0__DataFlowShape__00000000_.Name = `"T1" to "T2"`
	__stage_0__DataFlowShape__00000000_.StartRatio = 0.514410
	__stage_0__DataFlowShape__00000000_.EndRatio = 0.484404
	__stage_0__DataFlowShape__00000000_.StartOrientation = __stage_0__.ORIENTATION_HORIZONTAL
	__stage_0__DataFlowShape__00000000_.EndOrientation = __stage_0__.ORIENTATION_VERTICAL
	__stage_0__DataFlowShape__00000000_.CornerOffsetRatio = 1.518017
	__stage_0__DataFlowShape__00000000_.IsHidden = false
	__stage_0__DataShape__00000000_.Name = `D1`
	__stage_0__DiagramProcess__00000000_.Name = `P1`
	__stage_0__DiagramProcess__00000000_.Description = ``
	__stage_0__DiagramProcess__00000000_.ComputedPrefix = ``
	__stage_0__DiagramProcess__00000000_.IsExpanded = false
	__stage_0__DiagramProcess__00000000_.IsChecked = true
	__stage_0__DiagramProcess__00000000_.IsEditable_ = true
	__stage_0__DiagramProcess__00000000_.IsShowPrefix = false
	__stage_0__DiagramProcess__00000000_.DefaultBoxWidth = 250.000000
	__stage_0__DiagramProcess__00000000_.DefaultBoxHeigth = 70.000000
	__stage_0__DiagramProcess__00000000_.Width = 1214.287589
	__stage_0__DiagramProcess__00000000_.Height = 1350.000000
	__stage_0__DiagramProcess__00000000_.IsProcesssNodeExpanded = false
	__stage_0__DiagramProcess__00000000_.IsParticipantsNodeExpanded = true
	__stage_0__DiagramProcess__00000000_.IsExternalParticipantsNodeExpanded = false
	__stage_0__DiagramProcess__00000000_.IsNotesNodeExpanded = true
	__stage_0__Library__00000000_.Name = `issue 1427`
	__stage_0__Library__00000000_.Description = ``
	__stage_0__Library__00000000_.ComputedPrefix = ``
	__stage_0__Library__00000000_.IsExpanded = false
	__stage_0__Library__00000000_.IsRootLibrary = true
	__stage_0__Library__00000000_.IsSubLibrariesNodeExpanded = false
	__stage_0__Library__00000000_.NbPixPerCharacter = 9.000000
	__stage_0__Library__00000000_.LogoSVGFile = ``
	__stage_0__Library__00000000_.IsProcessesNodeExpanded = true
	__stage_0__Library__00000000_.IsDataFlowsNodeExpanded = true
	__stage_0__Library__00000000_.IsDatasNodeExpanded = true
	__stage_0__Library__00000000_.IsResourcesNodeExpanded = false
	__stage_0__Library__00000000_.IsNotesNodeExpanded = false
	__stage_0__Library__00000000_.IsExpandedTmp = true
	__stage_0__Note__00000000_.Name = `AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA AAA`
	__stage_0__Note__00000000_.Description = ``
	__stage_0__Note__00000000_.ComputedPrefix = ``
	__stage_0__Note__00000000_.IsExpanded = false
	__stage_0__Note__00000000_.IsTasksNodeExpanded = false
	__stage_0__NoteShape__00000000_.Name = `AAA AAA AAA shape`
	__stage_0__NoteShape__00000000_.X = 664.287589
	__stage_0__NoteShape__00000000_.Y = 299.881547
	__stage_0__NoteShape__00000000_.Width = 250.000000
	__stage_0__NoteShape__00000000_.Height = 70.000000
	__stage_0__NoteShape__00000000_.IsHidden = false
	__stage_0__Participant__00000000_.Name = `Pa 1`
	__stage_0__Participant__00000000_.IsProcessResource = false
	__stage_0__Participant__00000000_.Description = ``
	__stage_0__Participant__00000000_.IsResourcesNodeExpanded = false
	__stage_0__Participant__00000000_.IsProcessesNodeExpanded = false
	__stage_0__Participant__00000000_.ComputedPrefix = ``
	__stage_0__Participant__00000000_.IsExpanded = false
	__stage_0__Participant__00000000_.IsTasksNodeExpanded = true
	__stage_0__Participant__00000000_.IsControlFlowsNodeExpanded = false
	__stage_0__Participant__00000000_.IsDataFlowsNodeExpanded = false
	__stage_0__Participant__00000001_.Name = `Pa2`
	__stage_0__Participant__00000001_.IsProcessResource = false
	__stage_0__Participant__00000001_.Description = ``
	__stage_0__Participant__00000001_.IsResourcesNodeExpanded = false
	__stage_0__Participant__00000001_.IsProcessesNodeExpanded = false
	__stage_0__Participant__00000001_.ComputedPrefix = ``
	__stage_0__Participant__00000001_.IsExpanded = false
	__stage_0__Participant__00000001_.IsTasksNodeExpanded = true
	__stage_0__Participant__00000001_.IsControlFlowsNodeExpanded = false
	__stage_0__Participant__00000001_.IsDataFlowsNodeExpanded = false
	__stage_0__Participant__00000002_.Name = `P5`
	__stage_0__Participant__00000002_.IsProcessResource = false
	__stage_0__Participant__00000002_.Description = ``
	__stage_0__Participant__00000002_.IsResourcesNodeExpanded = false
	__stage_0__Participant__00000002_.IsProcessesNodeExpanded = false
	__stage_0__Participant__00000002_.ComputedPrefix = ``
	__stage_0__Participant__00000002_.IsExpanded = false
	__stage_0__Participant__00000002_.IsTasksNodeExpanded = false
	__stage_0__Participant__00000002_.IsControlFlowsNodeExpanded = false
	__stage_0__Participant__00000002_.IsDataFlowsNodeExpanded = false
	__stage_0__ParticipantShape__00000000_.Name = `Pa 1-P1`
	__stage_0__ParticipantShape__00000000_.IsExpanded = false
	__stage_0__ParticipantShape__00000000_.X = 126.467794
	__stage_0__ParticipantShape__00000000_.Y = 786.000000
	__stage_0__ParticipantShape__00000000_.Width = 250.000000
	__stage_0__ParticipantShape__00000000_.Height = 70.000000
	__stage_0__ParticipantShape__00000000_.IsHidden = false
	__stage_0__ParticipantShape__00000000_.WidthWeight = 1.000000
	__stage_0__ParticipantShape__00000001_.Name = `Pa2-P1`
	__stage_0__ParticipantShape__00000001_.IsExpanded = false
	__stage_0__ParticipantShape__00000001_.X = 174.975623
	__stage_0__ParticipantShape__00000001_.Y = 830.000000
	__stage_0__ParticipantShape__00000001_.Width = 250.000000
	__stage_0__ParticipantShape__00000001_.Height = 70.000000
	__stage_0__ParticipantShape__00000001_.IsHidden = false
	__stage_0__ParticipantShape__00000001_.WidthWeight = 1.000000
	__stage_0__ParticipantShape__00000002_.Name = `-P1`
	__stage_0__ParticipantShape__00000002_.IsExpanded = false
	__stage_0__ParticipantShape__00000002_.X = 172.319830
	__stage_0__ParticipantShape__00000002_.Y = 373.000000
	__stage_0__ParticipantShape__00000002_.Width = 250.000000
	__stage_0__ParticipantShape__00000002_.Height = 70.000000
	__stage_0__ParticipantShape__00000002_.IsHidden = false
	__stage_0__ParticipantShape__00000002_.WidthWeight = 1.000000
	__stage_0__Process__00000000_.Name = `P1`
	__stage_0__Process__00000000_.Description = ``
	__stage_0__Process__00000000_.ComputedPrefix = ``
	__stage_0__Process__00000000_.IsExpanded = false
	__stage_0__Process__00000000_.SVG_Path = ``
	__stage_0__Process__00000000_.InverseAppliedScaling = 0.000000
	__stage_0__Process__00000000_.IsSubProcessNodeExpanded = false
	__stage_0__Process__00000000_.IsDataFlowsNodeExpanded = true
	__stage_0__ProcessShape__00000000_.Name = `ProcessShape`
	__stage_0__ProcessShape__00000000_.IsExpanded = false
	__stage_0__ProcessShape__00000000_.X = 100.000000
	__stage_0__ProcessShape__00000000_.Y = 50.000000
	__stage_0__ProcessShape__00000000_.Width = 713.000000
	__stage_0__ProcessShape__00000000_.Height = 1000.000000
	__stage_0__ProcessShape__00000000_.IsHidden = false
	__stage_0__Task__00000000_.Name = `T1`
	__stage_0__Task__00000000_.Description = ``
	__stage_0__Task__00000000_.ComputedPrefix = ``
	__stage_0__Task__00000000_.IsExpanded = false
	__stage_0__Task__00000000_.IsStartTask = false
	__stage_0__Task__00000000_.IsEndTask = false
	__stage_0__Task__00000000_.IsTaskNameNotProcessName = false
	__stage_0__Task__00000001_.Name = `T2`
	__stage_0__Task__00000001_.Description = ``
	__stage_0__Task__00000001_.ComputedPrefix = ``
	__stage_0__Task__00000001_.IsExpanded = false
	__stage_0__Task__00000001_.IsStartTask = false
	__stage_0__Task__00000001_.IsEndTask = false
	__stage_0__Task__00000001_.IsTaskNameNotProcessName = false
	__stage_0__TaskShape__00000000_.Name = `-P1`
	__stage_0__TaskShape__00000000_.IsExpanded = false
	__stage_0__TaskShape__00000000_.X = 111.000000
	__stage_0__TaskShape__00000000_.Y = 437.000000
	__stage_0__TaskShape__00000000_.Width = 164.000000
	__stage_0__TaskShape__00000000_.Height = 70.000000
	__stage_0__TaskShape__00000000_.IsHidden = false
	__stage_0__TaskShape__00000001_.Name = `-P1`
	__stage_0__TaskShape__00000001_.IsExpanded = false
	__stage_0__TaskShape__00000001_.X = 404.000000
	__stage_0__TaskShape__00000001_.Y = 617.000000
	__stage_0__TaskShape__00000001_.Width = 167.000000
	__stage_0__TaskShape__00000001_.Height = 70.000000
	__stage_0__TaskShape__00000001_.IsHidden = false

	// ------------------------------------------------------------------------
	// Phase 3: Pointer Setups (Intra-stage and Cross-stage pointers)
	// ------------------------------------------------------------------------
	__stage_0__DataFlow__00000000_.Datas = append(__stage_0__DataFlow__00000000_.Datas, __stage_0__Data__00000000_)
	__stage_0__DataFlow__00000000_.StartTask = __stage_0__Task__00000000_
	__stage_0__DataFlow__00000000_.EndTask = __stage_0__Task__00000001_
	__stage_0__DataFlow__00000000_.StartExternalParticipant = nil
	__stage_0__DataFlow__00000000_.EndExternalParticipant = nil
	__stage_0__DataFlowShape__00000000_.DataFlow = __stage_0__DataFlow__00000000_
	__stage_0__DataShape__00000000_.Data = __stage_0__Data__00000000_
	__stage_0__DataShape__00000000_.DataFlow = __stage_0__DataFlow__00000000_
	__stage_0__DiagramProcess__00000000_.Process_Shapes = append(__stage_0__DiagramProcess__00000000_.Process_Shapes, __stage_0__ProcessShape__00000000_)
	__stage_0__DiagramProcess__00000000_.Participant_Shapes = append(__stage_0__DiagramProcess__00000000_.Participant_Shapes, __stage_0__ParticipantShape__00000000_)
	__stage_0__DiagramProcess__00000000_.Participant_Shapes = append(__stage_0__DiagramProcess__00000000_.Participant_Shapes, __stage_0__ParticipantShape__00000001_)
	__stage_0__DiagramProcess__00000000_.Participant_Shapes = append(__stage_0__DiagramProcess__00000000_.Participant_Shapes, __stage_0__ParticipantShape__00000002_)
	__stage_0__DiagramProcess__00000000_.Task_Shapes = append(__stage_0__DiagramProcess__00000000_.Task_Shapes, __stage_0__TaskShape__00000000_)
	__stage_0__DiagramProcess__00000000_.Task_Shapes = append(__stage_0__DiagramProcess__00000000_.Task_Shapes, __stage_0__TaskShape__00000001_)
	__stage_0__DiagramProcess__00000000_.DataFlow_Shapes = append(__stage_0__DiagramProcess__00000000_.DataFlow_Shapes, __stage_0__DataFlowShape__00000000_)
	__stage_0__DiagramProcess__00000000_.Data_Shapes = append(__stage_0__DiagramProcess__00000000_.Data_Shapes, __stage_0__DataShape__00000000_)
	__stage_0__DiagramProcess__00000000_.Note_Shapes = append(__stage_0__DiagramProcess__00000000_.Note_Shapes, __stage_0__NoteShape__00000000_)
	__stage_0__Library__00000000_.RootProcesses = append(__stage_0__Library__00000000_.RootProcesses, __stage_0__Process__00000000_)
	__stage_0__Library__00000000_.ProcesssWhoseNodeIsExpanded = append(__stage_0__Library__00000000_.ProcesssWhoseNodeIsExpanded, __stage_0__Process__00000000_)
	__stage_0__Library__00000000_.RootDataFlows = append(__stage_0__Library__00000000_.RootDataFlows, __stage_0__DataFlow__00000000_)
	__stage_0__Library__00000000_.RootDatas = append(__stage_0__Library__00000000_.RootDatas, __stage_0__Data__00000000_)
	__stage_0__Library__00000000_.RootNotes = append(__stage_0__Library__00000000_.RootNotes, __stage_0__Note__00000000_)
	__stage_0__NoteShape__00000000_.Note = __stage_0__Note__00000000_
	__stage_0__Participant__00000000_.Tasks = append(__stage_0__Participant__00000000_.Tasks, __stage_0__Task__00000000_)
	__stage_0__Participant__00000001_.Tasks = append(__stage_0__Participant__00000001_.Tasks, __stage_0__Task__00000001_)
	__stage_0__ParticipantShape__00000000_.Participant = __stage_0__Participant__00000000_
	__stage_0__ParticipantShape__00000001_.Participant = __stage_0__Participant__00000001_
	__stage_0__ParticipantShape__00000002_.Participant = __stage_0__Participant__00000002_
	__stage_0__Process__00000000_.DiagramProcesss = append(__stage_0__Process__00000000_.DiagramProcesss, __stage_0__DiagramProcess__00000000_)
	__stage_0__Process__00000000_.DiagramProcessWhoseNodeIsExpanded = append(__stage_0__Process__00000000_.DiagramProcessWhoseNodeIsExpanded, __stage_0__DiagramProcess__00000000_)
	__stage_0__Process__00000000_.Participants = append(__stage_0__Process__00000000_.Participants, __stage_0__Participant__00000000_)
	__stage_0__Process__00000000_.Participants = append(__stage_0__Process__00000000_.Participants, __stage_0__Participant__00000001_)
	__stage_0__Process__00000000_.Participants = append(__stage_0__Process__00000000_.Participants, __stage_0__Participant__00000002_)
	__stage_0__Process__00000000_.DataFlows = append(__stage_0__Process__00000000_.DataFlows, __stage_0__DataFlow__00000000_)
	__stage_0__ProcessShape__00000000_.Process = __stage_0__Process__00000000_
	__stage_0__Task__00000000_.Type = nil
	__stage_0__Task__00000001_.Type = nil
	__stage_0__TaskShape__00000000_.Task = __stage_0__Task__00000000_
	__stage_0__TaskShape__00000001_.Task = __stage_0__Task__00000001_
}
