package models

import (
	"strings"
	"testing"
)

func TestStageSetMarshallVersionComment(t *testing.T) {
	stageSet := NewStageSet("test")
	res, err := stageSet.MarshallToString("main")
	if err != nil {
		t.Fatalf("MarshallToString failed: %v", err)
	}

	expectedPrefix := "// file generated by gong\n// go module version: "
	if !strings.HasPrefix(res, expectedPrefix) {
		t.Errorf("expected res to start with %q, but got:\n%s", expectedPrefix, res[:min(len(res), 150)])
	}

	expectedProbeComment := "/* to edit this file with the default probe, use the command\ngo run github.com/fullstack-lang/gong/dsm/project/go/models/probe/cmd/probe@"
	if !strings.Contains(res, expectedProbeComment) {
		t.Errorf("expected res to contain %q, but got:\n%s", expectedProbeComment, res[:min(len(res), 250)])
	}

	expectedPackage := "stage.go\n*/\npackage main\n"
	if !strings.Contains(res, expectedPackage) {
		t.Errorf("expected res to contain %q, but got:\n%s", expectedPackage, res[:min(len(res), 250)])
	}

	// Verify unmarshalling works seamlessly with the version and probe comment header
	stageSet2 := NewStageSet("test2")
	if err := stageSet2.ParseAstString(res, true); err != nil {
		t.Fatalf("ParseAstString failed with header comments: %v", err)
	}
}
