// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { LogoAPI } from './logo-api'
import { Logo, CopyLogoToLogoAPI } from './logo'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class LogoService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  LogoServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private logosUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.logosUrl = origin + '/api/github.com/fullstack-lang/gong/lib/split/go/v1/logos';
  }

  /** GET logos from the server */
  // gets is more robust to refactoring
  gets(Name: string, frontRepo: FrontRepo): Observable<LogoAPI[]> {
    return this.getLogos(Name, frontRepo)
  }
  getLogos(Name: string, frontRepo: FrontRepo): Observable<LogoAPI[]> {

    let params = new HttpParams().set("Name", Name)

    return this.http.get<LogoAPI[]>(this.logosUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<LogoAPI[]>('getLogos', []))
      );
  }

  /** GET logo by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, Name: string, frontRepo: FrontRepo): Observable<LogoAPI> {
    return this.getLogo(id, Name, frontRepo)
  }
  getLogo(id: number, Name: string, frontRepo: FrontRepo): Observable<LogoAPI> {

    let params = new HttpParams().set("Name", Name)

    const url = `${this.logosUrl}/${id}`;
    return this.http.get<LogoAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched logo id=${id}`)),
      catchError(this.handleError<LogoAPI>(`getLogo id=${id}`))
    );
  }

  // postFront copy logo to a version with encoded pointers and post to the back
  postFront(logo: Logo, Name: string): Observable<LogoAPI> {
    let logoAPI = new LogoAPI
    CopyLogoToLogoAPI(logo, logoAPI)
    const id = typeof logoAPI === 'number' ? logoAPI : logoAPI.ID
    const url = `${this.logosUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<LogoAPI>(url, logoAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<LogoAPI>('postLogo'))
    );
  }
  
  /** POST: add a new logo to the server */
  post(logodb: LogoAPI, Name: string, frontRepo: FrontRepo): Observable<LogoAPI> {
    return this.postLogo(logodb, Name, frontRepo)
  }
  postLogo(logodb: LogoAPI, Name: string, frontRepo: FrontRepo): Observable<LogoAPI> {

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<LogoAPI>(this.logosUrl, logodb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted logodb id=${logodb.ID}`)
      }),
      catchError(this.handleError<LogoAPI>('postLogo'))
    );
  }

  /** DELETE: delete the logodb from the server */
  delete(logodb: LogoAPI | number, Name: string): Observable<LogoAPI> {
    return this.deleteLogo(logodb, Name)
  }
  deleteLogo(logodb: LogoAPI | number, Name: string): Observable<LogoAPI> {
    const id = typeof logodb === 'number' ? logodb : logodb.ID;
    const url = `${this.logosUrl}/${id}`;

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<LogoAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted logodb id=${id}`)),
      catchError(this.handleError<LogoAPI>('deleteLogo'))
    );
  }

  // updateFront copy logo to a version with encoded pointers and update to the back
  updateFront(logo: Logo, Name: string): Observable<LogoAPI> {
    let logoAPI = new LogoAPI
    CopyLogoToLogoAPI(logo, logoAPI)
    const id = typeof logoAPI === 'number' ? logoAPI : logoAPI.ID
    const url = `${this.logosUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<LogoAPI>(url, logoAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<LogoAPI>('updateLogo'))
    );
  }

  /** PUT: update the logodb on the server */
  update(logodb: LogoAPI, Name: string, frontRepo: FrontRepo): Observable<LogoAPI> {
    return this.updateLogo(logodb, Name, frontRepo)
  }
  updateLogo(logodb: LogoAPI, Name: string, frontRepo: FrontRepo): Observable<LogoAPI> {
    const id = typeof logodb === 'number' ? logodb : logodb.ID;
    const url = `${this.logosUrl}/${id}`;


    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<LogoAPI>(url, logodb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated logodb id=${logodb.ID}`)
      }),
      catchError(this.handleError<LogoAPI>('updateLogo'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in LogoService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("LogoService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
