// generated by ng_file_service_ts
import { Injectable, Component, Inject, DOCUMENT } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Location } from '@angular/common'
/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { ThreejsAPI } from './threejs-api'
import { Threejs, CopyThreejsToThreejsAPI } from './threejs'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class ThreejsService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ThreejsServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private threejssUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.threejssUrl = origin + '/api/github.com/fullstack-lang/gong/lib/split/go/v1/threejss';
  }

  /** GET threejss from the server */
  // gets is more robust to refactoring
  gets(Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI[]> {
    return this.getThreejss(Name, frontRepo)
  }
  getThreejss(Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI[]> {

    let params = new HttpParams().set("Name", Name)

    return this.http.get<ThreejsAPI[]>(this.threejssUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<ThreejsAPI[]>('getThreejss', []))
      );
  }

  /** GET threejs by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI> {
    return this.getThreejs(id, Name, frontRepo)
  }
  getThreejs(id: number, Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI> {

    let params = new HttpParams().set("Name", Name)

    const url = `${this.threejssUrl}/${id}`;
    return this.http.get<ThreejsAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched threejs id=${id}`)),
      catchError(this.handleError<ThreejsAPI>(`getThreejs id=${id}`))
    );
  }

  // postFront copy threejs to a version with encoded pointers and post to the back
  postFront(threejs: Threejs, Name: string): Observable<ThreejsAPI> {
    let threejsAPI = new ThreejsAPI
    CopyThreejsToThreejsAPI(threejs, threejsAPI)
    const id = typeof threejsAPI === 'number' ? threejsAPI : threejsAPI.ID
    const url = `${this.threejssUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ThreejsAPI>(url, threejsAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ThreejsAPI>('postThreejs'))
    );
  }

  /** POST: add a new threejs to the server */
  post(threejsdb: ThreejsAPI, Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI> {
    return this.postThreejs(threejsdb, Name, frontRepo)
  }
  postThreejs(threejsdb: ThreejsAPI, Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI> {

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ThreejsAPI>(this.threejssUrl, threejsdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted threejsdb id=${threejsdb.ID}`)
      }),
      catchError(this.handleError<ThreejsAPI>('postThreejs'))
    );
  }

  /** DELETE: delete the threejsdb from the server */
  delete(threejsdb: ThreejsAPI | number, Name: string): Observable<ThreejsAPI> {
    return this.deleteThreejs(threejsdb, Name)
  }
  deleteThreejs(threejsdb: ThreejsAPI | number, Name: string): Observable<ThreejsAPI> {
    const id = typeof threejsdb === 'number' ? threejsdb : threejsdb.ID;
    const url = `${this.threejssUrl}/${id}`;

    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ThreejsAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted threejsdb id=${id}`)),
      catchError(this.handleError<ThreejsAPI>('deleteThreejs'))
    );
  }

  // updateFront copy threejs to a version with encoded pointers and update to the back
  updateFront(threejs: Threejs, Name: string): Observable<ThreejsAPI> {
    let threejsAPI = new ThreejsAPI
    CopyThreejsToThreejsAPI(threejs, threejsAPI)
    const id = typeof threejsAPI === 'number' ? threejsAPI : threejsAPI.ID
    const url = `${this.threejssUrl}/${id}`;
    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<ThreejsAPI>(url, threejsAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ThreejsAPI>('updateThreejs'))
    );
  }

  /** PUT: update the threejsdb on the server */
  update(threejsdb: ThreejsAPI, Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI> {
    return this.updateThreejs(threejsdb, Name, frontRepo)
  }
  updateThreejs(threejsdb: ThreejsAPI, Name: string, frontRepo: FrontRepo): Observable<ThreejsAPI> {
    const id = typeof threejsdb === 'number' ? threejsdb : threejsdb.ID;
    const url = `${this.threejssUrl}/${id}`;


    let params = new HttpParams().set("Name", Name)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ThreejsAPI>(url, threejsdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated threejsdb id=${threejsdb.ID}`)
      }),
      catchError(this.handleError<ThreejsAPI>('updateThreejs'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ThreejsService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging
      console.error("ThreejsService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
