// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gong/lib/threejs/go/db"
	"github.com/fullstack-lang/gong/lib/threejs/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Vector3_sql sql.NullBool
var _ = dummy_Vector3_sql
var dummy_Vector3_time time.Duration
var _ = dummy_Vector3_time
var dummy_Vector3_sort sort.Float64Slice
var _ = dummy_Vector3_sort

// Vector3API is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model vector3API
type Vector3API struct {
	gorm.Model

	models.Vector3_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Vector3PointersEncoding Vector3PointersEncoding
}

// Vector3PointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Vector3PointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Vector3DB describes a vector3 in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model vector3DB
type Vector3DB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field vector3DB.Name
	Name_Data sql.NullString

	// Declation for basic field vector3DB.X
	X_Data sql.NullFloat64

	// Declation for basic field vector3DB.Y
	Y_Data sql.NullFloat64

	// Declation for basic field vector3DB.Z
	Z_Data sql.NullFloat64

	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Vector3PointersEncoding
}

// Vector3DBs arrays vector3DBs
// swagger:response vector3DBsResponse
type Vector3DBs []Vector3DB

// Vector3DBResponse provides response
// swagger:response vector3DBResponse
type Vector3DBResponse struct {
	Vector3DB
}

// Vector3WOP is a Vector3 without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Vector3WOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	X float64 `xlsx:"2"`

	Y float64 `xlsx:"3"`

	Z float64 `xlsx:"4"`
	// insertion for WOP pointer fields
}

var Vector3_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"X",
	"Y",
	"Z",
}

type BackRepoVector3Struct struct {
	// stores Vector3DB according to their gorm ID
	Map_Vector3DBID_Vector3DB map[uint]*Vector3DB

	// stores Vector3DB ID according to Vector3 address
	Map_Vector3Ptr_Vector3DBID map[*models.Vector3]uint

	// stores Vector3 according to their gorm ID
	Map_Vector3DBID_Vector3Ptr map[uint]*models.Vector3

	db db.DBInterface

	stage *models.Stage
}

func (backRepoVector3 *BackRepoVector3Struct) GetStage() (stage *models.Stage) {
	stage = backRepoVector3.stage
	return
}

func (backRepoVector3 *BackRepoVector3Struct) GetDB() db.DBInterface {
	return backRepoVector3.db
}

// GetVector3DBFromVector3Ptr is a handy function to access the back repo instance from the stage instance
func (backRepoVector3 *BackRepoVector3Struct) GetVector3DBFromVector3Ptr(vector3 *models.Vector3) (vector3DB *Vector3DB) {
	id := backRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3]
	vector3DB = backRepoVector3.Map_Vector3DBID_Vector3DB[id]
	return
}

// BackRepoVector3.CommitPhaseOne commits all staged instances of Vector3 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoVector3 *BackRepoVector3Struct) CommitPhaseOne(stage *models.Stage) (Error error) {

	var vector3s []*models.Vector3
	for vector3 := range stage.Vector3s {
		vector3s = append(vector3s, vector3)
	}

	// Sort by the order stored in _stagedOrder.
	sort.Slice(vector3s, func(i, j int) bool {
		return stage.Vector3_stagedOrder[vector3s[i]] < stage.Vector3_stagedOrder[vector3s[j]]
	})

	for _, vector3 := range vector3s {
		backRepoVector3.CommitPhaseOneInstance(vector3)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, vector3 := range backRepoVector3.Map_Vector3DBID_Vector3Ptr {
		if _, ok := stage.Vector3s[vector3]; !ok {
			backRepoVector3.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoVector3.CommitDeleteInstance commits deletion of Vector3 to the BackRepo
func (backRepoVector3 *BackRepoVector3Struct) CommitDeleteInstance(id uint) (Error error) {

	vector3 := backRepoVector3.Map_Vector3DBID_Vector3Ptr[id]

	// vector3 is not staged anymore, remove vector3DB
	vector3DB := backRepoVector3.Map_Vector3DBID_Vector3DB[id]
	db, _ := backRepoVector3.db.Unscoped()
	_, err := db.Delete(vector3DB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	delete(backRepoVector3.Map_Vector3Ptr_Vector3DBID, vector3)
	delete(backRepoVector3.Map_Vector3DBID_Vector3Ptr, id)
	delete(backRepoVector3.Map_Vector3DBID_Vector3DB, id)

	return
}

// BackRepoVector3.CommitPhaseOneInstance commits vector3 staged instances of Vector3 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoVector3 *BackRepoVector3Struct) CommitPhaseOneInstance(vector3 *models.Vector3) (Error error) {

	// check if the vector3 is not commited yet
	if _, ok := backRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3]; ok {
		return
	}

	// initiate vector3
	var vector3DB Vector3DB
	vector3DB.CopyBasicFieldsFromVector3(vector3)

	_, err := backRepoVector3.db.Create(&vector3DB)
	if err != nil {
		log.Fatal(err)
	}

	// update stores
	backRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3] = vector3DB.ID
	backRepoVector3.Map_Vector3DBID_Vector3Ptr[vector3DB.ID] = vector3
	backRepoVector3.Map_Vector3DBID_Vector3DB[vector3DB.ID] = &vector3DB

	return
}

// BackRepoVector3.CommitPhaseTwo commits all staged instances of Vector3 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoVector3 *BackRepoVector3Struct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, vector3 := range backRepoVector3.Map_Vector3DBID_Vector3Ptr {
		backRepoVector3.CommitPhaseTwoInstance(backRepo, idx, vector3)
	}

	return
}

// BackRepoVector3.CommitPhaseTwoInstance commits {{structname }} of models.Vector3 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoVector3 *BackRepoVector3Struct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, vector3 *models.Vector3) (Error error) {

	// fetch matching vector3DB
	if vector3DB, ok := backRepoVector3.Map_Vector3DBID_Vector3DB[idx]; ok {

		vector3DB.CopyBasicFieldsFromVector3(vector3)

		// insertion point for translating pointers encodings into actual pointers
		_, err := backRepoVector3.db.Save(vector3DB)
		if err != nil {
			log.Fatal(err)
		}

	} else {
		err := fmt.Errorf("Unkown Vector3 intance %s", vector3.Name)
		return err
	}

	return
}

// BackRepoVector3.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoVector3 *BackRepoVector3Struct) CheckoutPhaseOne() (Error error) {

	vector3DBArray := make([]Vector3DB, 0)
	_, err := backRepoVector3.db.Find(&vector3DBArray)
	if err != nil {
		return err
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	vector3InstancesToBeRemovedFromTheStage := make(map[*models.Vector3]any)
	for key, value := range backRepoVector3.stage.Vector3s {
		vector3InstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, vector3DB := range vector3DBArray {
		backRepoVector3.CheckoutPhaseOneInstance(&vector3DB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		vector3, ok := backRepoVector3.Map_Vector3DBID_Vector3Ptr[vector3DB.ID]
		if ok {
			delete(vector3InstancesToBeRemovedFromTheStage, vector3)
		}
	}

	// remove from stage and back repo's 3 maps all vector3s that are not in the checkout
	for vector3 := range vector3InstancesToBeRemovedFromTheStage {
		vector3.Unstage(backRepoVector3.GetStage())

		// remove instance from the back repo 3 maps
		vector3ID := backRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3]
		delete(backRepoVector3.Map_Vector3Ptr_Vector3DBID, vector3)
		delete(backRepoVector3.Map_Vector3DBID_Vector3DB, vector3ID)
		delete(backRepoVector3.Map_Vector3DBID_Vector3Ptr, vector3ID)
	}

	return
}

// CheckoutPhaseOneInstance takes a vector3DB that has been found in the DB, updates the backRepo and stages the
// models version of the vector3DB
func (backRepoVector3 *BackRepoVector3Struct) CheckoutPhaseOneInstance(vector3DB *Vector3DB) (Error error) {

	vector3, ok := backRepoVector3.Map_Vector3DBID_Vector3Ptr[vector3DB.ID]
	if !ok {
		vector3 = new(models.Vector3)

		backRepoVector3.Map_Vector3DBID_Vector3Ptr[vector3DB.ID] = vector3
		backRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3] = vector3DB.ID

		// append model store with the new element
		vector3.Name = vector3DB.Name_Data.String
		vector3.Stage(backRepoVector3.GetStage())
	}
	vector3DB.CopyBasicFieldsToVector3(vector3)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	vector3.Stage(backRepoVector3.GetStage())

	// preserve pointer to vector3DB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Vector3DBID_Vector3DB)[vector3DB hold variable pointers
	vector3DB_Data := *vector3DB
	preservedPtrToVector3 := &vector3DB_Data
	backRepoVector3.Map_Vector3DBID_Vector3DB[vector3DB.ID] = preservedPtrToVector3

	return
}

// BackRepoVector3.CheckoutPhaseTwo Checkouts all staged instances of Vector3 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoVector3 *BackRepoVector3Struct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, vector3DB := range backRepoVector3.Map_Vector3DBID_Vector3DB {
		backRepoVector3.CheckoutPhaseTwoInstance(backRepo, vector3DB)
	}
	return
}

// BackRepoVector3.CheckoutPhaseTwoInstance Checkouts staged instances of Vector3 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoVector3 *BackRepoVector3Struct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, vector3DB *Vector3DB) (Error error) {

	vector3 := backRepoVector3.Map_Vector3DBID_Vector3Ptr[vector3DB.ID]

	vector3DB.DecodePointers(backRepo, vector3)

	return
}

func (vector3DB *Vector3DB) DecodePointers(backRepo *BackRepoStruct, vector3 *models.Vector3) {

	// insertion point for checkout of pointer encoding
}

// CommitVector3 allows commit of a single vector3 (if already staged)
func (backRepo *BackRepoStruct) CommitVector3(vector3 *models.Vector3) {
	backRepo.BackRepoVector3.CommitPhaseOneInstance(vector3)
	if id, ok := backRepo.BackRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3]; ok {
		backRepo.BackRepoVector3.CommitPhaseTwoInstance(backRepo, id, vector3)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitVector3 allows checkout of a single vector3 (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutVector3(vector3 *models.Vector3) {
	// check if the vector3 is staged
	if _, ok := backRepo.BackRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3]; ok {

		if id, ok := backRepo.BackRepoVector3.Map_Vector3Ptr_Vector3DBID[vector3]; ok {
			var vector3DB Vector3DB
			vector3DB.ID = id

			if _, err := backRepo.BackRepoVector3.db.First(&vector3DB, id); err != nil {
				log.Fatalln("CheckoutVector3 : Problem with getting object with id:", id)
			}
			backRepo.BackRepoVector3.CheckoutPhaseOneInstance(&vector3DB)
			backRepo.BackRepoVector3.CheckoutPhaseTwoInstance(backRepo, &vector3DB)
		}
	}
}

// CopyBasicFieldsFromVector3
func (vector3DB *Vector3DB) CopyBasicFieldsFromVector3(vector3 *models.Vector3) {
	// insertion point for fields commit

	vector3DB.Name_Data.String = vector3.Name
	vector3DB.Name_Data.Valid = true

	vector3DB.X_Data.Float64 = vector3.X
	vector3DB.X_Data.Valid = true

	vector3DB.Y_Data.Float64 = vector3.Y
	vector3DB.Y_Data.Valid = true

	vector3DB.Z_Data.Float64 = vector3.Z
	vector3DB.Z_Data.Valid = true
}

// CopyBasicFieldsFromVector3_WOP
func (vector3DB *Vector3DB) CopyBasicFieldsFromVector3_WOP(vector3 *models.Vector3_WOP) {
	// insertion point for fields commit

	vector3DB.Name_Data.String = vector3.Name
	vector3DB.Name_Data.Valid = true

	vector3DB.X_Data.Float64 = vector3.X
	vector3DB.X_Data.Valid = true

	vector3DB.Y_Data.Float64 = vector3.Y
	vector3DB.Y_Data.Valid = true

	vector3DB.Z_Data.Float64 = vector3.Z
	vector3DB.Z_Data.Valid = true
}

// CopyBasicFieldsFromVector3WOP
func (vector3DB *Vector3DB) CopyBasicFieldsFromVector3WOP(vector3 *Vector3WOP) {
	// insertion point for fields commit

	vector3DB.Name_Data.String = vector3.Name
	vector3DB.Name_Data.Valid = true

	vector3DB.X_Data.Float64 = vector3.X
	vector3DB.X_Data.Valid = true

	vector3DB.Y_Data.Float64 = vector3.Y
	vector3DB.Y_Data.Valid = true

	vector3DB.Z_Data.Float64 = vector3.Z
	vector3DB.Z_Data.Valid = true
}

// CopyBasicFieldsToVector3
func (vector3DB *Vector3DB) CopyBasicFieldsToVector3(vector3 *models.Vector3) {
	// insertion point for checkout of basic fields (back repo to stage)
	vector3.Name = vector3DB.Name_Data.String
	vector3.X = vector3DB.X_Data.Float64
	vector3.Y = vector3DB.Y_Data.Float64
	vector3.Z = vector3DB.Z_Data.Float64
}

// CopyBasicFieldsToVector3_WOP
func (vector3DB *Vector3DB) CopyBasicFieldsToVector3_WOP(vector3 *models.Vector3_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	vector3.Name = vector3DB.Name_Data.String
	vector3.X = vector3DB.X_Data.Float64
	vector3.Y = vector3DB.Y_Data.Float64
	vector3.Z = vector3DB.Z_Data.Float64
}

// CopyBasicFieldsToVector3WOP
func (vector3DB *Vector3DB) CopyBasicFieldsToVector3WOP(vector3 *Vector3WOP) {
	vector3.ID = int(vector3DB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	vector3.Name = vector3DB.Name_Data.String
	vector3.X = vector3DB.X_Data.Float64
	vector3.Y = vector3DB.Y_Data.Float64
	vector3.Z = vector3DB.Z_Data.Float64
}

// Backup generates a json file from a slice of all Vector3DB instances in the backrepo
func (backRepoVector3 *BackRepoVector3Struct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Vector3DB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Vector3DB, 0)
	for _, vector3DB := range backRepoVector3.Map_Vector3DBID_Vector3DB {
		forBackup = append(forBackup, vector3DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Vector3 ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Vector3 file", err.Error())
	}
}

// Backup generates a json file from a slice of all Vector3DB instances in the backrepo
func (backRepoVector3 *BackRepoVector3Struct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Vector3DB, 0)
	for _, vector3DB := range backRepoVector3.Map_Vector3DBID_Vector3DB {
		forBackup = append(forBackup, vector3DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Vector3")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Vector3_Fields, -1)
	for _, vector3DB := range forBackup {

		var vector3WOP Vector3WOP
		vector3DB.CopyBasicFieldsToVector3WOP(&vector3WOP)

		row := sh.AddRow()
		row.WriteStruct(&vector3WOP, -1)
	}
}

// RestoreXL from the "Vector3" sheet all Vector3DB instances
func (backRepoVector3 *BackRepoVector3Struct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoVector3id_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Vector3"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoVector3.rowVisitorVector3)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoVector3 *BackRepoVector3Struct) rowVisitorVector3(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var vector3WOP Vector3WOP
		row.ReadStruct(&vector3WOP)

		// add the unmarshalled struct to the stage
		vector3DB := new(Vector3DB)
		vector3DB.CopyBasicFieldsFromVector3WOP(&vector3WOP)

		vector3DB_ID_atBackupTime := vector3DB.ID
		vector3DB.ID = 0
		_, err := backRepoVector3.db.Create(vector3DB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoVector3.Map_Vector3DBID_Vector3DB[vector3DB.ID] = vector3DB
		BackRepoVector3id_atBckpTime_newID[vector3DB_ID_atBackupTime] = vector3DB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Vector3DB.json" in dirPath that stores an array
// of Vector3DB and stores it in the database
// the map BackRepoVector3id_atBckpTime_newID is updated accordingly
func (backRepoVector3 *BackRepoVector3Struct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoVector3id_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Vector3DB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Vector3 file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Vector3DB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Vector3DBID_Vector3DB
	for _, vector3DB := range forRestore {

		vector3DB_ID_atBackupTime := vector3DB.ID
		vector3DB.ID = 0
		_, err := backRepoVector3.db.Create(vector3DB)
		if err != nil {
			log.Fatal(err)
		}
		backRepoVector3.Map_Vector3DBID_Vector3DB[vector3DB.ID] = vector3DB
		BackRepoVector3id_atBckpTime_newID[vector3DB_ID_atBackupTime] = vector3DB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Vector3 file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Vector3>id_atBckpTime_newID
// to compute new index
func (backRepoVector3 *BackRepoVector3Struct) RestorePhaseTwo() {

	for _, vector3DB := range backRepoVector3.Map_Vector3DBID_Vector3DB {

		// next line of code is to avert unused variable compilation error
		_ = vector3DB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		db, _ := backRepoVector3.db.Model(vector3DB)
		_, err := db.Updates(*vector3DB)
		if err != nil {
			log.Fatal(err)
		}
	}

}

// BackRepoVector3.ResetReversePointers commits all staged instances of Vector3 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoVector3 *BackRepoVector3Struct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, vector3 := range backRepoVector3.Map_Vector3DBID_Vector3Ptr {
		backRepoVector3.ResetReversePointersInstance(backRepo, idx, vector3)
	}

	return
}

func (backRepoVector3 *BackRepoVector3Struct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, vector3 *models.Vector3) (Error error) {

	// fetch matching vector3DB
	if vector3DB, ok := backRepoVector3.Map_Vector3DBID_Vector3DB[idx]; ok {
		_ = vector3DB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoVector3id_atBckpTime_newID map[uint]uint
