name: Release Portable Apps

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_release_portable_apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install gong
        run: go install ./go/cmd/gong

      - name: Build and upload process portable app
        run: |
          cd dsm/process/go/cmd/process
          gong portable
          gh release upload ${{ github.event.release.tag_name }} process-app-portable.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and upload statemachines portable app
        run: |
          cd dsm/statemachines/go/cmd/statemachines
          gong portable
          gh release upload ${{ github.event.release.tag_name }} statemachines-app-portable.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and upload barrgraph portable app
        run: |
          cd dsm/barrgraph/go/cmd/barrgraph
          gong portable
          gh release upload ${{ github.event.release.tag_name }} barrgraph-app-portable.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and upload project portable app
        run: |
          cd dsm/project/go/cmd/project
          gong portable
          gh release upload ${{ github.event.release.tag_name }} project-app-portable.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
